<?php
/**
 * AI-Generated Theme Layout
 * Generated by AI Theme Builder
 */

if (!defined('CMS_ROOT')) define('CMS_ROOT', dirname(__DIR__, 2));
if (!defined('CMS_APP')) define('CMS_APP', CMS_ROOT . '/app');

require_once CMS_APP . '/helpers/functions.php';

if (file_exists(CMS_ROOT . '/includes/helpers/menu.php')) {
    require_once CMS_ROOT . '/includes/helpers/menu.php';
}

$jtbBootPath = CMS_ROOT . '/plugins/jessie-theme-builder/includes/jtb-frontend-boot.php';
if (file_exists($jtbBootPath)) require_once $jtbBootPath;

$themeConfig = get_theme_config();
$themeOptions = $themeConfig['options'] ?? [];
$showHeader = $themeOptions['show_header'] ?? true;
$showFooter = $themeOptions['show_footer'] ?? true;

$siteName = theme_get('brand.site_name', get_site_name());
$siteLogo = theme_get('brand.logo', get_site_logo());
$tsLogo = theme_get('brand.logo') ?: $siteLogo;

$pageData = $page ?? [];
if (!empty($title) && empty($pageData['title'])) $pageData['title'] = $title;
$isTbPage = !empty($page['is_tb_page']);

$themeCssVariables = generate_theme_css_variables($themeConfig);
$themePath = '/themes/' . basename(__DIR__);
?><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?= render_seo_meta($pageData) ?>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,600;0,9..144,700;1,9..144,400&amp;family=Figtree:wght@400;500;600;700&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/assets/css/fontawesome.min.css">
    <link rel="stylesheet" href="/assets/css/tb-frontend.css">
    <link rel="stylesheet" href="<?= $themePath ?>/assets/css/style.css">
    <style>
<?= $themeCssVariables ?>
<?= generate_studio_css_overrides() ?>
    </style>
<?= function_exists("theme_render_favicon") ? theme_render_favicon() : "" ?>
<?= function_exists("theme_render_og_image") ? theme_render_og_image() : "" ?>
</head>
<body class="<?= esc(get_body_class() ?? '') ?><?= $isTbPage ? ' tb-page' : '' ?>">
<?= function_exists("theme_render_announcement_bar") ? theme_render_announcement_bar() : "" ?>

<?php if ($showHeader): ?>
<a href="#main-content" class="skip-nav">Skip to content</a>
<header id="siteHeader" class="ss-header">
  <div class="ss-header-inner">
    <a href="/" class="ss-brand">
      <?php if ($logo = theme_get('brand.logo')): ?>
        <img src="<?= esc($logo) ?>" alt="<?= esc($siteName) ?>" class="ss-brand-img">
      <?php else: ?>
        <span class="ss-brand-text" data-ts="brand.site_name"><?= esc(theme_get('brand.site_name', $siteName)) ?></span>
      <?php endif; ?>
    </a>
    <nav id="headerNav" class="ss-nav">
      <?php echo render_menu('header', ['class' => 'ss-nav-list', 'link_class' => 'ss-nav-link', 'wrap' => false]); ?>
    </nav>
    <?php if (theme_get('header.show_cta', true)): ?>
    <a href="<?= esc(theme_get('header.cta_link', '/contact')) ?>" class="ss-cta" data-ts="header.cta_text" data-ts-href="header.cta_link"><?= esc(theme_get('header.cta_text', 'Get Started')) ?></a>
    <?php endif; ?>
    <button class="dark-mode-toggle" data-dark-toggle aria-label="Toggle dark mode" style="background:none;border:none;cursor:pointer;font-size:1.25rem;padding:4px 8px">🌙</button>
    <button id="mobileToggle" class="ss-burger" aria-label="Menu">
      <span></span><span></span><span></span>
    </button>
  </div>
</header>
<div class="mobile-overlay" id="mobileOverlay"></div>
<?php endif; ?>

<?php if ($isTbPage): ?>
    <?= $content ?? '' ?>
<?php else: ?>
    <main id="main-content"><?= $content ?? '' ?></main>
<?php endif; ?>

<?php if ($showFooter): ?>
<?php
$footerDesc = theme_get('footer.description', 'Sentinel Shield provides enterprise-grade zero-trust identity management solutions that protect your organization with passwordless authentication, biometric verification, and comprehensive compliance reporting.');
$footerCopyright = theme_get('footer.copyright', '');
$footerEmail = theme_get('footer.email', '');
$footerPhone = theme_get('footer.phone', '');
$footerAddress = theme_get('footer.address', '');
?>
<footer class="ss-footer">
    <div class="ss-footer-main">
        <div class="ss-container">
            <div class="ss-footer-layout">
                <div class="ss-footer-brand-zone">
                    <a href="/" class="ss-footer-logo" data-ts="brand.logo">
                        <?php if ($tsLogo): ?>
                            <img src="<?= esc($tsLogo) ?>" alt="<?= esc(theme_get('brand.site_name', $siteName)) ?>" height="42">
                        <?php else: ?>
                            <span class="ss-footer-logo-text" data-ts="brand.site_name"><?= esc(theme_get('brand.site_name', $siteName)) ?></span>
                        <?php endif; ?>
                    </a>
                    <p class="ss-footer-mission" data-ts="footer.description"><?= esc($footerDesc) ?></p>
                    <div class="ss-footer-trust-badges">
                        <div class="ss-trust-item">
                            <i class="fas fa-shield-alt"></i>
                            <span>SOC 2 Certified</span>
                        </div>
                        <div class="ss-trust-item">
                            <i class="fas fa-lock"></i>
                            <span>GDPR Compliant</span>
                        </div>
                        <div class="ss-trust-item">
                            <i class="fas fa-check-circle"></i>
                            <span>ISO 27001</span>
                        </div>
                    </div>
                </div>
                <div class="ss-footer-links-zone">
                    <div class="ss-footer-nav-col">
                        <h4 class="ss-footer-col-title">Platform</h4>
                        <?= render_menu('footer', ['class' => 'ss-footer-menu', 'link_class' => 'ss-footer-link', 'wrap' => false]) ?>
                    </div>
                    <div class="ss-footer-contact-col">
                        <h4 class="ss-footer-col-title">Contact</h4>
                        <div class="ss-footer-contact-list">
                            <?php if ($footerPhone): ?>
                            <a href="tel:<?= esc(preg_replace('/[^0-9+]/', '', $footerPhone)) ?>" class="ss-contact-item" data-ts="footer.phone">
                                <i class="fas fa-phone"></i>
                                <span><?= esc($footerPhone) ?></span>
                            </a>
                            <?php endif; ?>
                            <?php if ($footerEmail): ?>
                            <a href="mailto:<?= esc($footerEmail) ?>" class="ss-contact-item" data-ts="footer.email">
                                <i class="fas fa-envelope"></i>
                                <span><?= esc($footerEmail) ?></span>
                            </a>
                            <?php endif; ?>
                            <?php if ($footerAddress): ?>
                            <div class="ss-contact-item" data-ts="footer.address">
                                <i class="fas fa-map-marker-alt"></i>
                                <span><?= esc($footerAddress) ?></span>
                            </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="ss-footer-bottom">
        <div class="ss-container">
            <div class="ss-footer-base">
                <p class="ss-copyright" data-ts="footer.copyright">
                    <?= $footerCopyright ? esc($footerCopyright) : '&copy; ' . date('Y') . ' ' . esc(theme_get('brand.site_name', $siteName)) . '. All rights reserved.' ?>
                </p>
                <div class="ss-footer-social">
                    <?php if (theme_get('footer.linkedin')): ?>
                    <a href="<?= esc(theme_get('footer.linkedin')) ?>" target="_blank" rel="noopener" class="ss-social-link" aria-label="LinkedIn">
                        <i class="fab fa-linkedin-in"></i>
                    </a>
                    <?php endif; ?>
                    <?php if (theme_get('footer.twitter')): ?>
                    <a href="<?= esc(theme_get('footer.twitter')) ?>" target="_blank" rel="noopener" class="ss-social-link" aria-label="Twitter">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <?php endif; ?>
                    <?php if (theme_get('footer.github')): ?>
                    <a href="<?= esc(theme_get('footer.github')) ?>" target="_blank" rel="noopener" class="ss-social-link" aria-label="GitHub">
                        <i class="fab fa-github"></i>
                    </a>
                    <?php endif; ?>
                    <?php if (theme_get('footer.youtube')): ?>
                    <a href="<?= esc(theme_get('footer.youtube')) ?>" target="_blank" rel="noopener" class="ss-social-link" aria-label="YouTube">
                        <i class="fab fa-youtube"></i>
                    </a>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</footer>
<?php endif; ?>

<script src="<?= $themePath ?>/assets/js/main.js"></script>
<?php if (function_exists('cms_ab_testing_widget')): echo cms_ab_testing_widget(); endif; ?>
<?php if (function_exists('ai_theme_chat_widget')): echo ai_theme_chat_widget(); endif; ?>
</body>
</html>