<?php /** Social Media Admin Dashboard */ ?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Social Media — Admin</title>
<style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#0f172a;color:#e2e8f0;line-height:1.6}.wrap{max-width:1200px;margin:0 auto;padding:2rem}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:2rem}h1{font-size:1.5rem;background:linear-gradient(135deg,#8b5cf6,#06b6d4);-webkit-background-clip:text;-webkit-text-fill-color:transparent}.nav a{color:#94a3b8;text-decoration:none;margin-left:1rem;font-size:.875rem}.nav a:hover{color:#e2e8f0}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:1rem;margin-bottom:2rem}.card{background:#1e293b;border:1px solid #334155;border-radius:.75rem;padding:1.25rem}.card .num{font-size:1.75rem;font-weight:700;color:#8b5cf6}.card .label{font-size:.75rem;color:#94a3b8;text-transform:uppercase}table{width:100%;border-collapse:collapse;background:#1e293b;border:1px solid #334155;border-radius:.75rem;overflow:hidden}th{background:#334155;text-align:left;padding:.75rem 1rem;font-size:.75rem;text-transform:uppercase;color:#94a3b8}td{padding:.75rem 1rem;border-top:1px solid #334155;font-size:.875rem}.back{display:inline-block;margin-bottom:1rem;color:#8b5cf6;text-decoration:none;font-size:.875rem}.badge{display:inline-block;padding:.125rem .5rem;border-radius:9999px;font-size:.7rem;font-weight:600}.badge-pub{background:#065f46;color:#6ee7b7}.badge-sched{background:#1e3a5f;color:#7dd3fc}.badge-draft{background:#334155;color:#94a3b8}</style>
</head><body><div class="wrap"><a href="/admin" class="back">← Admin</a>
<div class="top"><h1>📱 Social Media — Dashboard</h1><div class="nav"><a href="/admin/social">Dashboard</a><a href="/admin/social/users">Users</a></div></div>
<div class="cards"><div class="card"><div class="num"><?= $totalPosts ?></div><div class="label">Total Posts</div></div><div class="card"><div class="num"><?= $published ?></div><div class="label">Published</div></div><div class="card"><div class="num"><?= $scheduled ?></div><div class="label">Scheduled</div></div><div class="card"><div class="num"><?= $accounts ?></div><div class="label">Accounts</div></div></div>
<h2 style="margin-bottom:1rem;font-size:1.1rem">Recent Posts</h2>
<table><thead><tr><th>ID</th><th>Platform</th><th>Content</th><th>User</th><th>Status</th><th>Scheduled</th></tr></thead><tbody>
<?php foreach ($recent as $p): ?><tr><td><?= $p['id'] ?></td><td><?= $p['platform'] ?></td><td><?= htmlspecialchars(mb_substr($p['content'],0,60)) ?></td><td><?= htmlspecialchars($p['email'] ?? 'N/A') ?></td><td><span class="badge <?= $p['status']==='published'?'badge-pub':($p['status']==='scheduled'?'badge-sched':'badge-draft') ?>"><?= $p['status'] ?></span></td><td><?= $p['scheduled_at'] ? substr($p['scheduled_at'],0,16) : '—' ?></td></tr><?php endforeach; ?>
<?php if (empty($recent)): ?><tr><td colspan="6" style="text-align:center;color:#64748b">No posts yet</td></tr><?php endif; ?>
</tbody></table></div></body></html>
