<?php
/**
 * AI-Generated Theme Layout
 * Generated by AI Theme Builder
 */

if (!defined('CMS_ROOT')) define('CMS_ROOT', dirname(__DIR__, 2));
if (!defined('CMS_APP')) define('CMS_APP', CMS_ROOT . '/app');

require_once CMS_APP . '/helpers/functions.php';

if (file_exists(CMS_ROOT . '/includes/helpers/menu.php')) {
    require_once CMS_ROOT . '/includes/helpers/menu.php';
}

$jtbBootPath = CMS_ROOT . '/plugins/jessie-theme-builder/includes/jtb-frontend-boot.php';
if (file_exists($jtbBootPath)) require_once $jtbBootPath;

$themeConfig = get_theme_config();
$themeOptions = $themeConfig['options'] ?? [];
$showHeader = $themeOptions['show_header'] ?? true;
$showFooter = $themeOptions['show_footer'] ?? true;

$siteName = theme_get('brand.site_name', get_site_name());
$siteLogo = theme_get('brand.logo', get_site_logo());
$tsLogo = theme_get('brand.logo') ?: $siteLogo;

$pageData = $page ?? [];
if (!empty($title) && empty($pageData['title'])) $pageData['title'] = $title;
$isTbPage = !empty($page['is_tb_page']);

$themeCssVariables = generate_theme_css_variables($themeConfig);
$themePath = '/themes/' . basename(__DIR__);
?><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?= render_seo_meta($pageData) ?>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800&amp;family=Work+Sans:wght@400;500;600&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/assets/css/fontawesome.min.css">
    <link rel="stylesheet" href="/assets/css/tb-frontend.css">
    <link rel="stylesheet" href="<?= $themePath ?>/assets/css/style.css">
    <style>
<?= $themeCssVariables ?>
<?= generate_studio_css_overrides() ?>
    </style>
<?= function_exists("theme_render_favicon") ? theme_render_favicon() : "" ?>
<?= function_exists("theme_render_og_image") ? theme_render_og_image() : "" ?>
</head>
<body class="<?= esc(get_body_class() ?? '') ?><?= $isTbPage ? ' tb-page' : '' ?>">
<?= function_exists("theme_render_announcement_bar") ? theme_render_announcement_bar() : "" ?>

<?php if ($showHeader): ?>
<?php
$headerPhone = theme_get('header.phone', '+1 (888) 555-0123');
$headerEmail = theme_get('header.email', 'hello@emberanalytics.io');
?>
<a href="#main-content" class="skip-nav">Skip to content</a>
<header class="ea-masthead" id="siteHeader">
    <div class="ea-topbar">
        <div class="ea-topbar-inner">
            <div class="ea-topbar-contact">
                <?php if ($headerPhone): ?>
                <a href="tel:<?= esc(preg_replace('/[^0-9+]/', '', $headerPhone)) ?>" class="ea-topbar-link">
                    <i class="fas fa-phone-alt"></i>
                    <span data-ts="header.phone"><?= esc($headerPhone) ?></span>
                </a>
                <?php endif; ?>
                <?php if ($headerEmail): ?>
                <a href="mailto:<?= esc($headerEmail) ?>" class="ea-topbar-link">
                    <i class="fas fa-envelope"></i>
                    <span data-ts="header.email"><?= esc($headerEmail) ?></span>
                </a>
                <?php endif; ?>
            </div>
            <div class="ea-topbar-social">
                <?php if (theme_get('footer.facebook')): ?>
                <a href="<?= esc(theme_get('footer.facebook')) ?>" target="_blank" rel="noopener" aria-label="Facebook"><i class="fab fa-facebook-f"></i></a>
                <?php endif; ?>
                <?php if (theme_get('footer.twitter')): ?>
                <a href="<?= esc(theme_get('footer.twitter')) ?>" target="_blank" rel="noopener" aria-label="Twitter"><i class="fab fa-twitter"></i></a>
                <?php endif; ?>
                <?php if (theme_get('footer.linkedin')): ?>
                <a href="<?= esc(theme_get('footer.linkedin')) ?>" target="_blank" rel="noopener" aria-label="LinkedIn"><i class="fab fa-linkedin-in"></i></a>
                <?php endif; ?>
                <?php if (theme_get('footer.youtube')): ?>
                <a href="<?= esc(theme_get('footer.youtube')) ?>" target="_blank" rel="noopener" aria-label="YouTube"><i class="fab fa-youtube"></i></a>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="ea-navbar">
        <div class="ea-navbar-inner">
            <a href="/" class="ea-brand" data-ts="brand.logo">
                <?php if ($tsLogo): ?>
                    <img src="<?= esc($tsLogo) ?>" alt="<?= esc(theme_get('brand.site_name', $siteName)) ?>" class="ea-brand-img">
                <?php else: ?>
                    <span class="ea-brand-text" data-ts="brand.site_name"><?= esc(theme_get('brand.site_name', $siteName)) ?></span>
                <?php endif; ?>
            </a>
            <nav class="ea-nav" id="headerNav">
                <?= render_menu('header', ['class' => 'ea-nav-list', 'link_class' => 'ea-nav-link', 'wrap' => false]) ?>
            </nav>
            <div class="ea-navbar-actions">
                <a href="<?= esc(theme_get('header.cta_link', '#contact')) ?>" 
                   class="ea-cta-btn"
                   data-ts="header.cta_text" 
                   data-ts-href="header.cta_link">
                    <?= esc(theme_get('header.cta_text', 'Start Free Trial')) ?>
                </a>
                <button class="ea-hamburger" id="mobileToggle" aria-label="Toggle Menu">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
            </div>
        </div>
    </div>
</header>
<div class="mobile-overlay" id="mobileOverlay"></div>
<?php endif; ?>

<?php if ($isTbPage): ?>
    <?= $content ?? '' ?>
<?php else: ?>
    <main id="main-content"><?= $content ?? '' ?></main>
<?php endif; ?>

<?php if ($showFooter): ?>
<?php
$footerDesc = theme_get('footer.description', 'Ember Analytics transforms your e-commerce data into actionable insights. Real-time dashboards, predictive analytics, and seamless integrations to fuel your growth.');
$footerAddress = theme_get('footer.address', '');
$footerPhone = theme_get('footer.phone', '');
$footerEmail = theme_get('footer.email', '');
?>
<footer class="ea-footer">
    <div class="ea-footer-wave">
        <svg viewBox="0 0 1440 120" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M0,60 C360,120 720,0 1080,60 C1260,90 1380,80 1440,60 L1440,120 L0,120 Z" fill="currentColor"/>
        </svg>
    </div>
    <div class="ea-footer-main">
        <div class="ea-footer-container">
            <div class="ea-footer-grid">
                <div class="ea-footer-brand-col">
                    <a href="/" class="ea-footer-logo" data-ts="brand.logo">
                        <?php if ($tsLogo): ?>
                            <img src="<?= esc($tsLogo) ?>" alt="<?= esc(theme_get('brand.site_name', $siteName)) ?>" height="36">
                        <?php else: ?>
                            <span class="ea-footer-logo-text" data-ts="brand.site_name"><?= esc(theme_get('brand.site_name', $siteName)) ?></span>
                        <?php endif; ?>
                    </a>
                    <p class="ea-footer-desc" data-ts="footer.description"><?= esc($footerDesc) ?></p>
                    <div class="ea-footer-social">
                        <?php if (theme_get('footer.facebook')): ?>
                        <a href="<?= esc(theme_get('footer.facebook')) ?>" target="_blank" rel="noopener" aria-label="Facebook"><i class="fab fa-facebook-f"></i></a>
                        <?php endif; ?>
                        <?php if (theme_get('footer.twitter')): ?>
                        <a href="<?= esc(theme_get('footer.twitter')) ?>" target="_blank" rel="noopener" aria-label="Twitter"><i class="fab fa-twitter"></i></a>
                        <?php endif; ?>
                        <?php if (theme_get('footer.linkedin')): ?>
                        <a href="<?= esc(theme_get('footer.linkedin')) ?>" target="_blank" rel="noopener" aria-label="LinkedIn"><i class="fab fa-linkedin-in"></i></a>
                        <?php endif; ?>
                        <?php if (theme_get('footer.instagram')): ?>
                        <a href="<?= esc(theme_get('footer.instagram')) ?>" target="_blank" rel="noopener" aria-label="Instagram"><i class="fab fa-instagram"></i></a>
                        <?php endif; ?>
                        <?php if (theme_get('footer.youtube')): ?>
                        <a href="<?= esc(theme_get('footer.youtube')) ?>" target="_blank" rel="noopener" aria-label="YouTube"><i class="fab fa-youtube"></i></a>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="ea-footer-links-col">
                    <h4 class="ea-footer-heading"><?= esc(theme_get('footer.nav_title', 'Quick Links')) ?></h4>
                    <?= render_menu('footer', ['class' => 'ea-footer-nav', 'link_class' => 'ea-footer-link', 'wrap' => false]) ?>
                </div>
                <div class="ea-footer-contact-col">
                    <h4 class="ea-footer-heading"><?= esc(theme_get('footer.contact_title', 'Get in Touch')) ?></h4>
                    <ul class="ea-footer-contact-list">
                        <?php if ($footerAddress): ?>
                        <li>
                            <i class="fas fa-map-marker-alt"></i>
                            <span data-ts="footer.address"><?= esc($footerAddress) ?></span>
                        </li>
                        <?php endif; ?>
                        <?php if ($footerPhone): ?>
                        <li>
                            <i class="fas fa-phone-alt"></i>
                            <a href="tel:<?= esc(preg_replace('/[^0-9+]/', '', $footerPhone)) ?>" data-ts="footer.phone"><?= esc($footerPhone) ?></a>
                        </li>
                        <?php endif; ?>
                        <?php if ($footerEmail): ?>
                        <li>
                            <i class="fas fa-envelope"></i>
                            <a href="mailto:<?= esc($footerEmail) ?>" data-ts="footer.email"><?= esc($footerEmail) ?></a>
                        </li>
                        <?php endif; ?>
                    </ul>
                </div>
                <div class="ea-footer-newsletter-col">
                    <h4 class="ea-footer-heading"><?= esc(theme_get('footer.newsletter_title', 'Stay Updated')) ?></h4>
                    <p class="ea-footer-newsletter-desc"><?= esc(theme_get('footer.newsletter_desc', 'Get the latest analytics tips and product updates delivered to your inbox.')) ?></p>
                    <form class="ea-footer-newsletter-form">
                        <div class="ea-newsletter-input-wrap">
                            <input type="email" placeholder="Enter your email" class="ea-newsletter-input" required>
                            <button type="submit" class="ea-newsletter-btn">
                                <i class="fas fa-paper-plane"></i>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="ea-footer-bottom">
        <div class="ea-footer-container">
            <p class="ea-footer-copyright" data-ts="footer.copyright">
                <?= theme_get('footer.copyright') ? esc(theme_get('footer.copyright')) : '&copy; ' . date('Y') . ' ' . esc(theme_get('brand.site_name', $siteName)) . '. All rights reserved.' ?>
            </p>
        </div>
    </div>
</footer>
<?php endif; ?>

<script src="<?= $themePath ?>/assets/js/main.js"></script>
<?php if (function_exists('cms_ab_testing_widget')): echo cms_ab_testing_widget(); endif; ?>
<?php if (function_exists('ai_theme_chat_widget')): echo ai_theme_chat_widget(); endif; ?>
</body>
</html>