<?php
/**
 * Core Configuration Constants
 * Auto-generated by Roo Debug Agent
 */

// Debugging and Error Reporting
if (!defined('DEBUG_MODE')) define('DEBUG_MODE', true);
if (!defined('DEV_MODE')) define('DEV_MODE', false);
if (!defined('ERROR_REPORTING')) define('ERROR_REPORTING', E_ALL);
ini_set('display_errors', DEBUG_MODE ? '1' : '0');
ini_set('log_errors', '1');

// Security Settings
if (!defined('CSRF_TOKEN_LIFETIME')) define('CSRF_TOKEN_LIFETIME', 3600); // 1 hour
if (!defined('PASSWORD_HASH_COST')) define('PASSWORD_HASH_COST', 12);

// Path Constants
if (!defined('ROOT_PATH')) define('ROOT_PATH', dirname(__DIR__));
if (!defined('LOG_PATH')) define('LOG_PATH', ROOT_PATH . '/logs');

// Database Constants (overridable in config.php)
if (!defined('DB_HOST')) define('DB_HOST', $_ENV['DB_HOST'] ?? 'localhost');
if (!defined('DB_NAME')) define('DB_NAME', 'cms');
if (!defined('DB_USER')) define('DB_USER', 'cms_user');
if (!defined('DB_PASS')) define('DB_PASS', 'secure_password_123');

// Load additional config if exists
if (file_exists(__DIR__ . '/config.php')) {
    require_once __DIR__ . '/config.php';
}
