<?php
/**
 * Jessie CMS Installer
 * Web-based installation wizard
 * Delete this file after installation!
 */

// Prevent running if already installed
if (file_exists(__DIR__ . '/config.php')) {
    $cfg = require __DIR__ . '/config.php';
    if (!empty($cfg['db_host']) || !empty($cfg['DB_HOST'])) {
        echo '<h1>Jessie CMS is already installed.</h1><p><a href="/admin/">Go to Admin</a></p>';
        exit;
    }
}

$step = (int)($_GET['step'] ?? 1);
$error = '';
$success = '';

// Handle form submissions
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $step = (int)($_POST['step'] ?? 1);

    if ($step === 1) {
        // Requirements check — auto-advance
        $step = 2;
    }
    elseif ($step === 2) {
        // Database configuration
        $dbHost = trim($_POST['db_host'] ?? 'localhost');
        $dbPort = trim($_POST['db_port'] ?? '3306');
        $dbName = trim($_POST['db_name'] ?? '');
        $dbUser = trim($_POST['db_user'] ?? '');
        $dbPass = $_POST['db_pass'] ?? '';

        if (empty($dbName) || empty($dbUser)) {
            $error = 'Database name and username are required.';
            $step = 2;
        } else {
            // Test connection
            try {
                $dsn = "mysql:host={$dbHost};port={$dbPort};charset=utf8mb4";
                $pdo = new PDO($dsn, $dbUser, $dbPass, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);

                // Create database if it doesn't exist
                $pdo->exec("CREATE DATABASE IF NOT EXISTS `{$dbName}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
                $pdo->exec("USE `{$dbName}`");

                // Import schema
                $schemaFile = __DIR__ . '/database/schema.sql';
                if (file_exists($schemaFile)) {
                    $sql = file_get_contents($schemaFile);
                    $pdo->exec($sql);
                }


                // Write config.php
                $configContent = "<?php\n"
                    . "/**\n * Jessie CMS Configuration\n * Generated by installer on " . date('Y-m-d H:i:s') . "\n */\n\n"
                    . "// Database\n"
                    . "define('DB_HOST', " . var_export($dbHost, true) . ");\n"
                    . "define('DB_PORT', " . var_export($dbPort, true) . ");\n"
                    . "define('DB_NAME', " . var_export($dbName, true) . ");\n"
                    . "define('DB_USER', " . var_export($dbUser, true) . ");\n"
                    . "define('DB_PASS', " . var_export($dbPass, true) . ");\n"
                    . "define('DB_CHARSET', 'utf8mb4');\n\n"
                    . "// Paths\n"
                    . "define('CMS_ROOT', __DIR__);\n"
                    . "define('CMS_APP', CMS_ROOT . '/app');\n"
                    . "define('CMS_CONFIG', CMS_ROOT . '/config');\n"
                    . "define('CMS_UPLOADS', CMS_ROOT . '/public/uploads');\n\n"
                    . "// Security\n"
                    . "define('CMS_DEBUG', false);\n"
                    . "define('CMS_ENV', 'production');\n";

                file_put_contents(__DIR__ . '/config.php', $configContent);

                // Ensure extension tables exist (shop, dropshipping)
                if (!defined('CMS_ROOT')) { define('CMS_ROOT', __DIR__); }
                require_once __DIR__ . '/db.php';
                require_once __DIR__ . '/core/shop-coupons.php';
                require_once __DIR__ . '/core/shop-variants.php';
                require_once __DIR__ . '/core/shop-reviews.php';
                require_once __DIR__ . '/core/shop-digital.php';
                require_once __DIR__ . '/core/shop-wishlist.php';
                require_once __DIR__ . '/core/shop-analytics.php';
                require_once __DIR__ . '/core/shop-abandoned-carts.php';
                require_once __DIR__ . '/core/dropshipping.php';
                ShopCoupons::ensureTable();
                ShopVariants::ensureTable();
                ShopReviews::ensureTable();
                ShopDigital::ensureTable();
                ShopWishlist::ensureTable();
                ShopAnalytics::ensureTable();
                AbandonedCarts::ensureTable();
                Dropshipping::ensureTables();

                // Run plugin install scripts
                $pluginsDir = __DIR__ . '/plugins';
                if (is_dir($pluginsDir)) {
                    foreach (scandir($pluginsDir) as $pluginName) {
                        if ($pluginName === '.' || $pluginName === '..') continue;
                        $installFile = $pluginsDir . '/' . $pluginName . '/install.php';
                        if (file_exists($installFile)) {
                            try { require_once $installFile; } catch (\Throwable $e) {}
                        }
                    }
                }
                $_SESSION['install_db_ok'] = true;
                $step = 3;
            } catch (PDOException $e) {
                $error = 'Database connection failed: ' . $e->getMessage();
                $step = 2;
            }
        }
    }
    elseif ($step === 3) {
        // Admin account
        $username = trim($_POST['admin_user'] ?? '');
        $email = trim($_POST['admin_email'] ?? '');
        $password = $_POST['admin_pass'] ?? '';
        $siteName = trim($_POST['site_name'] ?? 'My Website');
        $siteUrl = trim($_POST['site_url'] ?? '');

        if (empty($username) || empty($password)) {
            $error = 'Username and password are required.';
            $step = 3;
        } elseif (strlen($password) < 8) {
            $error = 'Password must be at least 8 characters.';
            $step = 3;
        } else {
            try {
                require_once __DIR__ . '/config.php';
                $dsn = "mysql:host=" . DB_HOST . ";port=" . DB_PORT . ";dbname=" . DB_NAME . ";charset=utf8mb4";
                $pdo = new PDO($dsn, DB_USER, DB_PASS, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);

                // Create admin user
                $hash = password_hash($password, PASSWORD_DEFAULT);
                $stmt = $pdo->prepare("INSERT INTO admins (username, email, password_hash, role, created_at) VALUES (?, ?, ?, 'admin', NOW())
                    ON DUPLICATE KEY UPDATE password_hash = VALUES(password_hash), email = VALUES(email)");
                $stmt->execute([$username, $email ?: null, $hash]);

                // Save site settings
                $settings = [
                    'site_name' => $siteName,
                    'site_url' => $siteUrl ?: ('https://' . ($_SERVER['HTTP_HOST'] ?? 'localhost')),
                    'admin_email' => $email,
                    'setup_wizard_completed' => '0', // Will show setup wizard on first login
                ];
                foreach ($settings as $key => $value) {
                    $stmt = $pdo->prepare("INSERT INTO settings (`key`, `value`) VALUES (?, ?) ON DUPLICATE KEY UPDATE `value` = VALUES(`value`)");
                    $stmt->execute([$key, $value]);
                }

                $step = 4;
            } catch (PDOException $e) {
                $error = 'Setup failed: ' . $e->getMessage();
                $step = 3;
            }
        }
    }
}

// Requirements check data
$requirements = [
    ['PHP 8.2+', version_compare(PHP_VERSION, '8.2.0', '>='), PHP_VERSION],
    ['PDO MySQL', extension_loaded('pdo_mysql'), extension_loaded('pdo_mysql') ? 'Loaded' : 'Missing'],
    ['GD Extension', extension_loaded('gd'), extension_loaded('gd') ? 'Loaded' : 'Missing (optional)'],
    ['cURL Extension', extension_loaded('curl'), extension_loaded('curl') ? 'Loaded' : 'Missing'],
    ['JSON Extension', extension_loaded('json'), extension_loaded('json') ? 'Loaded' : 'Missing'],
    ['mbstring Extension', extension_loaded('mbstring'), extension_loaded('mbstring') ? 'Loaded' : 'Missing'],
    ['config.php writable', is_writable(__DIR__) || is_writable(__DIR__ . '/config.php'), is_writable(__DIR__) ? 'Yes' : 'No — check permissions'],
    ['uploads/ writable', is_writable(__DIR__ . '/public/uploads') || !is_dir(__DIR__ . '/public/uploads'), is_writable(__DIR__ . '/public/uploads') ? 'Yes' : 'Create /public/uploads/'],
    ['mod_rewrite', function_exists('apache_get_modules') ? in_array('mod_rewrite', apache_get_modules()) : true, 'Assumed OK'],
];
$allPassed = array_reduce($requirements, fn($carry, $r) => $carry && $r[1], true);
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Install — Jessie CMS</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0f172a; color: #e2e8f0; min-height: 100vh; display: flex; align-items: center; justify-content: center; }
        .installer { max-width: 600px; width: 100%; margin: 40px 20px; }
        .logo { text-align: center; margin-bottom: 32px; }
        .logo h1 { font-size: 2rem; font-weight: 800; }
        .logo h1 span { color: #6366f1; }
        .logo p { color: #94a3b8; font-size: 0.9rem; margin-top: 4px; }
        .card { background: #1e293b; border: 1px solid #334155; border-radius: 12px; padding: 32px; }
        .steps { display: flex; gap: 8px; margin-bottom: 24px; }
        .step-dot { width: 100%; height: 4px; border-radius: 2px; background: #334155; }
        .step-dot.active { background: #6366f1; }
        .step-dot.done { background: #22c55e; }
        h2 { font-size: 1.3rem; margin-bottom: 16px; }
        .form-group { margin-bottom: 16px; }
        label { display: block; font-size: 0.85rem; color: #94a3b8; margin-bottom: 4px; }
        input[type="text"], input[type="email"], input[type="password"], input[type="number"], input[type="url"] {
            width: 100%; padding: 10px 14px; border-radius: 8px; border: 1px solid #334155; background: #0f172a; color: #e2e8f0; font-size: 0.95rem;
        }
        input:focus { outline: none; border-color: #6366f1; }
        .btn { display: inline-block; padding: 12px 28px; border-radius: 8px; background: #6366f1; color: #fff; border: none; font-size: 1rem; cursor: pointer; font-weight: 600; text-decoration: none; }
        .btn:hover { background: #4f46e5; }
        .btn-block { width: 100%; text-align: center; }
        .alert { padding: 12px 16px; border-radius: 8px; margin-bottom: 16px; font-size: 0.9rem; }
        .alert-error { background: rgba(239,68,68,0.15); color: #ef4444; border: 1px solid rgba(239,68,68,0.3); }
        .alert-success { background: rgba(34,197,94,0.15); color: #22c55e; border: 1px solid rgba(34,197,94,0.3); }
        .req-table { width: 100%; margin: 16px 0; }
        .req-table td { padding: 8px 0; border-bottom: 1px solid #334155; font-size: 0.9rem; }
        .req-table td:last-child { text-align: right; }
        .pass { color: #22c55e; }
        .fail { color: #ef4444; }
        .row { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
        .success-icon { font-size: 4rem; text-align: center; margin: 20px 0; }
    </style>
</head>
<body>
<div class="installer">
    <div class="logo">
        <h1>🐕 Jessie <span>CMS</span></h1>
        <p>Installation Wizard</p>
    </div>

    <div class="steps">
        <div class="step-dot <?= $step > 1 ? 'done' : ($step === 1 ? 'active' : '') ?>"></div>
        <div class="step-dot <?= $step > 2 ? 'done' : ($step === 2 ? 'active' : '') ?>"></div>
        <div class="step-dot <?= $step > 3 ? 'done' : ($step === 3 ? 'active' : '') ?>"></div>
        <div class="step-dot <?= $step >= 4 ? 'done' : '' ?>"></div>
    </div>

    <div class="card">
        <?php if ($error): ?>
            <div class="alert alert-error"><?= htmlspecialchars($error) ?></div>
        <?php endif; ?>

        <?php if ($step === 1): ?>
            <h2>Step 1 — Requirements Check</h2>
            <table class="req-table">
                <?php foreach ($requirements as $r): ?>
                <tr>
                    <td><?= $r[0] ?></td>
                    <td class="<?= $r[1] ? 'pass' : 'fail' ?>"><?= $r[1] ? '✅' : '❌' ?> <?= htmlspecialchars($r[2]) ?></td>
                </tr>
                <?php endforeach; ?>
            </table>
            <?php if ($allPassed): ?>
                <form method="post"><input type="hidden" name="step" value="1">
                    <button type="submit" class="btn btn-block">Continue →</button>
                </form>
            <?php else: ?>
                <div class="alert alert-error">Please fix the requirements above before continuing.</div>
            <?php endif; ?>

        <?php elseif ($step === 2): ?>
            <h2>Step 2 — Database</h2>
            <form method="post">
                <input type="hidden" name="step" value="2">
                <div class="row">
                    <div class="form-group">
                        <label>Host</label>
                        <input type="text" name="db_host" value="<?= htmlspecialchars($_POST['db_host'] ?? 'localhost') ?>" required>
                    </div>
                    <div class="form-group">
                        <label>Port</label>
                        <input type="number" name="db_port" value="<?= htmlspecialchars($_POST['db_port'] ?? '3306') ?>">
                    </div>
                </div>
                <div class="form-group">
                    <label>Database Name</label>
                    <input type="text" name="db_name" value="<?= htmlspecialchars($_POST['db_name'] ?? 'jessie_cms') ?>" required>
                </div>
                <div class="row">
                    <div class="form-group">
                        <label>Username</label>
                        <input type="text" name="db_user" value="<?= htmlspecialchars($_POST['db_user'] ?? 'root') ?>" required>
                    </div>
                    <div class="form-group">
                        <label>Password</label>
                        <input type="password" name="db_pass" value="">
                    </div>
                </div>
                <button type="submit" class="btn btn-block">Test & Create Database →</button>
            </form>

        <?php elseif ($step === 3): ?>
            <h2>Step 3 — Site & Admin</h2>
            <form method="post">
                <input type="hidden" name="step" value="3">
                <div class="form-group">
                    <label>Site Name</label>
                    <input type="text" name="site_name" value="<?= htmlspecialchars($_POST['site_name'] ?? 'My Website') ?>" required>
                </div>
                <div class="form-group">
                    <label>Site URL</label>
                    <input type="url" name="site_url" value="<?= htmlspecialchars($_POST['site_url'] ?? ('https://' . ($_SERVER['HTTP_HOST'] ?? 'localhost'))) ?>">
                </div>
                <hr style="border-color: #334155; margin: 20px 0;">
                <div class="row">
                    <div class="form-group">
                        <label>Admin Username</label>
                        <input type="text" name="admin_user" value="<?= htmlspecialchars($_POST['admin_user'] ?? 'admin') ?>" required minlength="3">
                    </div>
                    <div class="form-group">
                        <label>Admin Email</label>
                        <input type="email" name="admin_email" value="<?= htmlspecialchars($_POST['admin_email'] ?? '') ?>">
                    </div>
                </div>
                <div class="form-group">
                    <label>Admin Password (min 8 characters)</label>
                    <input type="password" name="admin_pass" required minlength="8">
                </div>
                <button type="submit" class="btn btn-block">Create Admin & Finish →</button>
            </form>

        <?php elseif ($step === 4): ?>
            <div class="success-icon">🎉</div>
            <h2 style="text-align: center;">Installation Complete!</h2>
            <p style="text-align: center; color: #94a3b8; margin: 16px 0;">
                Jessie CMS is ready. For security, <strong>delete install.php</strong> now.
            </p>
            <div style="display: flex; gap: 12px; margin-top: 24px;">
                <a href="/" class="btn" style="flex: 1; text-align: center; background: #334155;">View Site</a>
                <a href="/admin/" class="btn" style="flex: 1; text-align: center;">Admin Panel →</a>
            </div>
        <?php endif; ?>
    </div>
</div>
</body>
</html>
