<?php
/**
 * AI-Generated Theme Layout
 * Generated by AI Theme Builder
 */

if (!defined('CMS_ROOT')) define('CMS_ROOT', dirname(__DIR__, 2));
if (!defined('CMS_APP')) define('CMS_APP', CMS_ROOT . '/app');

require_once CMS_APP . '/helpers/functions.php';

if (file_exists(CMS_ROOT . '/includes/helpers/menu.php')) {
    require_once CMS_ROOT . '/includes/helpers/menu.php';
}

$jtbBootPath = CMS_ROOT . '/plugins/jessie-theme-builder/includes/jtb-frontend-boot.php';
if (file_exists($jtbBootPath)) require_once $jtbBootPath;

$themeConfig = get_theme_config();
$themeOptions = $themeConfig['options'] ?? [];
$showHeader = $themeOptions['show_header'] ?? true;
$showFooter = $themeOptions['show_footer'] ?? true;

$siteName = theme_get('brand.site_name', get_site_name());
$siteLogo = theme_get('brand.logo', get_site_logo());
$tsLogo = theme_get('brand.logo') ?: $siteLogo;

$pageData = $page ?? [];
if (!empty($title) && empty($pageData['title'])) $pageData['title'] = $title;
$isTbPage = !empty($page['is_tb_page']);

$themeCssVariables = generate_theme_css_variables($themeConfig);
$themePath = '/themes/' . basename(__DIR__);
?><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?= render_seo_meta($pageData) ?>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Bitter:wght@400;600;700;800&amp;family=Rubik:wght@300;400;500;600;700&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/assets/css/fontawesome.min.css">
    <link rel="stylesheet" href="/assets/css/tb-frontend.css">
    <link rel="stylesheet" href="<?= $themePath ?>/assets/css/style.css">
    <style>
<?= $themeCssVariables ?>
<?= generate_studio_css_overrides() ?>
    </style>
<?= function_exists("theme_render_favicon") ? theme_render_favicon() : "" ?>
<?= function_exists("theme_render_og_image") ? theme_render_og_image() : "" ?>
</head>
<body class="<?= esc(get_body_class() ?? '') ?><?= $isTbPage ? ' tb-page' : '' ?>">
<?= function_exists("theme_render_announcement_bar") ? theme_render_announcement_bar() : "" ?>

<?php if ($showHeader): ?>
<?php
$headerPhone = theme_get('header.phone', '');
$headerEmail = theme_get('header.email', '');
$headerCtaText = theme_get('header.cta_text', 'Start Free Trial');
$headerCtaLink = theme_get('header.cta_link', '#contact');
?>
<a href="#main-content" class="skip-nav">Skip to content</a>
<header id="siteHeader" class="vp-header">
    <div class="vp-header-inner">
        <div class="vp-brand-block">
            <a href="/" class="vp-logo-link">
                <?php if ($tsLogo): ?>
                    <img src="<?= esc($tsLogo) ?>" alt="<?= esc(theme_get('brand.site_name', $siteName)) ?>" class="vp-logo-img">
                <?php else: ?>
                    <span class="vp-logo-text" data-ts="brand.site_name"><?= esc(theme_get('brand.site_name', $siteName)) ?></span>
                <?php endif; ?>
            </a>
            <p class="vp-brand-tagline" data-ts="header.tagline"><?= esc(theme_get('header.tagline', 'Premium WordPress hosting that scales with you')) ?></p>
        </div>
        
        <div class="vp-header-right">
            <nav id="headerNav" class="vp-nav">
                <?= render_menu('header', ['class' => 'vp-nav-links', 'link_class' => 'vp-nav-link', 'wrap' => false]) ?>
            </nav>
            
            <div class="vp-header-actions">
                <?php if ($headerPhone): ?>
                <a href="tel:<?= esc(preg_replace('/[^0-9+]/', '', $headerPhone)) ?>" class="vp-phone-link" data-ts="header.phone">
                    <i class="fas fa-phone"></i>
                    <span><?= esc($headerPhone) ?></span>
                </a>
                <?php endif; ?>
                
                <a href="<?= esc($headerCtaLink) ?>" class="vp-cta-btn" data-ts="header.cta_text" data-ts-href="header.cta_link">
                    <?= esc($headerCtaText) ?>
                </a>
            </div>
            
            <button class="dark-mode-toggle" data-dark-toggle aria-label="Toggle dark mode" style="background:none;border:none;cursor:pointer;font-size:1.25rem;padding:4px 8px">🌙</button>
    <button id="mobileToggle" class="vp-mobile-toggle" aria-label="Menu">
                <span></span>
                <span></span>
                <span></span>
            </button>
        </div>
    </div>
</header>
<div class="mobile-overlay" id="mobileOverlay"></div>
<?php endif; ?>

<?php if ($isTbPage): ?>
    <?= $content ?? '' ?>
<?php else: ?>
    <main id="main-content"><?= $content ?? '' ?></main>
<?php endif; ?>

<?php if ($showFooter): ?>
<?php
$footerDesc = theme_get('footer.description', 'VerdantPress delivers enterprise-grade WordPress hosting with automated workflows, expert support, and infrastructure built for performance.');
$footerAddress = theme_get('footer.address', '');
$footerPhone = theme_get('footer.phone', '');
$footerEmail = theme_get('footer.email', '');
$footerFacebook = theme_get('footer.facebook', '');
$footerInstagram = theme_get('footer.instagram', '');
$footerLinkedin = theme_get('footer.linkedin', '');
$footerYoutube = theme_get('footer.youtube', '');
?>
<footer class="vp-footer">
    <div class="vp-footer-newsletter">
        <div class="vp-container">
            <div class="vp-newsletter-wrap">
                <div class="vp-newsletter-content">
                    <h3 data-ts="footer.newsletter_title"><?= esc(theme_get('footer.newsletter_title', 'Stay Updated')) ?></h3>
                    <p data-ts="footer.newsletter_desc"><?= esc(theme_get('footer.newsletter_desc', 'Get WordPress tips, hosting insights, and product updates delivered to your inbox.')) ?></p>
                </div>
                <form class="vp-newsletter-form">
                    <input type="email" placeholder="Enter your email" class="vp-newsletter-input" required>
                    <button type="submit" class="vp-newsletter-btn">
                        <span>Subscribe</span>
                        <i class="fas fa-arrow-right"></i>
                    </button>
                </form>
            </div>
        </div>
    </div>
    
    <div class="vp-footer-main">
        <div class="vp-container">
            <div class="vp-footer-grid">
                <div class="vp-footer-col vp-footer-brand">
                    <a href="/" class="vp-footer-logo">
                        <?php if ($tsLogo): ?>
                            <img src="<?= esc($tsLogo) ?>" alt="<?= esc(theme_get('brand.site_name', $siteName)) ?>" height="36">
                        <?php else: ?>
                            <span class="vp-footer-logo-text" data-ts="brand.site_name"><?= esc(theme_get('brand.site_name', $siteName)) ?></span>
                        <?php endif; ?>
                    </a>
                    <p class="vp-footer-desc" data-ts="footer.description"><?= esc($footerDesc) ?></p>
                    
                    <?php if ($footerFacebook || $footerInstagram || $footerLinkedin || $footerYoutube): ?>
                    <div class="vp-footer-social">
                        <?php if ($footerFacebook): ?>
                        <a href="<?= esc($footerFacebook) ?>" target="_blank" rel="noopener" aria-label="Facebook">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                        <?php endif; ?>
                        <?php if ($footerInstagram): ?>
                        <a href="<?= esc($footerInstagram) ?>" target="_blank" rel="noopener" aria-label="Instagram">
                            <i class="fab fa-instagram"></i>
                        </a>
                        <?php endif; ?>
                        <?php if ($footerLinkedin): ?>
                        <a href="<?= esc($footerLinkedin) ?>" target="_blank" rel="noopener" aria-label="LinkedIn">
                            <i class="fab fa-linkedin-in"></i>
                        </a>
                        <?php endif; ?>
                        <?php if ($footerYoutube): ?>
                        <a href="<?= esc($footerYoutube) ?>" target="_blank" rel="noopener" aria-label="YouTube">
                            <i class="fab fa-youtube"></i>
                        </a>
                        <?php endif; ?>
                    </div>
                    <?php endif; ?>
                </div>
                
                <div class="vp-footer-col">
                    <h4 class="vp-footer-title">Quick Links</h4>
                    <?= render_menu('footer', ['class' => 'vp-footer-links', 'link_class' => 'vp-footer-link', 'wrap' => false]) ?>
                </div>
                
                <div class="vp-footer-col">
                    <h4 class="vp-footer-title">Hosting Solutions</h4>
                    <ul class="vp-footer-links">
                        <li><a href="#" class="vp-footer-link">Managed WordPress</a></li>
                        <li><a href="#" class="vp-footer-link">WooCommerce Hosting</a></li>
                        <li><a href="#" class="vp-footer-link">Enterprise Plans</a></li>
                        <li><a href="#" class="vp-footer-link">Migration Services</a></li>
                    </ul>
                </div>
                
                <div class="vp-footer-col">
                    <h4 class="vp-footer-title">Contact Us</h4>
                    <ul class="vp-footer-contact">
                        <?php if ($footerAddress): ?>
                        <li data-ts="footer.address">
                            <i class="fas fa-map-marker-alt"></i>
                            <span><?= esc($footerAddress) ?></span>
                        </li>
                        <?php endif; ?>
                        <?php if ($footerPhone): ?>
                        <li>
                            <i class="fas fa-phone"></i>
                            <a href="tel:<?= esc(preg_replace('/[^0-9+]/', '', $footerPhone)) ?>" data-ts="footer.phone"><?= esc($footerPhone) ?></a>
                        </li>
                        <?php endif; ?>
                        <?php if ($footerEmail): ?>
                        <li>
                            <i class="fas fa-envelope"></i>
                            <a href="mailto:<?= esc($footerEmail) ?>" data-ts="footer.email"><?= esc($footerEmail) ?></a>
                        </li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    
    <div class="vp-footer-bottom">
        <div class="vp-container">
            <div class="vp-footer-bottom-inner">
                <p class="vp-copyright" data-ts="footer.copyright">
                    <?= theme_get('footer.copyright') ? esc(theme_get('footer.copyright')) : '&copy; ' . date('Y') . ' ' . esc(theme_get('brand.site_name', $siteName)) . '. All rights reserved.' ?>
                </p>
                <div class="vp-footer-legal">
                    <a href="#">Privacy Policy</a>
                    <a href="#">Terms of Service</a>
                    <a href="#">SLA</a>
                </div>
            </div>
        </div>
    </div>
</footer>
<?php endif; ?>

<script src="<?= $themePath ?>/assets/js/main.js"></script>
<?php if (function_exists('cms_ab_testing_widget')): echo cms_ab_testing_widget(); endif; ?>
<?php if (function_exists('ai_theme_chat_widget')): echo ai_theme_chat_widget(); endif; ?>
</body>
</html>