<?php
/**
 * AI-Generated Theme Layout
 * Generated by AI Theme Builder
 */

if (!defined('CMS_ROOT')) define('CMS_ROOT', dirname(__DIR__, 2));
if (!defined('CMS_APP')) define('CMS_APP', CMS_ROOT . '/app');

require_once CMS_APP . '/helpers/functions.php';

if (file_exists(CMS_ROOT . '/includes/helpers/menu.php')) {
    require_once CMS_ROOT . '/includes/helpers/menu.php';
}

$jtbBootPath = CMS_ROOT . '/plugins/jessie-theme-builder/includes/jtb-frontend-boot.php';
if (file_exists($jtbBootPath)) require_once $jtbBootPath;

$themeConfig = get_theme_config();
$themeOptions = $themeConfig['options'] ?? [];
$showHeader = $themeOptions['show_header'] ?? true;
$showFooter = $themeOptions['show_footer'] ?? true;

$siteName = theme_get('brand.site_name', get_site_name());
$siteLogo = theme_get('brand.logo', get_site_logo());
$tsLogo = theme_get('brand.logo') ?: $siteLogo;

$pageData = $page ?? [];
if (!empty($title) && empty($pageData['title'])) $pageData['title'] = $title;
$isTbPage = !empty($page['is_tb_page']);

$themeCssVariables = generate_theme_css_variables($themeConfig);
$themePath = '/themes/' . basename(__DIR__);
?><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?= render_seo_meta($pageData) ?>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&amp;family=IBM+Plex+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/assets/css/fontawesome.min.css">
    <link rel="stylesheet" href="/assets/css/tb-frontend.css">
    <link rel="stylesheet" href="<?= $themePath ?>/assets/css/style.css?v=<?= filemtime(__DIR__ . "/assets/css/style.css") ?>">
    <style>
<?= $themeCssVariables ?>
<?= generate_studio_css_overrides() ?>
    </style>
<?= function_exists("theme_render_favicon") ? theme_render_favicon() : "" ?>
<?= function_exists("theme_render_og_image") ? theme_render_og_image() : "" ?>
</head>
<body class="<?= esc(get_body_class() ?? '') ?><?= $isTbPage ? ' tb-page' : '' ?>">
<?= function_exists("theme_render_announcement_bar") ? theme_render_announcement_bar() : "" ?>

<?php if ($showHeader): ?>
<a href="#main-content" class="skip-nav">Skip to content</a>
<header id="siteHeader" class="agr-header">
  <div class="agr-header-inner">
    <a href="/" class="agr-brand">
      <?php if ($logo = theme_get('brand.logo')): ?>
        <img src="<?= esc($logo) ?>" alt="<?= esc($siteName) ?>" class="agr-brand-img">
      <?php else: ?>
        <span class="agr-brand-text" data-ts="brand.site_name"><?= esc(theme_get('brand.site_name', $siteName)) ?></span>
      <?php endif; ?>
    </a>
    <nav id="headerNav" class="agr-nav">
      <?php echo render_menu('header', ['class' => 'agr-nav-list', 'link_class' => 'agr-nav-link', 'wrap' => false]); ?>
    </nav>
    <?php if (theme_get('header.show_cta', true)): ?>
    <a href="<?= esc(theme_get('header.cta_link', '/contact')) ?>" class="agr-cta" data-ts="header.cta_text" data-ts-href="header.cta_link"><?= esc(theme_get('header.cta_text', 'Get Started')) ?></a>
    <?php endif; ?>
    <button class="dark-mode-toggle" data-dark-toggle aria-label="Toggle dark mode" style="background:none;border:none;cursor:pointer;font-size:1.25rem;padding:4px 8px">🌙</button>
    <button id="mobileToggle" class="agr-burger" aria-label="Menu">
      <span></span><span></span><span></span>
    </button>
  </div>
</header>
<div class="mobile-overlay" id="mobileOverlay"></div>
<?php endif; ?>

<?php if ($isTbPage): ?>
    <?= $content ?? '' ?>
<?php else: ?>
    <main id="main-content"><?= $content ?? '' ?></main>
<?php endif; ?>

<?php if ($showFooter): ?>
<footer class="agr-footer agr-footer--magazine">
  <div class="agr-footer-top">
    <div class="agr-footer-inner">
      <div class="agr-footer-brand-row">
        <div class="agr-footer-brand">
      <?php if ($logo = theme_get('brand.logo')): ?>
        <img src="<?= esc($logo) ?>" alt="<?= esc($siteName) ?>" class="agr-footer-logo" data-ts="brand.logo">
      <?php else: ?>
        <span class="agr-footer-brand-text" data-ts="brand.site_name"><?= esc(theme_get('brand.site_name', $siteName)) ?></span>
      <?php endif; ?>
        </div>
    <div class="agr-footer-social">
      <?php if ($fb = theme_get('footer.facebook')): ?><a href="<?= esc($fb) ?>" target="_blank" class="agr-social-link" aria-label="Facebook"><i class="fab fa-facebook-f"></i></a><?php endif; ?>
      <?php if ($ig = theme_get('footer.instagram')): ?><a href="<?= esc($ig) ?>" target="_blank" class="agr-social-link" aria-label="Instagram"><i class="fab fa-instagram"></i></a><?php endif; ?>
      <?php if ($tw = theme_get('footer.twitter')): ?><a href="<?= esc($tw) ?>" target="_blank" class="agr-social-link" aria-label="Twitter"><i class="fab fa-twitter"></i></a><?php endif; ?>
      <?php if ($li = theme_get('footer.linkedin')): ?><a href="<?= esc($li) ?>" target="_blank" class="agr-social-link" aria-label="LinkedIn"><i class="fab fa-linkedin-in"></i></a><?php endif; ?>
    </div>
      </div>
    </div>
  </div>
  <div class="agr-footer-main">
    <div class="agr-footer-inner">
      <div class="agr-footer-content">
      <p class="agr-footer-desc" data-ts="footer.description"><?= esc(theme_get('footer.description', '')) ?></p>
      </div>
      <div class="agr-footer-nav-area">
    <?= render_menu('footer', ['class' => 'agr-footer-links', 'link_class' => 'agr-footer-link', 'wrap' => false]) ?>
      </div>
      <div class="agr-footer-contact-area">
      <?php if (theme_get('footer.phone')): ?><p class="agr-footer-phone"><i class="fas fa-phone"></i> <a href="tel:<?= esc(theme_get('footer.phone')) ?>" data-ts="footer.phone"><?= esc(theme_get('footer.phone')) ?></a></p><?php endif; ?>
      <?php if (theme_get('footer.email')): ?><p class="agr-footer-email"><i class="fas fa-envelope"></i> <a href="mailto:<?= esc(theme_get('footer.email')) ?>" data-ts="footer.email"><?= esc(theme_get('footer.email')) ?></a></p><?php endif; ?>
      <?php if (theme_get('footer.address')): ?><p class="agr-footer-address" data-ts="footer.address"><i class="fas fa-map-marker-alt"></i> <?= esc(theme_get('footer.address')) ?></p><?php endif; ?>
      </div>
    </div>
  </div>
  <div class="agr-footer-bottom">
    <div class="agr-footer-inner">
    <p class="agr-footer-copyright">&copy; <?= date('Y') ?> <?= esc(theme_get('brand.site_name', $siteName)) ?>. All rights reserved.</p>
    </div>
  </div>
</footer>
<?php endif; ?>

<script src="<?= $themePath ?>/assets/js/main.js"></script>
<?php if (function_exists('cms_ab_testing_widget')): echo cms_ab_testing_widget(); endif; ?>
<?php if (function_exists('ai_theme_chat_widget')): echo ai_theme_chat_widget(); endif; ?>
</body>
</html>