<?php
/**
 * AI-Generated Theme Layout
 * Generated by AI Theme Builder
 */

if (!defined('CMS_ROOT')) define('CMS_ROOT', dirname(__DIR__, 2));
if (!defined('CMS_APP')) define('CMS_APP', CMS_ROOT . '/app');

require_once CMS_APP . '/helpers/functions.php';

if (file_exists(CMS_ROOT . '/includes/helpers/menu.php')) {
    require_once CMS_ROOT . '/includes/helpers/menu.php';
}

$jtbBootPath = CMS_ROOT . '/plugins/jessie-theme-builder/includes/jtb-frontend-boot.php';
if (file_exists($jtbBootPath)) require_once $jtbBootPath;

$themeConfig = get_theme_config();
$themeOptions = $themeConfig['options'] ?? [];
$showHeader = $themeOptions['show_header'] ?? true;
$showFooter = $themeOptions['show_footer'] ?? true;

$siteName = theme_get('brand.site_name', get_site_name());
$siteLogo = theme_get('brand.logo', get_site_logo());
$tsLogo = theme_get('brand.logo') ?: $siteLogo;

$pageData = $page ?? [];
if (!empty($title) && empty($pageData['title'])) $pageData['title'] = $title;
$isTbPage = !empty($page['is_tb_page']);

$themeCssVariables = generate_theme_css_variables($themeConfig);
$themePath = '/themes/' . basename(__DIR__);
?><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?= render_seo_meta($pageData) ?>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Bitter:wght@400;700&amp;family=Rubik:wght@400;600&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/assets/css/fontawesome.min.css">
    <link rel="stylesheet" href="/assets/css/tb-frontend.css">
    <link rel="stylesheet" href="<?= $themePath ?>/assets/css/style.css">
    <style>
<?= $themeCssVariables ?>
<?= generate_studio_css_overrides() ?>
    </style>
<?= function_exists("theme_render_favicon") ? theme_render_favicon() : "" ?>
<?= function_exists("theme_render_og_image") ? theme_render_og_image() : "" ?>
</head>
<body class="<?= esc(get_body_class() ?? '') ?><?= $isTbPage ? ' tb-page' : '' ?>">
<?= function_exists("theme_render_announcement_bar") ? theme_render_announcement_bar() : "" ?>

<?php if ($showHeader): ?>
<a href="#main-content" class="skip-nav">Skip to content</a>
<header id="siteHeader" class="tl-header">
  <div class="tl-header-inner">
    <a href="/" class="tl-brand">
      <?php if ($logo = theme_get('brand.logo')): ?>
        <img src="<?= esc($logo) ?>" alt="<?= esc($siteName) ?>" class="tl-brand-img">
      <?php else: ?>
        <span class="tl-brand-text" data-ts="brand.site_name"><?= esc(theme_get('brand.site_name', $siteName)) ?></span>
      <?php endif; ?>
    </a>
    <nav id="headerNav" class="tl-nav">
      <?php echo render_menu('header', ['class' => 'tl-nav-list', 'link_class' => 'tl-nav-link', 'wrap' => false]); ?>
    </nav>
    <div class="tl-header-actions">
    <button class="tl-search-toggle" aria-label="Search"><i class="fas fa-search"></i></button>
    <a href="<?= esc(theme_get('header.cta_link', '/contact')) ?>" class="tl-cta" data-ts="header.cta_text" data-ts-href="header.cta_link"><?= esc(theme_get('header.cta_text', 'Get Started')) ?></a>
    <button class="dark-mode-toggle" data-dark-toggle aria-label="Toggle dark mode" style="background:none;border:none;cursor:pointer;font-size:1.25rem;padding:4px 8px">🌙</button>
    <button id="mobileToggle" class="tl-burger" aria-label="Menu">
      <span></span><span></span><span></span>
    </button>
    </div>
  </div>
</header>
<div class="mobile-overlay" id="mobileOverlay"></div>
<?php endif; ?>

<?php if ($isTbPage): ?>
    <?= $content ?? '' ?>
<?php else: ?>
    <main id="main-content"><?= $content ?? '' ?></main>
<?php endif; ?>

<?php if ($showFooter): ?>
<footer class="tf-footer">
    <div class="tf-footer-top">
        <div class="tf-container">
            <div class="tf-footer-main">
                <div class="tf-footer-brand">
                    <a href="/" class="tf-footer-logo">
                        <?php if ($tsLogo): ?>
                            <img src="<?= esc($tsLogo) ?>" alt="<?= esc(theme_get('brand.site_name', $siteName)) ?>" height="48" class="tf-brand-img">
                        <?php else: ?>
                            <span class="tf-brand-text" data-ts="brand.site_name"><?= esc(theme_get('brand.site_name', $siteName)) ?></span>
                        <?php endif; ?>
                    </a>
                    <p class="tf-footer-tagline" data-ts="footer.description">
                        <?= esc(theme_get('footer.description', 'Transforming outdoor spaces with expert craftsmanship in patios, driveways, retaining walls, fencing, and artificial grass.')) ?>
                    </p>
                    <div class="tf-footer-social">
                        <?php if (theme_get('footer.facebook')): ?>
                            <a href="<?= esc(theme_get('footer.facebook')) ?>" target="_blank" aria-label="Facebook" class="tf-social-link">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                        <?php endif; ?>
                        <?php if (theme_get('footer.instagram')): ?>
                            <a href="<?= esc(theme_get('footer.instagram')) ?>" target="_blank" aria-label="Instagram" class="tf-social-link">
                                <i class="fab fa-instagram"></i>
                            </a>
                        <?php endif; ?>
                        <?php if (theme_get('footer.linkedin')): ?>
                            <a href="<?= esc(theme_get('footer.linkedin')) ?>" target="_blank" aria-label="LinkedIn" class="tf-social-link">
                                <i class="fab fa-linkedin-in"></i>
                            </a>
                        <?php endif; ?>
                        <?php if (theme_get('footer.youtube')): ?>
                            <a href="<?= esc(theme_get('footer.youtube')) ?>" target="_blank" aria-label="YouTube" class="tf-social-link">
                                <i class="fab fa-youtube"></i>
                            </a>
                        <?php endif; ?>
                    </div>
                </div>

                <div class="tf-footer-newsletter">
                    <h4 class="tf-footer-title" data-ts="footer.newsletter_title">Stay Updated</h4>
                    <p class="tf-footer-newsletter-desc" data-ts="footer.newsletter_desc">Get landscaping tips and seasonal offers.</p>
                    <form class="tf-newsletter-form">
                        <input type="email" placeholder="Your email address" class="tf-newsletter-input" required>
                        <button type="submit" class="tf-newsletter-btn">
                            <i class="fas fa-paper-plane"></i>
                        </button>
                    </form>
                </div>

                <div class="tf-footer-contact">
                    <h4 class="tf-footer-title" data-ts="footer.contact_title">Contact Us</h4>
                    <div class="tf-contact-info">
                        <?php if (theme_get('footer.phone')): ?>
                            <a href="tel:<?= esc(preg_replace('/[^0-9+]/', '', theme_get('footer.phone'))) ?>" class="tf-contact-item" data-ts="footer.phone">
                                <i class="fas fa-phone-alt tf-contact-icon"></i>
                                <span><?= esc(theme_get('footer.phone')) ?></span>
                            </a>
                        <?php endif; ?>
                        <?php if (theme_get('footer.email')): ?>
                            <a href="mailto:<?= esc(theme_get('footer.email')) ?>" class="tf-contact-item" data-ts="footer.email">
                                <i class="fas fa-envelope tf-contact-icon"></i>
                                <span><?= esc(theme_get('footer.email')) ?></span>
                            </a>
                        <?php endif; ?>
                        <?php if (theme_get('footer.address')): ?>
                            <div class="tf-contact-item" data-ts="footer.address">
                                <i class="fas fa-map-marker-alt tf-contact-icon"></i>
                                <span><?= esc(theme_get('footer.address')) ?></span>
                            </div>
                        <?php endif; ?>
                        <?php if (theme_get('footer.hours')): ?>
                            <div class="tf-contact-item" data-ts="footer.hours">
                                <i class="fas fa-clock tf-contact-icon"></i>
                                <span><?= esc(theme_get('footer.hours')) ?></span>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="tf-footer-bottom">
        <div class="tf-container">
            <div class="tf-footer-bottom-inner">
                <nav class="tf-footer-nav">
                    <?= render_menu('footer', ['class' => 'tf-footer-links', 'link_class' => 'tf-footer-link', 'wrap' => false]) ?>
                </nav>
                <p class="tf-copyright" data-ts="footer.copyright">
                    <?= theme_get('footer.copyright') ? esc(theme_get('footer.copyright')) : '&copy; ' . date('Y') . ' ' . esc(theme_get('brand.site_name', $siteName)) . '. All rights reserved.' ?>
                </p>
            </div>
        </div>
    </div>
</footer>
<?php endif; ?>

<script src="<?= $themePath ?>/assets/js/main.js"></script>
<?php if (function_exists('cms_ab_testing_widget')): echo cms_ab_testing_widget(); endif; ?>
<?php if (function_exists('ai_theme_chat_widget')): echo ai_theme_chat_widget(); endif; ?>
</body>
</html>