<?php
/**
 * AI-Generated Theme Layout
 * Generated by AI Theme Builder
 */

if (!defined('CMS_ROOT')) define('CMS_ROOT', dirname(__DIR__, 2));
if (!defined('CMS_APP')) define('CMS_APP', CMS_ROOT . '/app');

require_once CMS_APP . '/helpers/functions.php';

if (file_exists(CMS_ROOT . '/includes/helpers/menu.php')) {
    require_once CMS_ROOT . '/includes/helpers/menu.php';
}

$jtbBootPath = CMS_ROOT . '/plugins/jessie-theme-builder/includes/jtb-frontend-boot.php';
if (file_exists($jtbBootPath)) require_once $jtbBootPath;

$themeConfig = get_theme_config();
$themeOptions = $themeConfig['options'] ?? [];
$showHeader = $themeOptions['show_header'] ?? true;
$showFooter = $themeOptions['show_footer'] ?? true;

$siteName = theme_get('brand.site_name', get_site_name());
$siteLogo = theme_get('brand.logo', get_site_logo());
$tsLogo = theme_get('brand.logo') ?: $siteLogo;

$pageData = $page ?? [];
if (!empty($title) && empty($pageData['title'])) $pageData['title'] = $title;
$isTbPage = !empty($page['is_tb_page']);

$themeCssVariables = generate_theme_css_variables($themeConfig);
$themePath = '/themes/' . basename(__DIR__);
?><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?= render_seo_meta($pageData) ?>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;600;700;800&amp;family=PT+Serif:wght@400;700&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/assets/css/fontawesome.min.css">
    <link rel="stylesheet" href="/assets/css/tb-frontend.css">
    <link rel="stylesheet" href="<?= $themePath ?>/assets/css/style.css">
    <style>
<?= $themeCssVariables ?>
<?= generate_studio_css_overrides() ?>
    </style>
<?= function_exists("theme_render_favicon") ? theme_render_favicon() : "" ?>
<?= function_exists("theme_render_og_image") ? theme_render_og_image() : "" ?>
</head>
<body class="<?= esc(get_body_class() ?? '') ?><?= $isTbPage ? ' tb-page' : '' ?>">
<?= function_exists("theme_render_announcement_bar") ? theme_render_announcement_bar() : "" ?>

<?php if ($showHeader): ?>
<?php
$headerPhone = theme_get('header.phone', '(555) 911-ROOF');
$headerEmail = theme_get('header.email', 'emergency@stormshieldpro.com');
$ctaText = theme_get('header.cta_text', 'Emergency Callout');
$ctaLink = theme_get('header.cta_link', '#contact');
?>
<div class="ssp-topbar">
    <div class="ssp-topbar-inner">
        <div class="ssp-topbar-left">
            <?php if ($headerPhone): ?>
            <a href="tel:<?= esc(preg_replace('/[^0-9+]/', '', $headerPhone)) ?>" class="ssp-topbar-link" data-ts="header.phone">
                <i class="fas fa-phone-alt"></i>
                <span><?= esc($headerPhone) ?></span>
            </a>
            <?php endif; ?>
            <?php if ($headerEmail): ?>
            <a href="mailto:<?= esc($headerEmail) ?>" class="ssp-topbar-link" data-ts="header.email">
                <i class="fas fa-envelope"></i>
                <span><?= esc($headerEmail) ?></span>
            </a>
            <?php endif; ?>
        </div>
        <div class="ssp-topbar-right">
            <?php if (theme_get('footer.facebook')): ?>
            <a href="<?= esc(theme_get('footer.facebook')) ?>" class="ssp-topbar-social" aria-label="Facebook"><i class="fab fa-facebook-f"></i></a>
            <?php endif; ?>
            <?php if (theme_get('footer.instagram')): ?>
            <a href="<?= esc(theme_get('footer.instagram')) ?>" class="ssp-topbar-social" aria-label="Instagram"><i class="fab fa-instagram"></i></a>
            <?php endif; ?>
            <?php if (theme_get('footer.linkedin')): ?>
            <a href="<?= esc(theme_get('footer.linkedin')) ?>" class="ssp-topbar-social" aria-label="LinkedIn"><i class="fab fa-linkedin-in"></i></a>
            <?php endif; ?>
            <?php if (theme_get('footer.youtube')): ?>
            <a href="<?= esc(theme_get('footer.youtube')) ?>" class="ssp-topbar-social" aria-label="YouTube"><i class="fab fa-youtube"></i></a>
            <?php endif; ?>
        </div>
    </div>
</div>
<a href="#main-content" class="skip-nav">Skip to content</a>
<header class="ssp-header" id="siteHeader">
    <div class="ssp-header-inner">
        <a href="/" class="ssp-brand" data-ts="brand.logo">
            <?php if ($tsLogo): ?>
                <img src="<?= esc($tsLogo) ?>" alt="<?= esc(theme_get('brand.site_name', $siteName)) ?>" class="ssp-brand-logo">
            <?php else: ?>
                <span class="ssp-brand-icon"><i class="fas fa-shield-alt"></i></span>
                <span class="ssp-brand-text" data-ts="brand.site_name"><?= esc(theme_get('brand.site_name', $siteName)) ?></span>
            <?php endif; ?>
        </a>
        
        <nav class="ssp-nav-left" id="headerNav">
            <?= render_menu('header', ['class' => 'ssp-nav-links ssp-nav-links--left', 'link_class' => 'ssp-nav-link', 'wrap' => false]) ?>
        </nav>
        
        <div class="ssp-nav-right">
            <button class="ssp-search-toggle" aria-label="Search">
                <i class="fas fa-search"></i>
            </button>
            <a href="<?= esc($ctaLink) ?>" class="ssp-header-cta" data-ts="header.cta_text" data-ts-href="header.cta_link">
                <i class="fas fa-bolt"></i>
                <?= esc($ctaText) ?>
            </a>
        </div>
        
        <button class="ssp-hamburger" id="mobileToggle" aria-label="Menu">
            <span></span>
            <span></span>
            <span></span>
        </button>
    </div>
</header>
<div class="mobile-overlay" id="mobileOverlay"></div>
<?php endif; ?>

<?php if ($isTbPage): ?>
    <?= $content ?? '' ?>
<?php else: ?>
    <main id="main-content"><?= $content ?? '' ?></main>
<?php endif; ?>

<?php if ($showFooter): ?>
<?php
$footerDesc = theme_get('footer.description', 'Your trusted partner for emergency roof repairs. We respond fast when storms strike, protecting your home and family around the clock.');
$footerAddress = theme_get('footer.address', '123 Rooftop Lane, Storm City, SC 29000');
$footerPhone = theme_get('footer.phone', '(555) 911-ROOF');
$footerEmail = theme_get('footer.email', 'emergency@stormshieldpro.com');
$footerHours = theme_get('footer.hours', '24/7 Emergency Service Available');
$footerCopyright = theme_get('footer.copyright', '');
?>
<footer class="ssp-footer">
    <div class="ssp-footer-newsletter">
        <div class="ssp-footer-newsletter-inner">
            <div class="ssp-newsletter-content">
                <h3 class="ssp-newsletter-title" data-ts="footer.newsletter_title"><?= esc(theme_get('footer.newsletter_title', 'Stay Storm-Ready')) ?></h3>
                <p class="ssp-newsletter-desc" data-ts="footer.newsletter_desc"><?= esc(theme_get('footer.newsletter_desc', 'Get seasonal roof maintenance tips and early storm alerts delivered to your inbox.')) ?></p>
            </div>
            <form class="ssp-newsletter-form">
                <input type="email" placeholder="Enter your email" class="ssp-newsletter-input" required>
                <button type="submit" class="ssp-newsletter-btn">
                    <span>Subscribe</span>
                    <i class="fas fa-paper-plane"></i>
                </button>
            </form>
        </div>
    </div>
    
    <div class="ssp-footer-main">
        <div class="ssp-footer-grid">
            <div class="ssp-footer-brand-col">
                <a href="/" class="ssp-footer-brand" data-ts="brand.logo">
                    <?php if ($tsLogo): ?>
                        <img src="<?= esc($tsLogo) ?>" alt="<?= esc(theme_get('brand.site_name', $siteName)) ?>" height="48">
                    <?php else: ?>
                        <span class="ssp-footer-brand-icon"><i class="fas fa-shield-alt"></i></span>
                        <span class="ssp-footer-brand-name" data-ts="brand.site_name"><?= esc(theme_get('brand.site_name', $siteName)) ?></span>
                    <?php endif; ?>
                </a>
                <p class="ssp-footer-tagline" data-ts="footer.description"><?= esc($footerDesc) ?></p>
                <div class="ssp-footer-socials">
                    <?php if (theme_get('footer.facebook')): ?>
                    <a href="<?= esc(theme_get('footer.facebook')) ?>" class="ssp-footer-social" aria-label="Facebook"><i class="fab fa-facebook-f"></i></a>
                    <?php endif; ?>
                    <?php if (theme_get('footer.instagram')): ?>
                    <a href="<?= esc(theme_get('footer.instagram')) ?>" class="ssp-footer-social" aria-label="Instagram"><i class="fab fa-instagram"></i></a>
                    <?php endif; ?>
                    <?php if (theme_get('footer.linkedin')): ?>
                    <a href="<?= esc(theme_get('footer.linkedin')) ?>" class="ssp-footer-social" aria-label="LinkedIn"><i class="fab fa-linkedin-in"></i></a>
                    <?php endif; ?>
                    <?php if (theme_get('footer.youtube')): ?>
                    <a href="<?= esc(theme_get('footer.youtube')) ?>" class="ssp-footer-social" aria-label="YouTube"><i class="fab fa-youtube"></i></a>
                    <?php endif; ?>
                </div>
            </div>
            
            <div class="ssp-footer-links-col">
                <h4 class="ssp-footer-heading">Quick Links</h4>
                <?= render_menu('footer', ['class' => 'ssp-footer-nav', 'link_class' => 'ssp-footer-link', 'wrap' => false]) ?>
            </div>
            
            <div class="ssp-footer-services-col">
                <h4 class="ssp-footer-heading" data-ts="footer.services_title"><?= esc(theme_get('footer.services_title', 'Our Services')) ?></h4>
                <ul class="ssp-footer-services-list">
                    <li><a href="/services#storm-damage" class="ssp-footer-link">Storm Damage Repair</a></li>
                    <li><a href="/services#leak-detection" class="ssp-footer-link">Leak Detection</a></li>
                    <li><a href="/services#missing-tiles" class="ssp-footer-link">Missing Tile Replacement</a></li>
                    <li><a href="/services#weatherproofing" class="ssp-footer-link">Emergency Weatherproofing</a></li>
                    <li><a href="/services#inspection" class="ssp-footer-link">Roof Inspections</a></li>
                </ul>
            </div>
            
            <div class="ssp-footer-contact-col">
                <h4 class="ssp-footer-heading" data-ts="footer.contact_title"><?= esc(theme_get('footer.contact_title', 'Emergency Contact')) ?></h4>
                <ul class="ssp-footer-contact-list">
                    <?php if ($footerPhone): ?>
                    <li>
                        <i class="fas fa-phone-alt"></i>
                        <a href="tel:<?= esc(preg_replace('/[^0-9+]/', '', $footerPhone)) ?>" data-ts="footer.phone"><?= esc($footerPhone) ?></a>
                    </li>
                    <?php endif; ?>
                    <?php if ($footerEmail): ?>
                    <li>
                        <i class="fas fa-envelope"></i>
                        <a href="mailto:<?= esc($footerEmail) ?>" data-ts="footer.email"><?= esc($footerEmail) ?></a>
                    </li>
                    <?php endif; ?>
                    <?php if ($footerAddress): ?>
                    <li>
                        <i class="fas fa-map-marker-alt"></i>
                        <span data-ts="footer.address"><?= esc($footerAddress) ?></span>
                    </li>
                    <?php endif; ?>
                    <?php if ($footerHours): ?>
                    <li>
                        <i class="fas fa-clock"></i>
                        <span data-ts="footer.hours"><?= esc($footerHours) ?></span>
                    </li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </div>
    
    <div class="ssp-footer-bottom">
        <div class="ssp-footer-bottom-inner">
            <p class="ssp-copyright" data-ts="footer.copyright">
                <?= $footerCopyright ? esc($footerCopyright) : '&copy; ' . date('Y') . ' ' . esc(theme_get('brand.site_name', $siteName)) . '. All rights reserved.' ?>
            </p>
            <div class="ssp-footer-badges">
                <span class="ssp-badge"><i class="fas fa-shield-alt"></i> Licensed & Insured</span>
                <span class="ssp-badge"><i class="fas fa-bolt"></i> 24/7 Emergency</span>
            </div>
        </div>
    </div>
</footer>
<?php endif; ?>

<script src="<?= $themePath ?>/assets/js/main.js"></script>
<?php if (function_exists('cms_ab_testing_widget')): echo cms_ab_testing_widget(); endif; ?>
<?php if (function_exists('ai_theme_chat_widget')): echo ai_theme_chat_widget(); endif; ?>
</body>
</html>