<?php /** Analytics Admin — Users */ ?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Analytics — Users</title>
<style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#0f172a;color:#e2e8f0;line-height:1.6}.wrap{max-width:1200px;margin:0 auto;padding:2rem}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:2rem}h1{font-size:1.5rem;background:linear-gradient(135deg,#8b5cf6,#06b6d4);-webkit-background-clip:text;-webkit-text-fill-color:transparent}.nav a{color:#94a3b8;text-decoration:none;margin-left:1rem;font-size:.875rem}.nav a:hover{color:#e2e8f0}.nav a.active{color:#8b5cf6}table{width:100%;border-collapse:collapse;background:#1e293b;border:1px solid #334155;border-radius:.75rem;overflow:hidden}th{background:#334155;text-align:left;padding:.75rem 1rem;font-size:.75rem;text-transform:uppercase;color:#94a3b8}td{padding:.75rem 1rem;border-top:1px solid #334155;font-size:.875rem}.back{display:inline-block;margin-bottom:1rem;color:#8b5cf6;text-decoration:none;font-size:.875rem}</style>
</head><body><div class="wrap"><a href="/admin" class="back">← Admin</a>
<div class="top"><h1>📊 Analytics — Users</h1><div class="nav"><a href="/admin/analytics">Dashboard</a><a href="/admin/analytics/users" class="active">Users</a></div></div>
<table><thead><tr><th>ID</th><th>Email</th><th>Name</th><th>Events</th><th>Goals</th><th>Credits</th><th>Joined</th></tr></thead><tbody>
<?php foreach ($users as $u): ?><tr><td><?= $u['id'] ?></td><td><?= htmlspecialchars($u['email']) ?></td><td><?= htmlspecialchars($u['name'] ?? '') ?></td><td><?= $u['event_count'] ?></td><td><?= $u['goal_count'] ?></td><td><?= $u['credits_remaining'] ?? 0 ?></td><td><?= substr($u['created_at'],0,10) ?></td></tr><?php endforeach; ?>
<?php if (empty($users)): ?><tr><td colspan="7" style="text-align:center;color:#64748b">No users yet</td></tr><?php endif; ?>
</tbody></table></div></body></html>
