<?php
/**
 * AI-Generated Theme Layout
 * Generated by AI Theme Builder
 */

if (!defined('CMS_ROOT')) define('CMS_ROOT', dirname(__DIR__, 2));
if (!defined('CMS_APP')) define('CMS_APP', CMS_ROOT . '/app');

require_once CMS_APP . '/helpers/functions.php';

if (file_exists(CMS_ROOT . '/includes/helpers/menu.php')) {
    require_once CMS_ROOT . '/includes/helpers/menu.php';
}

$jtbBootPath = CMS_ROOT . '/plugins/jessie-theme-builder/includes/jtb-frontend-boot.php';
if (file_exists($jtbBootPath)) require_once $jtbBootPath;

$themeConfig = get_theme_config();
$themeOptions = $themeConfig['options'] ?? [];
$showHeader = $themeOptions['show_header'] ?? true;
$showFooter = $themeOptions['show_footer'] ?? true;

$siteName = theme_get('brand.site_name', get_site_name());
$siteLogo = theme_get('brand.logo', get_site_logo());
$tsLogo = theme_get('brand.logo') ?: $siteLogo;

$pageData = $page ?? [];
if (!empty($title) && empty($pageData['title'])) $pageData['title'] = $title;
$isTbPage = !empty($page['is_tb_page']);

$themeCssVariables = generate_theme_css_variables($themeConfig);
$themePath = '/themes/' . basename(__DIR__);
?><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?= render_seo_meta($pageData) ?>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;500;600;700&amp;family=Red+Hat+Display:wght@300;400;500;600;700&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/assets/css/fontawesome.min.css">
    <link rel="stylesheet" href="/assets/css/tb-frontend.css">
    <link rel="stylesheet" href="<?= $themePath ?>/assets/css/style.css">
    <style>
<?= $themeCssVariables ?>
<?= generate_studio_css_overrides() ?>
    </style>
<?= function_exists("theme_render_favicon") ? theme_render_favicon() : "" ?>
<?= function_exists("theme_render_og_image") ? theme_render_og_image() : "" ?>
</head>
<body class="<?= esc(get_body_class() ?? '') ?><?= $isTbPage ? ' tb-page' : '' ?>">
<?= function_exists("theme_render_announcement_bar") ? theme_render_announcement_bar() : "" ?>

<?php if ($showHeader): ?>
<?php
$headerPhone = theme_get('header.phone', '');
$headerEmail = theme_get('header.email', '');
$ctaText = theme_get('header.cta_text', 'Request Assessment');
$ctaLink = theme_get('header.cta_link', '#contact');
?>
<a href="#main-content" class="skip-nav">Skip to content</a>
<header id="siteHeader" class="csh-masthead">
    <div class="csh-masthead-inner">
        <div class="csh-brand-tower">
            <a href="/" class="csh-logo-link" data-ts="brand.logo">
                <?php if ($tsLogo): ?>
                    <img src="<?= esc($tsLogo) ?>" alt="<?= esc(theme_get('brand.site_name', $siteName)) ?>" class="csh-logo-img">
                <?php else: ?>
                    <span class="csh-logo-text" data-ts="brand.site_name"><?= esc(theme_get('brand.site_name', $siteName)) ?></span>
                <?php endif; ?>
            </a>
        </div>
        <div class="csh-nav-strip">
            <div class="csh-nav-strip-inner">
                <?php if ($headerPhone): ?>
                <div class="csh-contact-info">
                    <a href="tel:<?= esc(preg_replace('/[^0-9+]/', '', $headerPhone)) ?>" class="csh-phone-link" data-ts="header.phone">
                        <i class="fas fa-phone-alt"></i>
                        <span><?= esc($headerPhone) ?></span>
                    </a>
                </div>
                <?php endif; ?>
                <nav id="headerNav" class="csh-navigation">
                    <?= render_menu('header', ['class' => 'csh-nav-list', 'link_class' => 'csh-nav-item', 'wrap' => false]) ?>
                </nav>
                <a href="<?= esc($ctaLink) ?>" class="csh-header-cta" data-ts="header.cta_text" data-ts-href="header.cta_link">
                    <i class="fas fa-shield-alt"></i>
                    <?= esc($ctaText) ?>
                </a>
                <button class="dark-mode-toggle" data-dark-toggle aria-label="Toggle dark mode" style="background:none;border:none;cursor:pointer;font-size:1.25rem;padding:4px 8px">🌙</button>
    <button id="mobileToggle" class="csh-hamburger" aria-label="Menu">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
            </div>
        </div>
    </div>
</header>
<div class="mobile-overlay" id="mobileOverlay"></div>
<?php endif; ?>

<?php if ($isTbPage): ?>
    <?= $content ?? '' ?>
<?php else: ?>
    <main id="main-content"><?= $content ?? '' ?></main>
<?php endif; ?>

<?php if ($showFooter): ?>
<?php
$footerDesc = theme_get('footer.description', 'Defending digital frontiers with enterprise-grade security solutions. Your trusted partner in cyber resilience.');
$footerCopyright = theme_get('footer.copyright', '');
$footerAddress = theme_get('footer.address', '');
$footerPhone = theme_get('footer.phone', '');
$footerEmail = theme_get('footer.email', '');
$footerFacebook = theme_get('footer.facebook', '');
$footerInstagram = theme_get('footer.instagram', '');
$footerLinkedin = theme_get('footer.linkedin', '');
$footerYoutube = theme_get('footer.youtube', '');
?>
<footer class="csh-site-footer">
    <div class="csh-footer-wave">
        <svg viewBox="0 0 1440 100" preserveAspectRatio="none">
            <path d="M0,50 C360,100 720,0 1080,50 C1260,75 1380,25 1440,50 L1440,100 L0,100 Z" fill="currentColor"/>
        </svg>
    </div>
    <div class="csh-footer-main">
        <div class="container">
            <div class="csh-footer-grid">
                <div class="csh-footer-brand-col">
                    <a href="/" class="csh-footer-logo" data-ts="brand.logo">
                        <?php if ($tsLogo): ?>
                            <img src="<?= esc($tsLogo) ?>" alt="<?= esc(theme_get('brand.site_name', $siteName)) ?>" height="36">
                        <?php else: ?>
                            <span class="csh-footer-logo-text" data-ts="brand.site_name"><?= esc(theme_get('brand.site_name', $siteName)) ?></span>
                        <?php endif; ?>
                    </a>
                    <p class="csh-footer-desc" data-ts="footer.description"><?= esc($footerDesc) ?></p>
                    <div class="csh-footer-social">
                        <?php if ($footerFacebook): ?>
                        <a href="<?= esc($footerFacebook) ?>" target="_blank" rel="noopener" aria-label="Facebook"><i class="fab fa-facebook-f"></i></a>
                        <?php endif; ?>
                        <?php if ($footerInstagram): ?>
                        <a href="<?= esc($footerInstagram) ?>" target="_blank" rel="noopener" aria-label="Instagram"><i class="fab fa-instagram"></i></a>
                        <?php endif; ?>
                        <?php if ($footerLinkedin): ?>
                        <a href="<?= esc($footerLinkedin) ?>" target="_blank" rel="noopener" aria-label="LinkedIn"><i class="fab fa-linkedin-in"></i></a>
                        <?php endif; ?>
                        <?php if ($footerYoutube): ?>
                        <a href="<?= esc($footerYoutube) ?>" target="_blank" rel="noopener" aria-label="YouTube"><i class="fab fa-youtube"></i></a>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="csh-footer-nav-col">
                    <h4 class="csh-footer-heading">Navigation</h4>
                    <?= render_menu('footer', ['class' => 'csh-footer-menu', 'link_class' => 'csh-footer-link', 'wrap' => false]) ?>
                </div>
                <div class="csh-footer-contact-col">
                    <h4 class="csh-footer-heading">Contact Us</h4>
                    <ul class="csh-footer-contact-list">
                        <?php if ($footerAddress): ?>
                        <li>
                            <i class="fas fa-map-marker-alt"></i>
                            <span data-ts="footer.address"><?= esc($footerAddress) ?></span>
                        </li>
                        <?php endif; ?>
                        <?php if ($footerPhone): ?>
                        <li>
                            <i class="fas fa-phone-alt"></i>
                            <a href="tel:<?= esc(preg_replace('/[^0-9+]/', '', $footerPhone)) ?>" data-ts="footer.phone"><?= esc($footerPhone) ?></a>
                        </li>
                        <?php endif; ?>
                        <?php if ($footerEmail): ?>
                        <li>
                            <i class="fas fa-envelope"></i>
                            <a href="mailto:<?= esc($footerEmail) ?>" data-ts="footer.email"><?= esc($footerEmail) ?></a>
                        </li>
                        <?php endif; ?>
                    </ul>
                </div>
                <div class="csh-footer-newsletter-col">
                    <h4 class="csh-footer-heading">Security Bulletin</h4>
                    <p class="csh-newsletter-text">Stay informed about the latest threats and security insights.</p>
                    <form class="csh-newsletter-form">
                        <div class="csh-newsletter-input-wrap">
                            <input type="email" placeholder="Enter your email" class="csh-newsletter-input" required>
                            <button type="button" class="csh-newsletter-btn">
                                <i class="fas fa-paper-plane"></i>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="csh-footer-bottom">
        <div class="container">
            <div class="csh-footer-bottom-inner">
                <p class="csh-copyright" data-ts="footer.copyright">
                    <?= $footerCopyright ? esc($footerCopyright) : '&copy; ' . date('Y') . ' ' . esc(theme_get('brand.site_name', $siteName)) . '. All rights reserved.' ?>
                </p>
                <div class="csh-footer-badges">
                    <span class="csh-badge"><i class="fas fa-lock"></i> SOC 2 Certified</span>
                    <span class="csh-badge"><i class="fas fa-shield-alt"></i> ISO 27001</span>
                </div>
            </div>
        </div>
    </div>
</footer>
<?php endif; ?>

<script src="<?= $themePath ?>/assets/js/main.js"></script>
<?php if (function_exists('cms_ab_testing_widget')): echo cms_ab_testing_widget(); endif; ?>
<?php if (function_exists('ai_theme_chat_widget')): echo ai_theme_chat_widget(); endif; ?>
</body>
</html>