<?php
/**
 * Header Template
 * Generated by AI Designer for Jessie AI CMS
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $page_title ?? 'Jessie AI CMS'; ?></title>
    
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Playfair+Display:wght@400;500;600;700&display=swap" rel="stylesheet">
    
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    
    <!-- Theme Stylesheet -->
    <link rel="stylesheet" href="<?php echo $theme_url ?? ''; ?>/assets/css/style.css">
</head>
<body>

<header style="position: sticky; top: 0; background-color: var(--color-background); box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1); z-index: 100;">
    <div class="container" style="display: flex; justify-content: space-between; align-items: center; padding: 1rem;">
        <div class="logo" style="font-family: 'Inter', sans-serif; font-size: 1.5rem; font-weight: bold; color: var(--color-text);">
            Jessie AI CMS
        </div>
        <nav class="nav-desktop" style="display: flex; gap: 1.5rem;">
            <a href="/" style="color: var(--color-text); text-decoration: none;">Homepage</a>
            <a href="/about" style="color: var(--color-text); text-decoration: none;">About</a>
            <a href="/services" style="color: var(--color-text); text-decoration: none;">Services</a>
            <a href="/contact" style="color: var(--color-text); text-decoration: none;">Contact</a>
            <a href="/blog" style="color: var(--color-text); text-decoration: none;">Blog</a>
            <a href="/portfolio" style="color: var(--color-text); text-decoration: none;">Portfolio</a>
            <a href="/pricing" style="color: var(--color-text); text-decoration: none;">Pricing</a>
            <a href="/team" style="color: var(--color-text); text-decoration: none;">Team</a>
            <a href="/faq" style="color: var(--color-text); text-decoration: none;">Faq</a>
            <a href="/testimonials" style="color: var(--color-text); text-decoration: none;">Testimonials</a>
        </nav>
        <button class="cta-button" style="background-color: var(--color-primary); color: white; border: none; padding: 0.5rem 1rem; border-radius: 5px; cursor: pointer;">
            Get Started
        </button>
        <button class="hamburger" aria-label="Toggle navigation" style="display: none; background: none; border: none; cursor: pointer;">
            <span style="display: block; width: 25px; height: 3px; background: var(--color-text); margin: 5px 0;"></span>
            <span style="display: block; width: 25px; height: 3px; background: var(--color-text); margin: 5px 0;"></span>
            <span style="display: block; width: 25px; height: 3px; background: var(--color-text); margin: 5px 0;"></span>
        </button>
    </div>
</header>