<?php
/**
 * AI Theme Builder — Boilerplate Templates
 * 
 * Fixed PHP templates ensuring correct CMS integration.
 * Uses theme_get(), data-ts, generate_studio_css_overrides(), etc.
 * 
 * Lessons from manual theme building applied:
 * - Professional CSS variable palette  
 * - Decorative ornamental elements
 * - Photo-forward overlay cards
 * - Premium typography hierarchy (section-label → divider → title → desc)
 * - data-animate scroll animations
 * - Mobile slide-out nav
 * - Gallery template support
 * - Section Manager integration (sections/ dir, homepage_sections)
 * - theme_render_favicon/og_image/announcement_bar
 * 
 * @package CMS\Core
 */

defined('CMS_ROOT') or define('CMS_ROOT', dirname(__DIR__));

/* ══════════════════════════════════════════════════════════════════
   Standalone functions called by AiThemeBuilder::step4_assembly()
   ══════════════════════════════════════════════════════════════════ */

/**
 * Build layout.php with header & footer
 */
function ai_theme_build_layout(string $fontsLink, string $headerHtml, string $footerHtml): string
{
    return '<?php
/**
 * AI-Generated Theme Layout
 * Generated by AI Theme Builder
 */

if (!defined(\'CMS_ROOT\')) define(\'CMS_ROOT\', dirname(__DIR__, 2));
if (!defined(\'CMS_APP\')) define(\'CMS_APP\', CMS_ROOT . \'/app\');

require_once CMS_APP . \'/helpers/functions.php\';

if (file_exists(CMS_ROOT . \'/includes/helpers/menu.php\')) {
    require_once CMS_ROOT . \'/includes/helpers/menu.php\';
}

$jtbBootPath = CMS_ROOT . \'/plugins/jessie-theme-builder/includes/jtb-frontend-boot.php\';
if (file_exists($jtbBootPath)) require_once $jtbBootPath;

$themeConfig = get_theme_config();
$themeOptions = $themeConfig[\'options\'] ?? [];
$showHeader = $themeOptions[\'show_header\'] ?? true;
$showFooter = $themeOptions[\'show_footer\'] ?? true;

$siteName = theme_get(\'brand.site_name\', get_site_name());
$siteLogo = theme_get(\'brand.logo\', get_site_logo());
$tsLogo = theme_get(\'brand.logo\') ?: $siteLogo;

$pageData = $page ?? [];
if (!empty($title) && empty($pageData[\'title\'])) $pageData[\'title\'] = $title;
$isTbPage = !empty($page[\'is_tb_page\']);

$themeCssVariables = generate_theme_css_variables($themeConfig);
$themePath = \'/themes/\' . basename(__DIR__);
?><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?= render_seo_meta($pageData) ?>
    ' . $fontsLink . '
    <link rel="stylesheet" href="/assets/css/fontawesome.min.css">
    <link rel="stylesheet" href="/assets/css/tb-frontend.css">
    <link rel="stylesheet" href="<?= $themePath ?>/assets/css/style.css?v=<?= @filemtime(__DIR__ . "/assets/css/style.css") ?: time() ?>">
    <style>
<?= $themeCssVariables ?>
<?= generate_studio_css_overrides() ?>
    </style>
<?= function_exists("theme_render_favicon") ? theme_render_favicon() : "" ?>
<?= function_exists("theme_render_og_image") ? theme_render_og_image() : "" ?>
</head>
<body class="<?= esc(get_body_class() ?? \'\') ?><?= $isTbPage ? \' tb-page\' : \'\' ?>">
<a href="#main-content" class="skip-nav">Skip to content</a>
<?= function_exists("theme_render_announcement_bar") ? theme_render_announcement_bar() : "" ?>

<?php if ($showHeader): ?>
' . $headerHtml . '
<div class="mobile-overlay" id="mobileOverlay"></div>
<?php endif; ?>

<?php if ($isTbPage): ?>
    <?= $content ?? \'\' ?>
<?php else: ?>
    <main id="main-content"><?= $content ?? \'\' ?></main>
<?php endif; ?>

<?php if ($showFooter): ?>
' . $footerHtml . '
<?php endif; ?>

<script src="<?= $themePath ?>/assets/js/main.js"></script>
<?php if (function_exists(\'cms_ab_testing_widget\')): echo cms_ab_testing_widget(); endif; ?>
<?php if (function_exists(\'ai_theme_chat_widget\')): echo ai_theme_chat_widget(); endif; ?>
</body>
</html>';
}

/**
 * Page template — hero with bg image + breadcrumbs + prose
 */
function ai_theme_page_template(): string
{
    return '<?php
/**
 * Page Template — AI Generated
 * Smart rendering: rich AI content (starts with <style, <section, <!--rich-->) renders full-width.
 * Simple HTML content renders in container-narrow prose wrapper.
 */
$_pageContent = $page[\'content\'] ?? \'\';
$_contentTrimmed = ltrim($_pageContent);
$_isRichContent = (
    str_starts_with($_contentTrimmed, \'<style\') ||
    str_starts_with($_contentTrimmed, \'<section\') ||
    str_starts_with($_contentTrimmed, \'<!--rich-->\')
);

// Rich AI content includes its own hero section, so skip the default hero
if (!$_isRichContent):
?>
<section class="page-hero"<?php if (!empty($page[\'featured_image\'])): ?> style="background:url(<?= esc($page[\'featured_image\']) ?>) center/cover no-repeat"<?php endif; ?>>
    <?php if (!empty($page[\'featured_image\'])): ?>
    <div class="page-hero-overlay"></div>
    <?php endif; ?>
    <div class="container">
        <h1 class="page-hero-title" data-page-id="<?= (int)($page[\'id\'] ?? 0) ?>" data-page-field="title"><?= esc($page[\'title\']) ?></h1>
        <div class="page-breadcrumb">
            <a href="/">Home</a>
            <span class="breadcrumb-sep"><i class="fas fa-chevron-right"></i></span>
            <span><?= esc($page[\'title\']) ?></span>
        </div>
    </div>
</section>

<section class="page-content-section">
    <div class="container container-narrow">
        <div class="prose" data-page-id="<?= (int)($page[\'id\'] ?? 0) ?>" data-page-field="content">
            <?= $_pageContent ?>
        </div>
    </div>
</section>
<?php else: ?>
<div data-page-id="<?= (int)($page[\'id\'] ?? 0) ?>" data-page-field="content">
<?= $_pageContent ?>
</div>
<?php endif; ?>';
}

/**
 * Single article template — meta bar, category badge, featured image
 */
function ai_theme_article_template(): string
{
    return '<?php
/**
 * Article Template — AI Generated
 */
?>
<section class="page-hero">
    <div class="container">
        <h1 class="page-hero-title" data-article-id="<?= (int)($article[\'id\'] ?? 0) ?>" data-page-field="title"><?= esc($article[\'title\']) ?></h1>
        <div class="page-breadcrumb">
            <a href="/">Home</a>
            <span class="breadcrumb-sep"><i class="fas fa-chevron-right"></i></span>
            <a href="/articles">Articles</a>
            <span class="breadcrumb-sep"><i class="fas fa-chevron-right"></i></span>
            <span><?= esc($article[\'title\']) ?></span>
        </div>
    </div>
</section>

<section class="page-content-section">
    <div class="container container-narrow">
        <div class="article-meta">
            <?php if (!empty($article[\'category_name\'])): ?>
            <span class="article-category"><?= esc($article[\'category_name\']) ?></span>
            <?php endif; ?>
            <span class="article-date"><i class="far fa-calendar"></i> <?= date(\'F j, Y\', strtotime($article[\'published_at\'] ?? $article[\'created_at\'])) ?></span>
            <?php if (!empty($article[\'views\'])): ?>
            <span><i class="far fa-eye"></i> <?= number_format($article[\'views\']) ?> views</span>
            <?php endif; ?>
        </div>

        <?php if (!empty($article[\'featured_image\'])): ?>
        <div class="article-featured-img">
            <img src="<?= esc($article[\'featured_image\']) ?>" alt="<?= esc($article[\'title\']) ?>">
        </div>
        <?php endif; ?>

        <div class="prose" data-article-id="<?= (int)($article[\'id\'] ?? 0) ?>" data-page-field="content">
            <?= $article[\'content\'] ?>
        </div>

        <div class="article-back">
            <a href="/articles" class="btn btn-outline"><i class="fas fa-arrow-left"></i> Back to Articles</a>
        </div>
    </div>
</section>';
}

/**
 * Articles listing — grid with sidebar categories + pagination
 */
function ai_theme_articles_template(string $sidebarHtml = ''): string
{
    $sidebarBlock = $sidebarHtml ?: '<?php if (!empty($categories)): ?>
            <aside class="atpl-sidebar">
                <div class="atpl-widget">
                    <h4 class="atpl-widget-title"><i class="fas fa-folder"></i> Categories</h4>
                    <?php foreach ($categories as $cat): ?>
                    <a href="/articles?category=<?= esc($cat[\'slug\']) ?>" class="atpl-cat-link">
                        <span><?= esc($cat[\'name\']) ?></span>
                        <span class="atpl-cat-count"><?= (int)($cat[\'article_count\'] ?? 0) ?></span>
                    </a>
                    <?php endforeach; ?>
                </div>
                <div class="atpl-widget">
                    <h4 class="atpl-widget-title"><i class="fas fa-search"></i> Search Articles</h4>
                    <form action="/articles" method="get" class="atpl-search-form">
                        <input type="text" name="q" placeholder="Search..." class="atpl-search-input">
                        <button type="submit" class="atpl-search-btn"><i class="fas fa-arrow-right"></i></button>
                    </form>
                </div>
            </aside>
            <?php endif; ?>';

    return '<?php
/**
 * Articles List Template — AI Generated
 * 2-column layout: article grid + sidebar
 */
?>
<style>
.atpl-hero{padding:calc(var(--section-spacing,.5) * .6) 0;background:var(--surface,#1a1a2e);text-align:center}
.atpl-hero h1{font-family:var(--heading-font,inherit);font-size:clamp(1.8rem,4vw,2.8rem);margin:0 0 8px;color:var(--text,#fff)}
.atpl-breadcrumb{display:flex;align-items:center;justify-content:center;gap:8px;font-size:.85rem;color:var(--text-muted,#999)}
.atpl-breadcrumb a{color:var(--primary,#6c63ff);text-decoration:none}
.atpl-wrap{display:grid;grid-template-columns:1fr 300px;gap:40px;max-width:var(--container-width,1200px);margin:0 auto;padding:calc(var(--section-spacing,.5) * .8) 20px}
.atpl-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:24px}
.atpl-card{background:var(--surface,#1e1e2e);border-radius:var(--border-radius,12px);overflow:hidden;transition:transform .25s,box-shadow .25s;text-decoration:none;color:inherit;display:flex;flex-direction:column;border:1px solid var(--border,#2a2a3a)}
.atpl-card:hover{transform:translateY(-4px);box-shadow:0 12px 32px rgba(0,0,0,.2)}
.atpl-card-img{position:relative;aspect-ratio:16/9;overflow:hidden;background:var(--background,#111)}
.atpl-card-img img{width:100%;height:100%;object-fit:cover;transition:transform .4s}
.atpl-card:hover .atpl-card-img img{transform:scale(1.05)}
.atpl-card-img .atpl-placeholder{display:flex;align-items:center;justify-content:center;width:100%;height:100%;font-size:2rem;color:var(--text-muted,#666)}
.atpl-tag{position:absolute;top:12px;left:12px;background:var(--primary,#6c63ff);color:#fff;font-size:.7rem;padding:4px 10px;border-radius:20px;font-weight:600;text-transform:uppercase;letter-spacing:.05em}
.atpl-card-body{padding:20px;flex:1;display:flex;flex-direction:column}
.atpl-date{font-size:.78rem;color:var(--text-muted,#888);margin-bottom:8px;display:flex;align-items:center;gap:6px}
.atpl-card-body h3{font-family:var(--heading-font,inherit);font-size:1.05rem;margin:0 0 8px;line-height:1.4;color:var(--text,#fff)}
.atpl-card-body p{font-size:.88rem;color:var(--text-muted,#aaa);line-height:1.6;margin:0;flex:1}
.atpl-sidebar{display:flex;flex-direction:column;gap:24px}
.atpl-widget{background:var(--surface,#1e1e2e);border-radius:var(--border-radius,12px);padding:24px;border:1px solid var(--border,#2a2a3a)}
.atpl-widget-title{font-size:.9rem;font-weight:700;margin:0 0 16px;display:flex;align-items:center;gap:8px;color:var(--text,#fff);text-transform:uppercase;letter-spacing:.05em;font-family:var(--heading-font,inherit)}
.atpl-cat-link{display:flex;justify-content:space-between;align-items:center;padding:10px 0;border-bottom:1px solid var(--border,#2a2a3a);text-decoration:none;color:var(--text-muted,#aaa);font-size:.9rem;transition:color .2s}
.atpl-cat-link:last-child{border-bottom:0}
.atpl-cat-link:hover{color:var(--primary,#6c63ff)}
.atpl-cat-count{background:var(--background,#111);font-size:.75rem;padding:2px 8px;border-radius:10px;min-width:24px;text-align:center}
.atpl-search-form{display:flex;gap:8px}
.atpl-search-input{flex:1;padding:10px 14px;border:1px solid var(--border,#2a2a3a);border-radius:var(--border-radius,8px);background:var(--background,#111);color:var(--text,#fff);font-size:.9rem}
.atpl-search-btn{padding:10px 16px;background:var(--primary,#6c63ff);color:#fff;border:0;border-radius:var(--border-radius,8px);cursor:pointer;transition:opacity .2s}
.atpl-search-btn:hover{opacity:.85}
.atpl-pagination{display:flex;align-items:center;justify-content:center;gap:16px;padding:40px 0 0;grid-column:1/-1}
.atpl-pagination a{padding:10px 20px;border:1px solid var(--border,#2a2a3a);border-radius:var(--border-radius,8px);color:var(--text,#fff);text-decoration:none;font-size:.9rem;transition:border-color .2s,background .2s}
.atpl-pagination a:hover{border-color:var(--primary,#6c63ff);background:var(--surface,#1e1e2e)}
.atpl-pagination span{font-size:.85rem;color:var(--text-muted,#888)}
.atpl-empty{text-align:center;padding:80px 20px;grid-column:1/-1}
.atpl-empty i{font-size:3rem;color:var(--text-muted,#555);margin-bottom:16px}
@media(max-width:1024px){.atpl-wrap{grid-template-columns:1fr;}.atpl-sidebar{order:2}}
@media(max-width:640px){.atpl-grid{grid-template-columns:1fr}}
</style>

<section class="atpl-hero">
    <div class="container">
        <h1>Articles</h1>
        <div class="atpl-breadcrumb">
            <a href="/">Home</a>
            <span><i class="fas fa-chevron-right" style="font-size:.6rem"></i></span>
            <span>Articles</span>
        </div>
    </div>
</section>

<div class="atpl-wrap">
    <div>
        <?php if (!empty($articles)): ?>
        <div class="atpl-grid">
            <?php foreach ($articles as $a): ?>
            <a href="/article/<?= esc($a[\'slug\']) ?>" class="atpl-card" data-animate>
                <div class="atpl-card-img">
                    <?php if (!empty($a[\'featured_image\'])): ?>
                    <img src="<?= esc($a[\'featured_image\']) ?>" alt="<?= esc($a[\'title\']) ?>" loading="lazy" decoding="async">
                    <?php else: ?>
                    <div class="atpl-placeholder"><i class="fas fa-newspaper"></i></div>
                    <?php endif; ?>
                    <?php if (!empty($a[\'category_name\'])): ?>
                    <span class="atpl-tag"><?= esc($a[\'category_name\']) ?></span>
                    <?php endif; ?>
                </div>
                <div class="atpl-card-body">
                    <span class="atpl-date"><i class="far fa-calendar-alt"></i> <?= date(\'M j, Y\', strtotime($a[\'published_at\'] ?? $a[\'created_at\'])) ?></span>
                    <h3><?= esc($a[\'title\']) ?></h3>
                    <p><?= esc(mb_strimwidth(strip_tags(!empty($a[\'excerpt\']) ? $a[\'excerpt\'] : $a[\'content\']), 0, 130, \'...\')) ?></p>
                </div>
            </a>
            <?php endforeach; ?>
        </div>

        <?php if ($totalPages > 1): ?>
        <div class="atpl-pagination">
            <?php if ($currentPage > 1): ?>
            <a href="/articles?page=<?= $currentPage - 1 ?>"><i class="fas fa-chevron-left"></i> Previous</a>
            <?php endif; ?>
            <span>Page <?= $currentPage ?> of <?= $totalPages ?></span>
            <?php if ($currentPage < $totalPages): ?>
            <a href="/articles?page=<?= $currentPage + 1 ?>">Next <i class="fas fa-chevron-right"></i></a>
            <?php endif; ?>
        </div>
        <?php endif; ?>

        <?php else: ?>
        <div class="atpl-empty">
            <i class="fas fa-newspaper"></i>
            <h2 style="font-weight:400;margin:0 0 8px">No articles yet</h2>
            <p style="color:var(--text-muted,#888)">Check back soon for new content.</p>
        </div>
        <?php endif; ?>
    </div>

    ' . $sidebarBlock . '
</div>';
}

/**
 * Gallery template — universal, theme-aware
 */
function ai_theme_gallery_template(): string
{
    return '<?php
/**
 * Gallery Template — AI Generated
 */
$_galleries = [];
try {
    $_pdo = \core\Database::connection();
    $_activeTheme = function_exists(\'get_active_theme\') ? get_active_theme() : \'default\';
    $_galStmt = $_pdo->prepare("SELECT * FROM galleries WHERE is_public = 1 AND theme = ? ORDER BY sort_order ASC, name ASC");
    $_galStmt->execute([$_activeTheme]);
    $_galleries = $_galStmt->fetchAll(\PDO::FETCH_ASSOC);
    foreach ($_galleries as &$_gal) {
        $_imgStmt = $_pdo->prepare("SELECT * FROM gallery_images WHERE gallery_id = ? ORDER BY sort_order ASC, id ASC");
        $_imgStmt->execute([$_gal[\'id\']]);
        $_gal[\'images\'] = $_imgStmt->fetchAll(\PDO::FETCH_ASSOC);
    }
    unset($_gal);
} catch (\Throwable $e) {}

$_totalPhotos = 0;
foreach ($_galleries as $_g) $_totalPhotos += count($_g[\'images\'] ?? []);
?>
<link rel="stylesheet" href="/public/css/gallery-layouts.css">

<section class="page-hero">
    <div class="container">
        <h1 class="page-hero-title"><?= esc($page[\'title\'] ?? \'Gallery\') ?></h1>
        <?php if (!empty($page[\'content\']) && trim(strip_tags($page[\'content\'])) !== \'\'): ?>
        <div style="max-width:560px;margin:16px auto 0;opacity:0.7;font-size:1.05rem"><?= $page[\'content\'] ?></div>
        <?php endif; ?>
        <?php if ($_totalPhotos > 0): ?>
        <p style="margin-top:16px;font-size:0.72rem;letter-spacing:0.15em;text-transform:uppercase;opacity:0.3"><?= $_totalPhotos ?> photos · <?= count($_galleries) ?> <?= count($_galleries) === 1 ? \'collection\' : \'collections\' ?></p>
        <?php endif; ?>
    </div>
</section>

<?php if (!empty($_galleries)): ?>
<?php foreach ($_galleries as $_gallery): ?>
<?php if (!empty($_gallery[\'images\'])): ?>
<?php $_template = $_gallery[\'display_template\'] ?? \'grid\'; ?>
<section class="gallery-section" id="gallery-<?= esc($_gallery[\'slug\']) ?>">
    <div class="container">
        <div class="gallery-header">
            <h2><?= esc($_gallery[\'name\']) ?></h2>
            <?php if (!empty($_gallery[\'description\'])): ?>
            <p class="gallery-desc"><?= esc($_gallery[\'description\']) ?></p>
            <?php endif; ?>
            <span class="gallery-count"><?= count($_gallery[\'images\']) ?> photos</span>
        </div>
        <?php if ($_template === \'carousel\'): ?>
        <div class="gallery-layout-carousel">
            <div class="gallery-carousel-track">
                <?php foreach ($_gallery[\'images\'] as $_img): ?>
                <div class="gallery-item" data-src="/uploads/media/<?= esc($_img[\'filename\']) ?>">
                    <img src="/uploads/media/<?= esc($_img[\'filename\']) ?>" alt="<?= esc($_img[\'title\'] ?? \'\') ?>" loading="lazy">
                    <?php if (!empty($_img[\'title\'])): ?><div class="gallery-caption"><span><?= esc($_img[\'title\']) ?></span></div><?php endif; ?>
                </div>
                <?php endforeach; ?>
            </div>
            <div class="gallery-carousel-nav">
                <button class="gallery-carousel-btn" data-dir="prev" aria-label="Previous">&#8249;</button>
                <button class="gallery-carousel-btn" data-dir="next" aria-label="Next">&#8250;</button>
            </div>
        </div>
        <?php else: ?>
        <div class="gallery-layout-<?= esc($_template) ?>">
            <?php foreach ($_gallery[\'images\'] as $_img): ?>
            <div class="gallery-item" data-src="/uploads/media/<?= esc($_img[\'filename\']) ?>">
                <img src="/uploads/media/<?= esc($_img[\'filename\']) ?>" alt="<?= esc($_img[\'title\'] ?? \'\') ?>" loading="lazy">
                <?php if (!empty($_img[\'title\'])): ?><div class="gallery-caption"><span><?= esc($_img[\'title\']) ?></span></div><?php endif; ?>
            </div>
            <?php endforeach; ?>
        </div>
        <?php endif; ?>
    </div>
</section>
<?php endif; ?>
<?php endforeach; ?>
<?php else: ?>
<section class="gallery-section">
    <div class="container" style="text-align:center;padding:100px 0">
        <p style="opacity:0.4;font-size:3rem;margin-bottom:16px">📷</p>
        <h2 style="font-weight:400;margin-bottom:8px">No Galleries Yet</h2>
        <p style="opacity:0.5">Galleries will appear here once created.</p>
    </div>
</section>
<?php endif; ?>
<script src="/public/js/gallery-layouts.js"></script>';
}

/**
 * 404 error template
 */
function ai_theme_404_template(): string
{
    return '<section class="error-section">
    <div class="error-content">
        <span class="error-code">404</span>
        <h1 class="error-title">Page Not Found</h1>
        <p class="error-text">The page you\'re looking for doesn\'t exist or has been moved.</p>
        <div class="error-actions">
            <a href="/" class="btn btn-primary">Go Home</a>
            <a href="/articles" class="btn btn-outline">Browse Articles</a>
        </div>
    </div>
</section>';
}

/**
 * Main JS — header scroll, mobile menu, animations, parallax
 */
function ai_theme_main_js(): string
{
    return <<<'JS'
/**
 * AI-Generated Theme — Main JavaScript
 * Header scroll, mobile menu, scroll animations, parallax
 */
document.addEventListener('DOMContentLoaded', function () {

    /* ── Header scroll ── */
    var header = document.getElementById('siteHeader');
    if (header) {
        function handleScroll() {
            if (window.pageYOffset > 60) {
                header.classList.add('header-scrolled');
            } else {
                header.classList.remove('header-scrolled');
            }
        }
        window.addEventListener('scroll', handleScroll, { passive: true });
        handleScroll();
    }

    /* ── Mobile menu ── */
    var mobileToggle = document.getElementById('mobileToggle');
    var headerNav = document.getElementById('headerNav');
    var mobileOverlay = document.getElementById('mobileOverlay');

    if (mobileToggle && headerNav) {
        mobileToggle.addEventListener('click', function () {
            headerNav.classList.toggle('nav-open');
            mobileToggle.classList.toggle('toggle-active');
            document.body.classList.toggle('nav-open');
            mobileToggle.setAttribute('aria-expanded', document.body.classList.contains('nav-open'));
            if (mobileOverlay) mobileOverlay.classList.toggle('overlay-active');
        });

        if (mobileOverlay) {
            mobileOverlay.addEventListener('click', function () {
                headerNav.classList.remove('nav-open');
                mobileToggle.classList.remove('toggle-active');
                document.body.classList.remove('nav-open');
                mobileToggle.setAttribute('aria-expanded', 'false');
                mobileOverlay.classList.remove('overlay-active');
            });
        }

        headerNav.querySelectorAll('a').forEach(function (link) {
            link.addEventListener('click', function () {
                headerNav.classList.remove('nav-open');
                mobileToggle.classList.remove('toggle-active');
                document.body.classList.remove('nav-open');
                mobileToggle.setAttribute('aria-expanded', 'false');
                if (mobileOverlay) mobileOverlay.classList.remove('overlay-active');
            });
        });
    }

    /* ── Smooth scroll ── */
    document.querySelectorAll('a[href^="#"]').forEach(function (anchor) {
        anchor.addEventListener('click', function (e) {
            var targetId = this.getAttribute('href');
            if (targetId === '#') return;
            var target = document.querySelector(targetId);
            if (target) {
                e.preventDefault();
                var headerHeight = header ? header.offsetHeight : 0;
                window.scrollTo({
                    top: target.getBoundingClientRect().top + window.pageYOffset - headerHeight,
                    behavior: 'smooth'
                });
            }
        });
    });

    /* ── Scroll animations ── */
    var animEls = document.querySelectorAll('[data-animate]');
    if (animEls.length > 0 && 'IntersectionObserver' in window) {
        var delay = 0, lastBatch = 0;
        var obs = new IntersectionObserver(function (entries) {
            entries.forEach(function (entry) {
                if (entry.isIntersecting) {
                    var now = Date.now();
                    if (now - lastBatch > 200) delay = 0;
                    lastBatch = now;
                    setTimeout(function () { entry.target.classList.add('animated'); }, delay);
                    delay += 100;
                    obs.unobserve(entry.target);
                }
            });
        }, { threshold: 0.12, rootMargin: '0px 0px -60px 0px' });
        animEls.forEach(function (el) { obs.observe(el); });
    } else {
        // Fallback: no IntersectionObserver — show all immediately
        animEls.forEach(function (el) { el.classList.add('animated'); });
    }

    // Safety net: if any [data-animate] elements are still hidden after 2s, force-show them
    // This prevents invisible content if JS animation fails for any reason
    setTimeout(function () {
        document.querySelectorAll('[data-animate]:not(.animated)').forEach(function (el) {
            el.classList.add('animated');
        });
    }, 2000);

    /* ── Hero parallax ── */
    var heroBg = document.querySelector('.hero-bg, .hero__bg');
    if (heroBg) {
        var ticking = false;
        window.addEventListener('scroll', function () {
            if (!ticking) {
                requestAnimationFrame(function () {
                    var scrolled = window.pageYOffset;
                    if (scrolled < window.innerHeight) {
                        heroBg.style.transform = 'translateY(' + (scrolled * 0.35) + 'px)';
                    }
                    ticking = false;
                });
                ticking = true;
            }
        }, { passive: true });
    }

    /* ── Back to top button ── */
    var backToTop = document.querySelector('.back-to-top, #backToTop');
    if (backToTop) {
        window.addEventListener('scroll', function () {
            if (window.pageYOffset > 400) {
                backToTop.classList.add('visible');
            } else {
                backToTop.classList.remove('visible');
            }
        }, { passive: true });
        backToTop.addEventListener('click', function (e) {
            e.preventDefault();
            window.scrollTo({ top: 0, behavior: 'smooth' });
        });
    }

    /* ── FAQ Accordion ── */
    document.querySelectorAll('.faq-question, .accordion-trigger, [data-accordion]').forEach(function (trigger) {
        trigger.addEventListener('click', function () {
            var parent = this.closest('.faq-item, .accordion-item');
            if (!parent) return;
            var isActive = parent.classList.contains('active');
            // Close siblings
            var container = parent.parentElement;
            if (container) {
                container.querySelectorAll('.faq-item.active, .accordion-item.active').forEach(function (item) {
                    item.classList.remove('active');
                    var answer = item.querySelector('.faq-answer, .accordion-content');
                    if (answer) answer.style.maxHeight = null;
                });
            }
            // Toggle current
            if (!isActive) {
                parent.classList.add('active');
                var answer = parent.querySelector('.faq-answer, .accordion-content');
                if (answer) answer.style.maxHeight = answer.scrollHeight + 'px';
            }
        });
    });

    /* ── Counter animation (stats) ── */
    var counters = document.querySelectorAll('[data-count], .stat-number, .counter');
    if (counters.length > 0 && 'IntersectionObserver' in window) {
        var counterObs = new IntersectionObserver(function (entries) {
            entries.forEach(function (entry) {
                if (entry.isIntersecting) {
                    var el = entry.target;
                    var target = parseInt(el.getAttribute('data-count') || el.textContent.replace(/[^0-9]/g, ''), 10);
                    if (isNaN(target) || target === 0) return;
                    var suffix = el.textContent.replace(/[0-9,. ]/g, '');
                    var duration = 1500;
                    var start = 0;
                    var startTime = null;
                    function step(ts) {
                        if (!startTime) startTime = ts;
                        var progress = Math.min((ts - startTime) / duration, 1);
                        var eased = 1 - Math.pow(1 - progress, 3);
                        el.textContent = Math.floor(eased * target).toLocaleString() + suffix;
                        if (progress < 1) requestAnimationFrame(step);
                    }
                    requestAnimationFrame(step);
                    counterObs.unobserve(el);
                }
            });
        }, { threshold: 0.3 });
        counters.forEach(function (el) { counterObs.observe(el); });
    }

    /* ── Lightbox for gallery images ── */
    document.querySelectorAll('.gallery-item img, .lightbox-trigger img, [data-lightbox] img').forEach(function (img) {
        img.style.cursor = 'pointer';
        img.addEventListener('click', function () {
            var overlay = document.createElement('div');
            overlay.style.cssText = 'position:fixed;inset:0;z-index:9999;background:rgba(0,0,0,0.9);display:flex;align-items:center;justify-content:center;cursor:pointer;opacity:0;transition:opacity 0.3s';
            var bigImg = document.createElement('img');
            bigImg.src = this.src;
            bigImg.alt = this.alt || '';
            bigImg.style.cssText = 'max-width:90vw;max-height:90vh;object-fit:contain;border-radius:8px;transform:scale(0.9);transition:transform 0.3s';
            overlay.appendChild(bigImg);
            document.body.appendChild(overlay);
            requestAnimationFrame(function () { overlay.style.opacity = '1'; bigImg.style.transform = 'scale(1)'; });
            overlay.addEventListener('click', function () {
                overlay.style.opacity = '0';
                setTimeout(function () { overlay.remove(); }, 300);
            });
            document.addEventListener('keydown', function escHandler(e) {
                if (e.key === 'Escape') { overlay.click(); document.removeEventListener('keydown', escHandler); }
            });
        });
    });

    /* ── Dark mode toggle ── */
    var darkToggle = document.querySelector('[data-dark-toggle], .dark-mode-toggle');
    if (darkToggle) {
        var prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
        var savedTheme = localStorage.getItem('theme-mode');
        if (savedTheme) {
            document.documentElement.setAttribute('data-theme', savedTheme);
        } else if (prefersDark) {
            document.documentElement.setAttribute('data-theme', 'dark');
        }

        darkToggle.addEventListener('click', function() {
            var current = document.documentElement.getAttribute('data-theme');
            var next = current === 'dark' ? 'light' : 'dark';
            document.documentElement.setAttribute('data-theme', next);
            localStorage.setItem('theme-mode', next);
            this.textContent = next === 'dark' ? '☀️' : '🌙';
        });

        // Set initial icon
        var isDark = document.documentElement.getAttribute('data-theme') === 'dark' ||
                     (!document.documentElement.getAttribute('data-theme') && prefersDark);
        darkToggle.textContent = isDark ? '☀️' : '🌙';
    }

    /* ── Contact form AJAX handler ── */
    document.querySelectorAll('.contact-form, form[action="#"][method="post"]').forEach(function(form) {
        // Skip if it's clearly not a contact form
        var hasMessage = form.querySelector('[name="message"], textarea');
        var hasEmail = form.querySelector('[name="email"], input[type="email"]');
        if (!hasMessage || !hasEmail) return;

        form.addEventListener('submit', function(e) {
            e.preventDefault();
            var btn = form.querySelector('[type="submit"], button:last-of-type');
            var originalText = btn ? btn.textContent : '';
            if (btn) { btn.disabled = true; btn.textContent = 'Sending...'; }

            var data = {};
            new FormData(form).forEach(function(val, key) { data[key] = val; });
            data._page_slug = window.location.pathname.replace(/^\/page\//, '').replace(/^\//, '');

            fetch('/api/contact', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(data)
            })
            .then(function(r) { return r.json().then(function(d) { return { ok: r.ok, data: d }; }); })
            .then(function(res) {
                // Remove any existing alert
                var old = form.querySelector('.contact-alert');
                if (old) old.remove();

                var alert = document.createElement('div');
                alert.className = 'contact-alert';
                alert.style.cssText = 'padding:14px 20px;border-radius:8px;margin:16px 0;font-size:0.9rem;';

                if (res.ok && res.data.success) {
                    alert.style.background = 'rgba(34,197,94,0.15)';
                    alert.style.color = '#22c55e';
                    alert.style.border = '1px solid rgba(34,197,94,0.3)';
                    alert.textContent = res.data.message || 'Message sent successfully!';
                    form.reset();
                } else {
                    alert.style.background = 'rgba(239,68,68,0.15)';
                    alert.style.color = '#ef4444';
                    alert.style.border = '1px solid rgba(239,68,68,0.3)';
                    var errors = res.data.errors || [res.data.error || 'Something went wrong.'];
                    alert.textContent = Array.isArray(errors) ? errors.join(' ') : errors;
                }
                form.insertBefore(alert, form.firstChild);
                setTimeout(function() { alert.remove(); }, 8000);
            })
            .catch(function() {
                var alert = document.createElement('div');
                alert.className = 'contact-alert';
                alert.style.cssText = 'padding:14px 20px;border-radius:8px;margin:16px 0;background:rgba(239,68,68,0.15);color:#ef4444;border:1px solid rgba(239,68,68,0.3);';
                alert.textContent = 'Network error. Please try again.';
                form.insertBefore(alert, form.firstChild);
            })
            .finally(function() {
                if (btn) { btn.disabled = false; btn.textContent = originalText; }
            });
        });
    });

});
JS;
}

/**
 * Home template that uses sections/ directory (dynamic section loading)
 */
function ai_theme_home_template(string $slug, array $sectionIds): string
{
    $php = '<?php
/**
 * Home Template — AI Generated
 * Dynamic section loading via Section Manager
 */

// Pre-load customized values with defaults
$heroHeadline = theme_get(\'hero.headline\', \'Welcome to Our Website\');
$heroSubtitle = theme_get(\'hero.subtitle\', \'Discover what we have to offer.\');
$heroBtnText  = theme_get(\'hero.btn_text\', \'Get Started\');
$heroBtnLink  = theme_get(\'hero.btn_link\', \'#\');
$heroBgImage  = theme_get(\'hero.bg_image\');

$aboutLabel = theme_get(\'about.label\', \'About Us\');
$aboutTitle = theme_get(\'about.title\', \'Our Story\');
$aboutDesc  = theme_get(\'about.description\', \'We are passionate about what we do.\');
$aboutImage = theme_get(\'about.image\');

$pagesLabel = theme_get(\'pages.label\', \'Explore\');
$pagesTitle = theme_get(\'pages.title\', \'What We Offer\');
$pagesDesc  = theme_get(\'pages.description\', \'Discover our range of services and offerings.\');

$articlesLabel   = theme_get(\'articles.label\', \'Latest\');
$articlesTitle   = theme_get(\'articles.title\', \'News & Updates\');
$articlesDesc    = theme_get(\'articles.description\', \'Stay up to date with our latest news.\');
$articlesBtnText = theme_get(\'articles.btn_text\', \'View All\');
$articlesBtnLink = theme_get(\'articles.btn_link\', \'/articles\');

$ctaTitle   = theme_get(\'cta.title\', \'Ready to Get Started?\');
$ctaDesc    = theme_get(\'cta.description\', \'Contact us today to learn more.\');
$ctaBtnText = theme_get(\'cta.btn_text\', \'Contact Us\');
$ctaBtnLink = theme_get(\'cta.btn_link\', \'#\');

// Dynamic section loading
$themeConfig = get_theme_config(get_active_theme());
$defaultOrder = array_column($themeConfig[\'homepage_sections\'] ?? [], \'id\');
$sectionOrder = theme_get_section_order();
if (empty($sectionOrder)) $sectionOrder = $defaultOrder;

foreach ($sectionOrder as $sectionId) {
    if (!theme_section_enabled($sectionId)) continue;
    $sectionFile = __DIR__ . \'/../sections/\' . $sectionId . \'.php\';
    if (file_exists($sectionFile)) require $sectionFile;
}
?>';
    return $php;
}
