<?php
/**
 * AI Theme Builder — Boilerplate Templates
 * 
 * Fixed PHP templates ensuring correct CMS integration.
 * Uses theme_get(), data-ts, generate_studio_css_overrides(), etc.
 * 
 * Lessons from manual theme building applied:
 * - Professional CSS variable palette  
 * - Decorative ornamental elements
 * - Photo-forward overlay cards
 * - Premium typography hierarchy (section-label → divider → title → desc)
 * - data-animate scroll animations
 * - Mobile slide-out nav
 * - Gallery template support
 * - Section Manager integration (sections/ dir, homepage_sections)
 * - theme_render_favicon/og_image/announcement_bar
 * 
 * @package CMS\Core
 */

defined('CMS_ROOT') or define('CMS_ROOT', dirname(__DIR__));

/* ══════════════════════════════════════════════════════════════════
   Standalone functions called by AiThemeBuilder::step4_assembly()
   ══════════════════════════════════════════════════════════════════ */

/**
 * Build layout.php with header & footer
 */
function ai_theme_build_layout(string $fontsLink, string $headerHtml, string $footerHtml): string
{
    return '<?php
/**
 * AI-Generated Theme Layout
 * Generated by AI Theme Builder
 */

if (!defined(\'CMS_ROOT\')) define(\'CMS_ROOT\', dirname(__DIR__, 2));
if (!defined(\'CMS_APP\')) define(\'CMS_APP\', CMS_ROOT . \'/app\');

require_once CMS_APP . \'/helpers/functions.php\';

if (file_exists(CMS_ROOT . \'/includes/helpers/menu.php\')) {
    require_once CMS_ROOT . \'/includes/helpers/menu.php\';
}

$jtbBootPath = CMS_ROOT . \'/plugins/jessie-theme-builder/includes/jtb-frontend-boot.php\';
if (file_exists($jtbBootPath)) require_once $jtbBootPath;

$themeConfig = get_theme_config();
$themeOptions = $themeConfig[\'options\'] ?? [];
$showHeader = $themeOptions[\'show_header\'] ?? true;
$showFooter = $themeOptions[\'show_footer\'] ?? true;

$siteName = theme_get(\'brand.site_name\', get_site_name());
$siteLogo = theme_get(\'brand.logo\', get_site_logo());
$tsLogo = theme_get(\'brand.logo\') ?: $siteLogo;

$pageData = $page ?? [];
if (!empty($title) && empty($pageData[\'title\'])) $pageData[\'title\'] = $title;
$isTbPage = !empty($page[\'is_tb_page\']);

$themeCssVariables = generate_theme_css_variables($themeConfig);
$themePath = \'/themes/\' . basename(__DIR__);
?><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?= render_seo_meta($pageData) ?>
    ' . $fontsLink . '
    <link rel="stylesheet" href="/assets/css/fontawesome.min.css">
    <link rel="stylesheet" href="/assets/css/tb-frontend.css">
    <link rel="stylesheet" href="<?= $themePath ?>/assets/css/style.css">
    <style>
<?= $themeCssVariables ?>
<?= generate_studio_css_overrides() ?>
    </style>
<?= function_exists("theme_render_favicon") ? theme_render_favicon() : "" ?>
<?= function_exists("theme_render_og_image") ? theme_render_og_image() : "" ?>
</head>
<body class="<?= esc(get_body_class() ?? \'\') ?><?= $isTbPage ? \' tb-page\' : \'\' ?>">
<?= function_exists("theme_render_announcement_bar") ? theme_render_announcement_bar() : "" ?>

<?php if ($showHeader): ?>
' . $headerHtml . '
<div class="mobile-overlay" id="mobileOverlay"></div>
<?php endif; ?>

<?php if ($isTbPage): ?>
    <?= $content ?? \'\' ?>
<?php else: ?>
    <main><?= $content ?? \'\' ?></main>
<?php endif; ?>

<?php if ($showFooter): ?>
' . $footerHtml . '
<?php endif; ?>

<script src="<?= $themePath ?>/assets/js/main.js"></script>
</body>
</html>';
}

/**
 * Page template — hero with bg image + breadcrumbs + prose
 */
function ai_theme_page_template(): string
{
    return '<?php
/**
 * Page Template — AI Generated
 */
?>
<section class="page-hero"<?php if (!empty($page[\'featured_image\'])): ?> style="background:url(<?= esc($page[\'featured_image\']) ?>) center/cover no-repeat"<?php endif; ?>>
    <?php if (!empty($page[\'featured_image\'])): ?>
    <div class="page-hero-overlay"></div>
    <?php endif; ?>
    <div class="container">
        <h1 class="page-hero-title"><?= esc($page[\'title\']) ?></h1>
        <div class="page-breadcrumb">
            <a href="/">Home</a>
            <span class="breadcrumb-sep"><i class="fas fa-chevron-right"></i></span>
            <span><?= esc($page[\'title\']) ?></span>
        </div>
    </div>
</section>

<section class="page-content-section">
    <div class="container container-narrow">
        <div class="prose">
            <?= $page[\'content\'] ?>
        </div>
    </div>
</section>';
}

/**
 * Single article template — meta bar, category badge, featured image
 */
function ai_theme_article_template(): string
{
    return '<?php
/**
 * Article Template — AI Generated
 */
?>
<section class="page-hero">
    <div class="container">
        <h1 class="page-hero-title"><?= esc($article[\'title\']) ?></h1>
        <div class="page-breadcrumb">
            <a href="/">Home</a>
            <span class="breadcrumb-sep"><i class="fas fa-chevron-right"></i></span>
            <a href="/articles">Articles</a>
            <span class="breadcrumb-sep"><i class="fas fa-chevron-right"></i></span>
            <span><?= esc($article[\'title\']) ?></span>
        </div>
    </div>
</section>

<section class="page-content-section">
    <div class="container container-narrow">
        <div class="article-meta">
            <?php if (!empty($article[\'category_name\'])): ?>
            <span class="article-category"><?= esc($article[\'category_name\']) ?></span>
            <?php endif; ?>
            <span class="article-date"><i class="far fa-calendar"></i> <?= date(\'F j, Y\', strtotime($article[\'published_at\'] ?? $article[\'created_at\'])) ?></span>
            <?php if (!empty($article[\'views\'])): ?>
            <span><i class="far fa-eye"></i> <?= number_format($article[\'views\']) ?> views</span>
            <?php endif; ?>
        </div>

        <?php if (!empty($article[\'featured_image\'])): ?>
        <div class="article-featured-img">
            <img src="<?= esc($article[\'featured_image\']) ?>" alt="<?= esc($article[\'title\']) ?>">
        </div>
        <?php endif; ?>

        <div class="prose">
            <?= $article[\'content\'] ?>
        </div>

        <div class="article-back">
            <a href="/articles" class="btn btn-outline"><i class="fas fa-arrow-left"></i> Back to Articles</a>
        </div>
    </div>
</section>';
}

/**
 * Articles listing — grid with sidebar categories + pagination
 */
function ai_theme_articles_template(): string
{
    return '<?php
/**
 * Articles List Template — AI Generated
 */
?>
<section class="page-hero">
    <div class="container">
        <h1 class="page-hero-title">Articles</h1>
        <div class="page-breadcrumb">
            <a href="/">Home</a>
            <span class="breadcrumb-sep"><i class="fas fa-chevron-right"></i></span>
            <span>Articles</span>
        </div>
    </div>
</section>

<section class="section">
    <div class="container">
        <div class="articles-layout">
            <div>
                <?php if (!empty($articles)): ?>
                <div class="articles-grid">
                    <?php foreach ($articles as $a): ?>
                    <a href="/article/<?= esc($a[\'slug\']) ?>" class="article-card" data-animate>
                        <div class="article-card-img">
                            <?php if (!empty($a[\'featured_image\'])): ?>
                            <img src="<?= esc($a[\'featured_image\']) ?>" alt="<?= esc($a[\'title\']) ?>" loading="lazy">
                            <?php else: ?>
                            <div class="img-placeholder"><i class="fas fa-newspaper"></i></div>
                            <?php endif; ?>
                            <?php if (!empty($a[\'category_name\'])): ?>
                            <span class="article-card-tag"><?= esc($a[\'category_name\']) ?></span>
                            <?php endif; ?>
                        </div>
                        <div class="article-card-body">
                            <span class="article-card-date"><i class="far fa-calendar"></i> <?= date(\'M j, Y\', strtotime($a[\'published_at\'] ?? $a[\'created_at\'])) ?></span>
                            <h3><?= esc($a[\'title\']) ?></h3>
                            <p><?= esc(mb_strimwidth(strip_tags(!empty($a[\'excerpt\']) ? $a[\'excerpt\'] : $a[\'content\']), 0, 130, \'...\')) ?></p>
                        </div>
                    </a>
                    <?php endforeach; ?>
                </div>

                <?php if ($totalPages > 1): ?>
                <div class="pagination">
                    <?php if ($currentPage > 1): ?>
                    <a href="/articles?page=<?= $currentPage - 1 ?>" class="btn btn-outline"><i class="fas fa-chevron-left"></i> Previous</a>
                    <?php endif; ?>
                    <span class="pagination-info">Page <?= $currentPage ?> of <?= $totalPages ?></span>
                    <?php if ($currentPage < $totalPages): ?>
                    <a href="/articles?page=<?= $currentPage + 1 ?>" class="btn btn-outline">Next <i class="fas fa-chevron-right"></i></a>
                    <?php endif; ?>
                </div>
                <?php endif; ?>

                <?php else: ?>
                <div style="text-align:center;padding:60px 0">
                    <h2>No articles yet</h2>
                    <p style="opacity:0.6;margin-top:8px">Check back soon for new content.</p>
                </div>
                <?php endif; ?>
            </div>

            <?php if (!empty($categories)): ?>
            <aside>
                <div class="sidebar-widget">
                    <h4>Categories</h4>
                    <?php foreach ($categories as $cat): ?>
                    <a href="/articles?category=<?= esc($cat[\'slug\']) ?>" class="sidebar-cat-link">
                        <span><?= esc($cat[\'name\']) ?></span>
                        <span class="sidebar-cat-count"><?= (int)($cat[\'article_count\'] ?? 0) ?></span>
                    </a>
                    <?php endforeach; ?>
                </div>
            </aside>
            <?php endif; ?>
        </div>
    </div>
</section>';
}

/**
 * Gallery template — universal, theme-aware
 */
function ai_theme_gallery_template(): string
{
    return '<?php
/**
 * Gallery Template — AI Generated
 */
$_galleries = [];
try {
    $_pdo = \core\Database::connection();
    $_activeTheme = function_exists(\'get_active_theme\') ? get_active_theme() : \'default\';
    $_galStmt = $_pdo->prepare("SELECT * FROM galleries WHERE is_public = 1 AND (theme = ? OR theme IS NULL OR theme = \'\') ORDER BY sort_order ASC, name ASC");
    $_galStmt->execute([$_activeTheme]);
    $_galleries = $_galStmt->fetchAll(\PDO::FETCH_ASSOC);
    foreach ($_galleries as &$_gal) {
        $_imgStmt = $_pdo->prepare("SELECT * FROM gallery_images WHERE gallery_id = ? ORDER BY sort_order ASC, id ASC");
        $_imgStmt->execute([$_gal[\'id\']]);
        $_gal[\'images\'] = $_imgStmt->fetchAll(\PDO::FETCH_ASSOC);
    }
    unset($_gal);
} catch (\Throwable $e) {}

$_totalPhotos = 0;
foreach ($_galleries as $_g) $_totalPhotos += count($_g[\'images\'] ?? []);
?>
<link rel="stylesheet" href="/public/css/gallery-layouts.css">

<section class="page-hero">
    <div class="container">
        <h1 class="page-hero-title"><?= esc($page[\'title\'] ?? \'Gallery\') ?></h1>
        <?php if (!empty($page[\'content\']) && trim(strip_tags($page[\'content\'])) !== \'\'): ?>
        <div style="max-width:560px;margin:16px auto 0;opacity:0.7;font-size:1.05rem"><?= $page[\'content\'] ?></div>
        <?php endif; ?>
        <?php if ($_totalPhotos > 0): ?>
        <p style="margin-top:16px;font-size:0.72rem;letter-spacing:0.15em;text-transform:uppercase;opacity:0.3"><?= $_totalPhotos ?> photos · <?= count($_galleries) ?> <?= count($_galleries) === 1 ? \'collection\' : \'collections\' ?></p>
        <?php endif; ?>
    </div>
</section>

<?php if (!empty($_galleries)): ?>
<?php foreach ($_galleries as $_gallery): ?>
<?php if (!empty($_gallery[\'images\'])): ?>
<?php $_template = $_gallery[\'display_template\'] ?? \'grid\'; ?>
<section class="gallery-section" id="gallery-<?= esc($_gallery[\'slug\']) ?>">
    <div class="container">
        <div class="gallery-header">
            <h2><?= esc($_gallery[\'name\']) ?></h2>
            <?php if (!empty($_gallery[\'description\'])): ?>
            <p class="gallery-desc"><?= esc($_gallery[\'description\']) ?></p>
            <?php endif; ?>
            <span class="gallery-count"><?= count($_gallery[\'images\']) ?> photos</span>
        </div>
        <?php if ($_template === \'carousel\'): ?>
        <div class="gallery-layout-carousel">
            <div class="gallery-carousel-track">
                <?php foreach ($_gallery[\'images\'] as $_img): ?>
                <div class="gallery-item" data-src="/uploads/media/<?= esc($_img[\'filename\']) ?>">
                    <img src="/uploads/media/<?= esc($_img[\'filename\']) ?>" alt="<?= esc($_img[\'title\'] ?? \'\') ?>" loading="lazy">
                    <?php if (!empty($_img[\'title\'])): ?><div class="gallery-caption"><span><?= esc($_img[\'title\']) ?></span></div><?php endif; ?>
                </div>
                <?php endforeach; ?>
            </div>
            <div class="gallery-carousel-nav">
                <button class="gallery-carousel-btn" data-dir="prev" aria-label="Previous">&#8249;</button>
                <button class="gallery-carousel-btn" data-dir="next" aria-label="Next">&#8250;</button>
            </div>
        </div>
        <?php else: ?>
        <div class="gallery-layout-<?= esc($_template) ?>">
            <?php foreach ($_gallery[\'images\'] as $_img): ?>
            <div class="gallery-item" data-src="/uploads/media/<?= esc($_img[\'filename\']) ?>">
                <img src="/uploads/media/<?= esc($_img[\'filename\']) ?>" alt="<?= esc($_img[\'title\'] ?? \'\') ?>" loading="lazy">
                <?php if (!empty($_img[\'title\'])): ?><div class="gallery-caption"><span><?= esc($_img[\'title\']) ?></span></div><?php endif; ?>
            </div>
            <?php endforeach; ?>
        </div>
        <?php endif; ?>
    </div>
</section>
<?php endif; ?>
<?php endforeach; ?>
<?php else: ?>
<section class="gallery-section">
    <div class="container" style="text-align:center;padding:100px 0">
        <p style="opacity:0.4;font-size:3rem;margin-bottom:16px">📷</p>
        <h2 style="font-weight:400;margin-bottom:8px">No Galleries Yet</h2>
        <p style="opacity:0.5">Galleries will appear here once created.</p>
    </div>
</section>
<?php endif; ?>
<script src="/public/js/gallery-layouts.js"></script>';
}

/**
 * 404 error template
 */
function ai_theme_404_template(): string
{
    return '<section class="error-section">
    <div class="error-content">
        <span class="error-code">404</span>
        <h1 class="error-title">Page Not Found</h1>
        <p class="error-text">The page you\'re looking for doesn\'t exist or has been moved.</p>
        <div class="error-actions">
            <a href="/" class="btn btn-primary">Go Home</a>
            <a href="/articles" class="btn btn-outline">Browse Articles</a>
        </div>
    </div>
</section>';
}

/**
 * Main JS — header scroll, mobile menu, animations, parallax
 */
function ai_theme_main_js(): string
{
    return <<<'JS'
/**
 * AI-Generated Theme — Main JavaScript
 * Header scroll, mobile menu, scroll animations, parallax
 */
document.addEventListener('DOMContentLoaded', function () {

    /* ── Header scroll ── */
    var header = document.getElementById('siteHeader');
    if (header) {
        function handleScroll() {
            if (window.pageYOffset > 60) {
                header.classList.add('header-scrolled');
            } else {
                header.classList.remove('header-scrolled');
            }
        }
        window.addEventListener('scroll', handleScroll, { passive: true });
        handleScroll();
    }

    /* ── Mobile menu ── */
    var mobileToggle = document.getElementById('mobileToggle');
    var headerNav = document.getElementById('headerNav');
    var mobileOverlay = document.getElementById('mobileOverlay');

    if (mobileToggle && headerNav) {
        mobileToggle.addEventListener('click', function () {
            headerNav.classList.toggle('nav-open');
            mobileToggle.classList.toggle('toggle-active');
            document.body.classList.toggle('menu-open');
            if (mobileOverlay) mobileOverlay.classList.toggle('overlay-active');
        });

        if (mobileOverlay) {
            mobileOverlay.addEventListener('click', function () {
                headerNav.classList.remove('nav-open');
                mobileToggle.classList.remove('toggle-active');
                document.body.classList.remove('menu-open');
                mobileOverlay.classList.remove('overlay-active');
            });
        }

        headerNav.querySelectorAll('.nav-link').forEach(function (link) {
            link.addEventListener('click', function () {
                headerNav.classList.remove('nav-open');
                mobileToggle.classList.remove('toggle-active');
                document.body.classList.remove('menu-open');
                if (mobileOverlay) mobileOverlay.classList.remove('overlay-active');
            });
        });
    }

    /* ── Smooth scroll ── */
    document.querySelectorAll('a[href^="#"]').forEach(function (anchor) {
        anchor.addEventListener('click', function (e) {
            var targetId = this.getAttribute('href');
            if (targetId === '#') return;
            var target = document.querySelector(targetId);
            if (target) {
                e.preventDefault();
                var headerHeight = header ? header.offsetHeight : 0;
                window.scrollTo({
                    top: target.getBoundingClientRect().top + window.pageYOffset - headerHeight,
                    behavior: 'smooth'
                });
            }
        });
    });

    /* ── Scroll animations ── */
    var animEls = document.querySelectorAll('[data-animate]');
    if (animEls.length > 0 && 'IntersectionObserver' in window) {
        var delay = 0, lastBatch = 0;
        var obs = new IntersectionObserver(function (entries) {
            entries.forEach(function (entry) {
                if (entry.isIntersecting) {
                    var now = Date.now();
                    if (now - lastBatch > 200) delay = 0;
                    lastBatch = now;
                    setTimeout(function () { entry.target.classList.add('animated'); }, delay);
                    delay += 100;
                    obs.unobserve(entry.target);
                }
            });
        }, { threshold: 0.12, rootMargin: '0px 0px -60px 0px' });
        animEls.forEach(function (el) { obs.observe(el); });
    }

    /* ── Hero parallax ── */
    var heroBg = document.querySelector('.hero-bg, .hero__bg');
    if (heroBg) {
        var ticking = false;
        window.addEventListener('scroll', function () {
            if (!ticking) {
                requestAnimationFrame(function () {
                    var scrolled = window.pageYOffset;
                    if (scrolled < window.innerHeight) {
                        heroBg.style.transform = 'translateY(' + (scrolled * 0.35) + 'px)';
                    }
                    ticking = false;
                });
                ticking = true;
            }
        }, { passive: true });
    }

});
JS;
}

/**
 * Home template that uses sections/ directory (dynamic section loading)
 */
function ai_theme_home_template(string $slug, array $sectionIds): string
{
    $php = '<?php
/**
 * Home Template — AI Generated
 * Dynamic section loading via Section Manager
 */

// Pre-load customized values with defaults
$heroHeadline = theme_get(\'hero.headline\', \'Welcome to Our Website\');
$heroSubtitle = theme_get(\'hero.subtitle\', \'Discover what we have to offer.\');
$heroBtnText  = theme_get(\'hero.btn_text\', \'Get Started\');
$heroBtnLink  = theme_get(\'hero.btn_link\', \'#\');
$heroBgImage  = theme_get(\'hero.bg_image\');

$aboutLabel = theme_get(\'about.label\', \'About Us\');
$aboutTitle = theme_get(\'about.title\', \'Our Story\');
$aboutDesc  = theme_get(\'about.description\', \'We are passionate about what we do.\');
$aboutImage = theme_get(\'about.image\');

$pagesLabel = theme_get(\'pages.label\', \'Explore\');
$pagesTitle = theme_get(\'pages.title\', \'What We Offer\');
$pagesDesc  = theme_get(\'pages.description\', \'Discover our range of services and offerings.\');

$articlesLabel   = theme_get(\'articles.label\', \'Latest\');
$articlesTitle   = theme_get(\'articles.title\', \'News & Updates\');
$articlesDesc    = theme_get(\'articles.description\', \'Stay up to date with our latest news.\');
$articlesBtnText = theme_get(\'articles.btn_text\', \'View All\');
$articlesBtnLink = theme_get(\'articles.btn_link\', \'/articles\');

$ctaTitle   = theme_get(\'cta.title\', \'Ready to Get Started?\');
$ctaDesc    = theme_get(\'cta.description\', \'Contact us today to learn more.\');
$ctaBtnText = theme_get(\'cta.btn_text\', \'Contact Us\');
$ctaBtnLink = theme_get(\'cta.btn_link\', \'#\');

// Dynamic section loading
$themeConfig = get_theme_config(get_active_theme());
$defaultOrder = array_column($themeConfig[\'homepage_sections\'] ?? [], \'id\');
$sectionOrder = theme_get_section_order();
if (empty($sectionOrder)) $sectionOrder = $defaultOrder;

foreach ($sectionOrder as $sectionId) {
    if (!theme_section_enabled($sectionId)) continue;
    $sectionFile = __DIR__ . \'/../sections/\' . $sectionId . \'.php\';
    if (file_exists($sectionFile)) require $sectionFile;
}
?>';
    return $php;
}
