<?php
/**
 * AI Theme Builder — Boilerplate Templates
 * 
 * Fixed PHP templates with placeholders for AI-generated HTML.
 * These ensure correct CMS integration (theme_get, generate_studio_css_overrides, etc.)
 * 
 * @package CMS\Core
 */

defined('CMS_ROOT') or define('CMS_ROOT', dirname(__DIR__));

class AiThemeTemplates
{
    /**
     * Generate layout.php with AI-generated header & footer HTML.
     */
    public function layoutPhp(string $slug, string $fontsUrl, string $headerHtml, string $footerHtml): string
    {
        // Escape the slug for use in PHP string
        $escapedSlug = addslashes($slug);

        return <<<'LAYOUT_TOP'
<?php
/**
 * AI-Generated Theme Layout
 * Generated by AI Theme Builder
 */

if (!defined('CMS_ROOT')) {
    define('CMS_ROOT', dirname(__DIR__, 2));
}
if (!defined('CMS_APP')) {
    define('CMS_APP', CMS_ROOT . '/app');
}

// Load helpers
require_once CMS_APP . '/helpers/functions.php';

// Load menu helper
if (file_exists(CMS_ROOT . '/includes/helpers/menu.php')) {
    require_once CMS_ROOT . '/includes/helpers/menu.php';
}

// Load JTB for custom headers/footers
$jtbBootPath = CMS_ROOT . '/plugins/jessie-theme-builder/includes/jtb-frontend-boot.php';
if (file_exists($jtbBootPath)) {
    require_once $jtbBootPath;
}

// Get theme config
$themeConfig = get_theme_config();
$themeOptions = $themeConfig['options'] ?? [];

// Options
$showHeader = $themeOptions['show_header'] ?? true;
$showFooter = $themeOptions['show_footer'] ?? true;

// Site info
$siteName = get_site_name();
$siteLogo = get_site_logo();

// Page context
$pageData = $page ?? [];
if (!empty($title) && empty($pageData['title'])) {
    $pageData['title'] = $title;
}

// Is this a TB page?
$isTbPage = !empty($page['is_tb_page']);

// Generate CSS variables from theme.json
$themeCssVariables = generate_theme_css_variables($themeConfig);

// Theme path
LAYOUT_TOP
        . "\n\$themePath = '/themes/" . $escapedSlug . "';\n"
        . '?>' . "<!DOCTYPE html>\n"
        . "<html lang=\"en\">\n<head>\n"
        . "    <meta charset=\"UTF-8\">\n"
        . "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        . "    <?= render_seo_meta(\$pageData) ?>\n"
        . "    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n"
        . "    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n"
        . "    <link href=\"" . htmlspecialchars($fontsUrl, ENT_QUOTES) . "\" rel=\"stylesheet\">\n"
        . "    <link rel=\"stylesheet\" href=\"/assets/css/fontawesome.min.css\">\n"
        . "    <link rel=\"stylesheet\" href=\"/assets/css/tb-frontend.css\">\n"
        . "    <link rel=\"stylesheet\" href=\"<?= \$themePath ?>/assets/css/style.css\">\n"
        . "    <style>\n<?= \$themeCssVariables ?>\n<?= generate_studio_css_overrides() ?>\n    </style>\n"
        . "</head>\n"
        . "<body class=\"<?= esc(get_body_class() ?? '') ?><?= \$isTbPage ? ' tb-page' : '' ?>\">\n\n"
        . "<?php if (\$showHeader): ?>\n"
        . $headerHtml . "\n"
        . "<?php endif; ?>\n\n"
        . "<?php if (\$isTbPage): ?>\n"
        . "    <?= \$content ?? '' ?>\n"
        . "<?php else: ?>\n"
        . "    <main><?= \$content ?? '' ?></main>\n"
        . "<?php endif; ?>\n\n"
        . "<?php if (\$showFooter): ?>\n"
        . $footerHtml . "\n"
        . "<?php endif; ?>\n\n"
        . "<script src=\"<?= \$themePath ?>/assets/js/main.js\"></script>\n"
        . "</body>\n</html>\n";
    }

    /**
     * Standard page template
     */
    public function pagePhp(): string
    {
        return <<<'PHP'
<section class="page-hero">
    <div class="page-hero-overlay"></div>
    <div class="container">
        <h1 class="page-hero-title"><?= esc($page['title']) ?></h1>
        <div class="page-breadcrumb">
            <a href="/">Home</a>
            <span class="breadcrumb-sep"><i class="fas fa-chevron-right"></i></span>
            <span><?= esc($page['title']) ?></span>
        </div>
    </div>
</section>

<section class="page-content-section">
    <div class="container container-narrow">
        <?php if (!empty($page['featured_image'])): ?>
        <div class="page-featured-image">
            <img src="<?= esc($page['featured_image']) ?>" alt="<?= esc($page['title']) ?>">
        </div>
        <?php endif; ?>

        <div class="prose">
            <?= $page['content'] ?>
        </div>
    </div>
</section>
PHP;
    }

    /**
     * Single article template
     */
    public function articlePhp(): string
    {
        return <<<'PHP'
<section class="page-hero">
    <div class="page-hero-overlay"></div>
    <div class="container">
        <h1 class="page-hero-title"><?= esc($article['title']) ?></h1>
        <div class="page-breadcrumb">
            <a href="/">Home</a>
            <span class="breadcrumb-sep"><i class="fas fa-chevron-right"></i></span>
            <a href="/articles">Articles</a>
            <span class="breadcrumb-sep"><i class="fas fa-chevron-right"></i></span>
            <span><?= esc($article['title']) ?></span>
        </div>
    </div>
</section>

<section class="page-content-section">
    <div class="container container-narrow">
        <div class="article-meta">
            <?php if (!empty($article['category_name'])): ?>
            <span class="article-category"><?= esc($article['category_name']) ?></span>
            <?php endif; ?>
            <span class="article-date"><i class="far fa-calendar"></i> <?= date('M j, Y', strtotime($article['published_at'] ?? $article['created_at'])) ?></span>
            <?php if (!empty($article['views'])): ?>
            <span class="article-views"><i class="far fa-eye"></i> <?= number_format($article['views']) ?> views</span>
            <?php endif; ?>
        </div>

        <?php if (!empty($article['featured_image'])): ?>
        <div class="page-featured-image">
            <img src="<?= esc($article['featured_image']) ?>" alt="<?= esc($article['title']) ?>">
        </div>
        <?php endif; ?>

        <div class="prose">
            <?= $article['content'] ?>
        </div>

        <div class="article-back">
            <a href="/articles" class="btn btn-outline"><i class="fas fa-arrow-left"></i> Back to Articles</a>
        </div>
    </div>
</section>
PHP;
    }

    /**
     * Articles listing template
     */
    public function articlesPhp(): string
    {
        return <<<'PHP'
<section class="page-hero">
    <div class="page-hero-overlay"></div>
    <div class="container">
        <h1 class="page-hero-title"><?= esc(theme_get('articles.title', 'Articles')) ?></h1>
        <div class="page-breadcrumb">
            <a href="/">Home</a>
            <span class="breadcrumb-sep"><i class="fas fa-chevron-right"></i></span>
            <span>Articles</span>
        </div>
    </div>
</section>

<section class="section">
    <div class="container">
        <div class="articles-layout">
            <div class="articles-main">
                <?php if (!empty($articles)): ?>
                <div class="articles-grid">
                    <?php foreach ($articles as $a): ?>
                    <a href="/article/<?= esc($a['slug']) ?>" class="article-card" data-animate>
                        <div class="article-card-img">
                            <?php if (!empty($a['featured_image'])): ?>
                            <img src="<?= esc($a['featured_image']) ?>" alt="<?= esc($a['title']) ?>">
                            <?php else: ?>
                            <div class="img-placeholder"><i class="fas fa-newspaper"></i></div>
                            <?php endif; ?>
                            <?php if (!empty($a['category_name'])): ?>
                            <span class="article-card-tag"><?= esc($a['category_name']) ?></span>
                            <?php endif; ?>
                        </div>
                        <div class="article-card-body">
                            <h3><?= esc($a['title']) ?></h3>
                            <span class="article-card-date"><?= date('M j, Y', strtotime($a['published_at'] ?? $a['created_at'])) ?></span>
                            <p>
                                <?php if (!empty($a['excerpt'])): ?>
                                    <?= esc(mb_strimwidth(strip_tags($a['excerpt']), 0, 120, '...')) ?>
                                <?php else: ?>
                                    <?= esc(mb_strimwidth(strip_tags($a['content']), 0, 120, '...')) ?>
                                <?php endif; ?>
                            </p>
                        </div>
                    </a>
                    <?php endforeach; ?>
                </div>

                <?php if ($totalPages > 1): ?>
                <div class="pagination">
                    <?php if ($currentPage > 1): ?>
                    <a href="/articles?page=<?= $currentPage - 1 ?>" class="btn btn-outline"><i class="fas fa-chevron-left"></i> Previous</a>
                    <?php endif; ?>
                    <span class="pagination-info">Page <?= $currentPage ?> of <?= $totalPages ?></span>
                    <?php if ($currentPage < $totalPages): ?>
                    <a href="/articles?page=<?= $currentPage + 1 ?>" class="btn btn-outline">Next <i class="fas fa-chevron-right"></i></a>
                    <?php endif; ?>
                </div>
                <?php endif; ?>

                <?php else: ?>
                <div class="empty-state">
                    <h2>No articles yet</h2>
                    <p>Check back soon for new content.</p>
                </div>
                <?php endif; ?>
            </div>

            <?php if (!empty($categories)): ?>
            <aside class="articles-sidebar">
                <div class="sidebar-widget">
                    <h4>Categories</h4>
                    <div class="category-list">
                        <?php foreach ($categories as $cat): ?>
                        <a href="/articles?category=<?= esc($cat['slug']) ?>" class="category-item">
                            <span><?= esc($cat['name']) ?></span>
                            <span class="category-count"><?= (int)($cat['article_count'] ?? 0) ?></span>
                        </a>
                        <?php endforeach; ?>
                    </div>
                </div>
            </aside>
            <?php endif; ?>
        </div>
    </div>
</section>
PHP;
    }

    /**
     * 404 error page template
     */
    public function errorPhp(): string
    {
        return <<<'PHP'
<section class="error-section">
    <div class="error-content">
        <span class="error-code">404</span>
        <h1 class="error-title">Page Not Found</h1>
        <p class="error-text">The page you're looking for doesn't exist or has been moved.</p>
        <div class="error-actions">
            <a href="/" class="btn btn-primary">Go Home</a>
            <a href="/articles" class="btn btn-outline">Browse Articles</a>
        </div>
    </div>
</section>
PHP;
    }

    /**
     * Standard main.js
     */
    public function mainJs(): string
    {
        return <<<'JS'
/**
 * AI-Generated Theme — Main JavaScript
 * Mobile menu, header scroll, animations
 */
document.addEventListener('DOMContentLoaded', function () {

    /* ── Header scroll effect ── */
    const header = document.getElementById('siteHeader');
    if (header) {
        let lastScroll = 0;
        const scrollThreshold = 80;

        function handleScroll() {
            const currentScroll = window.pageYOffset;
            if (currentScroll > scrollThreshold) {
                header.classList.add('header-scrolled');
            } else {
                header.classList.remove('header-scrolled');
            }
            lastScroll = currentScroll;
        }

        window.addEventListener('scroll', handleScroll, { passive: true });
        handleScroll();
    }

    /* ── Mobile menu toggle ── */
    const mobileToggle = document.getElementById('mobileToggle');
    const headerNav = document.getElementById('headerNav');
    const mobileOverlay = document.getElementById('mobileOverlay');

    if (mobileToggle && headerNav) {
        mobileToggle.addEventListener('click', function () {
            headerNav.classList.toggle('nav-open');
            mobileToggle.classList.toggle('toggle-active');
            document.body.classList.toggle('menu-open');
            if (mobileOverlay) mobileOverlay.classList.toggle('overlay-active');
        });

        if (mobileOverlay) {
            mobileOverlay.addEventListener('click', function () {
                headerNav.classList.remove('nav-open');
                mobileToggle.classList.remove('toggle-active');
                document.body.classList.remove('menu-open');
                mobileOverlay.classList.remove('overlay-active');
            });
        }

        headerNav.querySelectorAll('.nav-link').forEach(function (link) {
            link.addEventListener('click', function () {
                headerNav.classList.remove('nav-open');
                mobileToggle.classList.remove('toggle-active');
                document.body.classList.remove('menu-open');
                if (mobileOverlay) mobileOverlay.classList.remove('overlay-active');
            });
        });
    }

    /* ── Smooth scroll for anchor links ── */
    document.querySelectorAll('a[href^="#"]').forEach(function (anchor) {
        anchor.addEventListener('click', function (e) {
            const target = document.querySelector(this.getAttribute('href'));
            if (target) {
                e.preventDefault();
                const headerHeight = header ? header.offsetHeight : 0;
                const targetPosition = target.getBoundingClientRect().top + window.pageYOffset - headerHeight;
                window.scrollTo({ top: targetPosition, behavior: 'smooth' });
            }
        });
    });

    /* ── Scroll-triggered animations ── */
    const animatedElements = document.querySelectorAll('[data-animate]');

    if (animatedElements.length > 0 && 'IntersectionObserver' in window) {
        const observer = new IntersectionObserver(function (entries) {
            entries.forEach(function (entry) {
                if (entry.isIntersecting) {
                    entry.target.classList.add('animated');
                    observer.unobserve(entry.target);
                }
            });
        }, { threshold: 0.15, rootMargin: '0px 0px -40px 0px' });

        animatedElements.forEach(function (el) {
            observer.observe(el);
        });
    }

    /* ── Parallax effect on hero ── */
    const heroBg = document.querySelector('.hero-bg, .hero__bg');
    if (heroBg) {
        window.addEventListener('scroll', function () {
            const scrolled = window.pageYOffset;
            heroBg.style.transform = 'translateY(' + (scrolled * 0.4) + 'px)';
        }, { passive: true });
    }

});
JS;
    }
}
