<?php
/**
 * AI-Generated Theme Layout
 * Generated by AI Theme Builder
 */

if (!defined('CMS_ROOT')) define('CMS_ROOT', dirname(__DIR__, 2));
if (!defined('CMS_APP')) define('CMS_APP', CMS_ROOT . '/app');

require_once CMS_APP . '/helpers/functions.php';

if (file_exists(CMS_ROOT . '/includes/helpers/menu.php')) {
    require_once CMS_ROOT . '/includes/helpers/menu.php';
}

$jtbBootPath = CMS_ROOT . '/plugins/jessie-theme-builder/includes/jtb-frontend-boot.php';
if (file_exists($jtbBootPath)) require_once $jtbBootPath;

$themeConfig = get_theme_config();
$themeOptions = $themeConfig['options'] ?? [];
$showHeader = $themeOptions['show_header'] ?? true;
$showFooter = $themeOptions['show_footer'] ?? true;

$siteName = theme_get('brand.site_name', get_site_name());
$siteLogo = theme_get('brand.logo', get_site_logo());
$tsLogo = theme_get('brand.logo') ?: $siteLogo;

$pageData = $page ?? [];
if (!empty($title) && empty($pageData['title'])) $pageData['title'] = $title;
$isTbPage = !empty($page['is_tb_page']);

$themeCssVariables = generate_theme_css_variables($themeConfig);
$themePath = '/themes/' . basename(__DIR__);
?><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?= render_seo_meta($pageData) ?>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&amp;family=Source+Sans+Pro:wght@400;600;700&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/assets/css/fontawesome.min.css">
    <link rel="stylesheet" href="/assets/css/tb-frontend.css">
    <link rel="stylesheet" href="<?= $themePath ?>/assets/css/style.css">
    <style>
<?= $themeCssVariables ?>
<?= generate_studio_css_overrides() ?>
    </style>
<?= function_exists("theme_render_favicon") ? theme_render_favicon() : "" ?>
<?= function_exists("theme_render_og_image") ? theme_render_og_image() : "" ?>
</head>
<body class="<?= esc(get_body_class() ?? '') ?><?= $isTbPage ? ' tb-page' : '' ?>">
<?= function_exists("theme_render_announcement_bar") ? theme_render_announcement_bar() : "" ?>

<?php if ($showHeader): ?>
<header class="site-header" id="siteHeader">
    <div class="header-container">
        <a href="/" class="header-logo" data-ts="brand.logo">
            <?php if ($tsLogo): ?>
                <img src="<?= esc($tsLogo) ?>" alt="<?= esc(theme_get('brand.site_name', $siteName)) ?>">
            <?php else: ?>
                <span class="logo-text" data-ts="brand.site_name"><?= esc(theme_get('brand.site_name', $siteName)) ?></span>
            <?php endif; ?>
        </a>
        <nav class="header-nav" id="headerNav">
            <?= render_menu('header', ['class' => 'nav-links', 'link_class' => 'nav-link', 'wrap' => false]) ?>
        </nav>
        <a href="<?= esc(theme_get('header.cta_link', '#reservations')) ?>"
           class="header-cta"
           data-ts="header.cta_text"
           data-ts-href="header.cta_link">
            <?= esc(theme_get('header.cta_text', 'RESERVE A TABLE')) ?>
        </a>
        <button class="mobile-toggle" id="mobileToggle" aria-label="Menu">
            <span></span><span></span><span></span>
        </button>
    </div>
</header>
<div class="mobile-overlay" id="mobileOverlay"></div>
<div class="mobile-overlay" id="mobileOverlay"></div>
<?php endif; ?>

<?php if ($isTbPage): ?>
    <?= $content ?? '' ?>
<?php else: ?>
    <main><?= $content ?? '' ?></main>
<?php endif; ?>

<?php if ($showFooter): ?>
<footer class="site-footer">
    <div class="footer-top">
        <div class="container">
            <div class="footer-grid">
                <div class="footer-brand">
                    <a href="/" class="footer-logo" data-ts="brand.logo">
                        <?php if ($tsLogo): ?>
                            <img src="<?= esc($tsLogo) ?>" alt="<?= esc(theme_get('brand.site_name', $siteName)) ?>">
                        <?php else: ?>
                            <span class="logo-text" data-ts="brand.site_name"><?= esc(theme_get('brand.site_name', $siteName)) ?></span>
                        <?php endif; ?>
                    </a>
                    <p class="footer-tagline" data-ts="footer.description">
                        <?= esc(theme_get('footer.description', 'Where fire meets flavor. An unforgettable dining experience crafted with passion and precision.')) ?>
                    </p>
                    <div class="footer-social">
                        <a href="#" aria-label="Facebook"><i class="fab fa-facebook-f"></i></a>
                        <a href="#" aria-label="Instagram"><i class="fab fa-instagram"></i></a>
                        <a href="#" aria-label="TripAdvisor"><i class="fab fa-tripadvisor"></i></a>
                        <a href="#" aria-label="Yelp"><i class="fab fa-yelp"></i></a>
                    </div>
                </div>
                <div class="footer-nav">
                    <h4>Explore</h4>
                    <?= render_menu('footer', ['class' => 'footer-links', 'link_class' => 'footer-link', 'wrap' => false]) ?>
                </div>
                <div class="footer-contact">
                    <h4>Contact</h4>
                    <ul class="contact-list">
                        <li>
                            <i class="fas fa-map-marker-alt"></i>
                            <span>247 Fireside Lane<br>Downtown District</span>
                        </li>
                        <li>
                            <i class="fas fa-phone"></i>
                            <a href="tel:+15551234567">(555) 123-4567</a>
                        </li>
                        <li>
                            <i class="fas fa-envelope"></i>
                            <a href="mailto:hello@emberandoak.com">hello@emberandoak.com</a>
                        </li>
                    </ul>
                </div>
                <div class="footer-hours">
                    <h4>Hours</h4>
                    <ul class="hours-list">
                        <li>
                            <span class="day">Monday - Thursday</span>
                            <span class="time">5:00 PM - 10:00 PM</span>
                        </li>
                        <li>
                            <span class="day">Friday - Saturday</span>
                            <span class="time">5:00 PM - 11:00 PM</span>
                        </li>
                        <li>
                            <span class="day">Sunday</span>
                            <span class="time">4:00 PM - 9:00 PM</span>
                        </li>
                    </ul>
                    <div class="ember-accent">
                        <i class="fas fa-fire"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="container">
            <p data-ts="footer.copyright">
                <?= theme_get('footer.copyright') ? esc(theme_get('footer.copyright')) : '&copy; ' . date('Y') . ' ' . esc(theme_get('brand.site_name', $siteName)) . '. All rights reserved.' ?>
            </p>
        </div>
    </div>
</footer>
<?php endif; ?>

<script src="<?= $themePath ?>/assets/js/main.js"></script>
</body>
</html>