<?php
/**
 * AI-Generated Theme Layout
 * Generated by AI Theme Builder
 */

if (!defined('CMS_ROOT')) define('CMS_ROOT', dirname(__DIR__, 2));
if (!defined('CMS_APP')) define('CMS_APP', CMS_ROOT . '/app');

require_once CMS_APP . '/helpers/functions.php';

if (file_exists(CMS_ROOT . '/includes/helpers/menu.php')) {
    require_once CMS_ROOT . '/includes/helpers/menu.php';
}

$jtbBootPath = CMS_ROOT . '/plugins/jessie-theme-builder/includes/jtb-frontend-boot.php';
if (file_exists($jtbBootPath)) require_once $jtbBootPath;

$themeConfig = get_theme_config();
$themeOptions = $themeConfig['options'] ?? [];
$showHeader = $themeOptions['show_header'] ?? true;
$showFooter = $themeOptions['show_footer'] ?? true;

$siteName = theme_get('brand.site_name', get_site_name());
$siteLogo = theme_get('brand.logo', get_site_logo());
$tsLogo = theme_get('brand.logo') ?: $siteLogo;

$pageData = $page ?? [];
if (!empty($title) && empty($pageData['title'])) $pageData['title'] = $title;
$isTbPage = !empty($page['is_tb_page']);

$themeCssVariables = generate_theme_css_variables($themeConfig);
$themePath = '/themes/' . basename(__DIR__);
?><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?= render_seo_meta($pageData) ?>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Mulish:wght@400;700&amp;family=Merriweather:wght@400&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/assets/css/fontawesome.min.css">
    <link rel="stylesheet" href="/assets/css/tb-frontend.css">
    <link rel="stylesheet" href="<?= $themePath ?>/assets/css/style.css">
    <style>
<?= $themeCssVariables ?>
<?= generate_studio_css_overrides() ?>
    </style>
<?= function_exists("theme_render_favicon") ? theme_render_favicon() : "" ?>
<?= function_exists("theme_render_og_image") ? theme_render_og_image() : "" ?>
</head>
<body class="<?= esc(get_body_class() ?? '') ?><?= $isTbPage ? ' tb-page' : '' ?>">
<?= function_exists("theme_render_announcement_bar") ? theme_render_announcement_bar() : "" ?>

<?php if ($showHeader): ?>
<a href="#main-content" class="skip-nav">Skip to content</a>
<header id="siteHeader" class="nf-header">
    <!-- Top Bar -->
    <div class="nf-top-bar">
        <div class="nf-container">
            <div class="nf-top-bar__inner">
                <div class="nf-top-bar__info">
                    <?php if (theme_get('header.phone')): ?>
                    <a href="tel:<?= esc(preg_replace('/[^0-9+]/', '', theme_get('header.phone'))) ?>" class="nf-top-bar__link" data-ts="header.phone">
                        <i class="fas fa-phone-alt"></i>
                        <span><?= esc(theme_get('header.phone')) ?></span>
                    </a>
                    <?php endif; ?>
                    <?php if (theme_get('header.email')): ?>
                    <a href="mailto:<?= esc(theme_get('header.email')) ?>" class="nf-top-bar__link" data-ts="header.email">
                        <i class="fas fa-envelope"></i>
                        <span><?= esc(theme_get('header.email')) ?></span>
                    </a>
                    <?php endif; ?>
                </div>
                <div class="nf-top-bar__social">
                    <?php if (theme_get('footer.facebook')): ?>
                    <a href="<?= esc(theme_get('footer.facebook')) ?>" target="_blank" class="nf-social-icon" aria-label="Facebook">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <?php endif; ?>
                    <?php if (theme_get('footer.instagram')): ?>
                    <a href="<?= esc(theme_get('footer.instagram')) ?>" target="_blank" class="nf-social-icon" aria-label="Instagram">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <?php endif; ?>
                    <?php if (theme_get('footer.linkedin')): ?>
                    <a href="<?= esc(theme_get('footer.linkedin')) ?>" target="_blank" class="nf-social-icon" aria-label="LinkedIn">
                        <i class="fab fa-linkedin-in"></i>
                    </a>
                    <?php endif; ?>
                    <?php if (theme_get('footer.twitter')): ?>
                    <a href="<?= esc(theme_get('footer.twitter')) ?>" target="_blank" class="nf-social-icon" aria-label="Twitter">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>

    <!-- Main Bar -->
    <div class="nf-main-bar">
        <div class="nf-container">
            <div class="nf-main-bar__inner">
                <!-- Logo -->
                <a href="/" class="nf-brand">
                    <?php if ($tsLogo): ?>
                        <img src="<?= esc($tsLogo) ?>" alt="<?= esc(theme_get('brand.site_name', $siteName)) ?>" height="<?= esc(theme_get('header.logoSize', '36')) ?>">
                    <?php else: ?>
                        <span class="nf-brand__text" data-ts="brand.site_name"><?= esc(theme_get('brand.site_name', $siteName)) ?></span>
                    <?php endif; ?>
                </a>

                <!-- Navigation -->
                <nav id="headerNav" class="nf-nav">
                    <?= render_menu('header', ['class' => 'nf-nav__list', 'link_class' => 'nf-nav__link', 'wrap' => false]) ?>
                </nav>

                <!-- Header Actions -->
                <div class="nf-header-actions">
                    <button class="nf-search-toggle" aria-label="Search">
                        <i class="fas fa-search"></i>
                    </button>
                    <a href="<?= esc(theme_get('header.cta_link', '#contact')) ?>" class="nf-cta-btn" data-ts="header.cta_text" data-ts-href="header.cta_link">
                        <?= esc(theme_get('header.cta_text', 'Open Account')) ?>
                    </a>
                    <button class="dark-mode-toggle" data-dark-toggle aria-label="Toggle dark mode" style="background:none;border:none;cursor:pointer;font-size:1.25rem;padding:4px 8px">🌙</button>
    <button id="mobileToggle" class="nf-hamburger" aria-label="Menu">
                        <span></span>
                        <span></span>
                        <span></span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="mobile-overlay" id="mobileOverlay"></div>
<?php endif; ?>

<?php if ($isTbPage): ?>
    <?= $content ?? '' ?>
<?php else: ?>
    <main id="main-content"><?= $content ?? '' ?></main>
<?php endif; ?>

<?php if ($showFooter): ?>
<footer class="nf-footer">
    <!-- Newsletter Section -->
    <div class="nf-newsletter">
        <div class="nf-container">
            <div class="nf-newsletter__inner">
                <div class="nf-newsletter__content">
                    <h3 class="nf-newsletter__title" data-ts="footer.newsletter_title">Stay Ahead with Financial Insights</h3>
                    <p class="nf-newsletter__desc" data-ts="footer.newsletter_desc">Get weekly tips on managing freelance finances, tax updates, and AI tools.</p>
                </div>
                <form class="nf-newsletter__form">
                    <div class="nf-newsletter__input-group">
                        <input type="email" placeholder="Your professional email" class="nf-newsletter__input" required>
                        <button type="submit" class="nf-newsletter__btn">
                            <span>Subscribe</span>
                            <i class="fas fa-arrow-right"></i>
                        </button>
                    </div>
                    <p class="nf-newsletter__note">By subscribing, you agree to our Privacy Policy. No spam.</p>
                </form>
            </div>
        </div>
    </div>

    <!-- Main Footer Content -->
    <div class="nf-footer__main">
        <div class="nf-container">
            <div class="nf-footer__grid">
                <!-- Brand Column -->
                <div class="nf-footer__brand">
                    <a href="/" class="nf-footer__logo">
                        <?php if ($tsLogo): ?>
                            <img src="<?= esc($tsLogo) ?>" alt="<?= esc(theme_get('brand.site_name', $siteName)) ?>" height="40">
                        <?php else: ?>
                            <span class="nf-footer__logo-text" data-ts="brand.site_name"><?= esc(theme_get('brand.site_name', $siteName)) ?></span>
                        <?php endif; ?>
                    </a>
                    <p class="nf-footer__tagline" data-ts="footer.description">
                        <?= esc(theme_get('footer.description', 'AI-powered banking built for the modern freelancer. Instant invoicing, multi-currency accounts, and intelligent expense management.')) ?>
                    </p>
                    <div class="nf-footer__social">
                        <?php if (theme_get('footer.facebook')): ?>
                        <a href="<?= esc(theme_get('footer.facebook')) ?>" target="_blank" class="nf-footer__social-link" aria-label="Facebook">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                        <?php endif; ?>
                        <?php if (theme_get('footer.instagram')): ?>
                        <a href="<?= esc(theme_get('footer.instagram')) ?>" target="_blank" class="nf-footer__social-link" aria-label="Instagram">
                            <i class="fab fa-instagram"></i>
                        </a>
                        <?php endif; ?>
                        <?php if (theme_get('footer.linkedin')): ?>
                        <a href="<?= esc(theme_get('footer.linkedin')) ?>" target="_blank" class="nf-footer__social-link" aria-label="LinkedIn">
                            <i class="fab fa-linkedin-in"></i>
                        </a>
                        <?php endif; ?>
                        <?php if (theme_get('footer.twitter')): ?>
                        <a href="<?= esc(theme_get('footer.twitter')) ?>" target="_blank" class="nf-footer__social-link" aria-label="Twitter">
                            <i class="fab fa-twitter"></i>
                        </a>
                        <?php endif; ?>
                    </div>
                </div>

                <!-- Quick Links -->
                <div class="nf-footer__col">
                    <h4 class="nf-footer__heading" data-ts="footer.links_title">Platform</h4>
                    <?= render_menu('footer', ['class' => 'nf-footer__links', 'link_class' => 'nf-footer__link', 'wrap' => false]) ?>
                </div>

                <!-- Resources -->
                <div class="nf-footer__col">
                    <h4 class="nf-footer__heading" data-ts="footer.resources_title">Resources</h4>
                    <div class="nf-footer__links">
                        <a href="/blog" class="nf-footer__link">Freelancer Blog</a>
                        <a href="/help" class="nf-footer__link">Help Center</a>
                        <a href="/security" class="nf-footer__link">Security</a>
                        <a href="/pricing" class="nf-footer__link">Pricing</a>
                        <a href="/api" class="nf-footer__link">API for Developers</a>
                    </div>
                </div>

                <!-- Contact -->
                <div class="nf-footer__col">
                    <h4 class="nf-footer__heading" data-ts="footer.contact_title">Contact</h4>
                    <div class="nf-footer__contact">
                        <?php if (theme_get('footer.address')): ?>
                        <div class="nf-footer__contact-item">
                            <i class="fas fa-map-marker-alt"></i>
                            <span data-ts="footer.address"><?= esc(theme_get('footer.address', '123 Fintech Avenue, San Francisco, CA 94107')) ?></span>
                        </div>
                        <?php endif; ?>
                        <?php if (theme_get('footer.phone')): ?>
                        <div class="nf-footer__contact-item">
                            <i class="fas fa-phone-alt"></i>
                            <a href="tel:<?= esc(preg_replace('/[^0-9+]/', '', theme_get('footer.phone'))) ?>" data-ts="footer.phone"><?= esc(theme_get('footer.phone', '+1 (555) 123-4567')) ?></a>
                        </div>
                        <?php endif; ?>
                        <?php if (theme_get('footer.email')): ?>
                        <div class="nf-footer__contact-item">
                            <i class="fas fa-envelope"></i>
                            <a href="mailto:<?= esc(theme_get('footer.email')) ?>" data-ts="footer.email"><?= esc(theme_get('footer.email', 'support@nexusflow.com')) ?></a>
                        </div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Footer Bottom -->
    <div class="nf-footer__bottom">
        <div class="nf-container">
            <div class="nf-footer__bottom-inner">
                <p class="nf-footer__copyright" data-ts="footer.copyright">
                    <?= theme_get('footer.copyright') ? esc(theme_get('footer.copyright')) : '&copy; ' . date('Y') . ' ' . esc(theme_get('brand.site_name', $siteName)) . '. All rights reserved.' ?>
                </p>
                <div class="nf-footer__legal">
                    <a href="/privacy" class="nf-footer__legal-link">Privacy Policy</a>
                    <a href="/terms" class="nf-footer__legal-link">Terms of Service</a>
                    <a href="/cookies" class="nf-footer__legal-link">Cookie Policy</a>
                    <a href="/compliance" class="nf-footer__legal-link">Compliance</a>
                </div>
            </div>
        </div>
    </div>
</footer>
<?php endif; ?>

<script src="<?= $themePath ?>/assets/js/main.js"></script>
<?php if (function_exists('cms_ab_testing_widget')): echo cms_ab_testing_widget(); endif; ?>
<?php if (function_exists('ai_theme_chat_widget')): echo ai_theme_chat_widget(); endif; ?>
</body>
</html>