<?php
/**
 * AI-Generated Theme Layout
 * Generated by AI Theme Builder
 */

if (!defined('CMS_ROOT')) define('CMS_ROOT', dirname(__DIR__, 2));
if (!defined('CMS_APP')) define('CMS_APP', CMS_ROOT . '/app');

require_once CMS_APP . '/helpers/functions.php';

if (file_exists(CMS_ROOT . '/includes/helpers/menu.php')) {
    require_once CMS_ROOT . '/includes/helpers/menu.php';
}

$jtbBootPath = CMS_ROOT . '/plugins/jessie-theme-builder/includes/jtb-frontend-boot.php';
if (file_exists($jtbBootPath)) require_once $jtbBootPath;

$themeConfig = get_theme_config();
$themeOptions = $themeConfig['options'] ?? [];
$showHeader = $themeOptions['show_header'] ?? true;
$showFooter = $themeOptions['show_footer'] ?? true;

$siteName = theme_get('brand.site_name', get_site_name());
$siteLogo = theme_get('brand.logo', get_site_logo());
$tsLogo = theme_get('brand.logo') ?: $siteLogo;

$pageData = $page ?? [];
if (!empty($title) && empty($pageData['title'])) $pageData['title'] = $title;
$isTbPage = !empty($page['is_tb_page']);

$themeCssVariables = generate_theme_css_variables($themeConfig);
$themePath = '/themes/' . basename(__DIR__);
?><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?= render_seo_meta($pageData) ?>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Mulish:wght@400;600;700;800&amp;family=Merriweather:wght@400;500;700&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/assets/css/fontawesome.min.css">
    <link rel="stylesheet" href="/assets/css/tb-frontend.css">
    <link rel="stylesheet" href="<?= $themePath ?>/assets/css/style.css">
    <style>
<?= $themeCssVariables ?>
<?= generate_studio_css_overrides() ?>
    </style>
<?= function_exists("theme_render_favicon") ? theme_render_favicon() : "" ?>
<?= function_exists("theme_render_og_image") ? theme_render_og_image() : "" ?>
</head>
<body class="<?= esc(get_body_class() ?? '') ?><?= $isTbPage ? ' tb-page' : '' ?>">
<?= function_exists("theme_render_announcement_bar") ? theme_render_announcement_bar() : "" ?>

<?php if ($showHeader): ?>
<?php
$headerPhone = theme_get('header.phone', '');
$headerEmail = theme_get('header.email', '');
$ctaText = theme_get('header.cta_text', 'Start Climbing');
$ctaLink = theme_get('header.cta_link', '#contact');
$brandName = theme_get('brand.site_name', $siteName);
?>
<a href="#main-content" class="skip-nav">Skip to content</a>
<header id="siteHeader" class="sp-masthead">
    <div class="sp-masthead-brand">
        <a href="/" class="sp-logo-link" data-ts="brand.logo">
            <?php if ($tsLogo): ?>
                <img src="<?= esc($tsLogo) ?>" alt="<?= esc($brandName) ?>" class="sp-logo-img">
            <?php else: ?>
                <span class="sp-logo-text" data-ts="brand.site_name"><?= esc($brandName) ?></span>
            <?php endif; ?>
        </a>
    </div>
    <div class="sp-masthead-bar">
        <div class="sp-masthead-inner">
            <nav id="headerNav" class="sp-nav-strip">
                <?= render_menu('header', ['class' => 'sp-nav-list', 'link_class' => 'sp-nav-item', 'wrap' => false]) ?>
            </nav>
            <div class="sp-masthead-actions">
                <?php if ($headerPhone): ?>
                <a href="tel:<?= esc(preg_replace('/[^0-9+]/', '', $headerPhone)) ?>" class="sp-header-phone" data-ts="header.phone">
                    <i class="fas fa-phone-alt"></i>
                    <span><?= esc($headerPhone) ?></span>
                </a>
                <?php endif; ?>
                <a href="<?= esc($ctaLink) ?>" class="sp-header-cta" data-ts="header.cta_text" data-ts-href="header.cta_link">
                    <?= esc($ctaText) ?>
                </a>
            </div>
            <button class="dark-mode-toggle" data-dark-toggle aria-label="Toggle dark mode" style="background:none;border:none;cursor:pointer;font-size:1.25rem;padding:4px 8px">🌙</button>
    <button id="mobileToggle" class="sp-burger" aria-label="Menu">
                <span></span>
                <span></span>
                <span></span>
            </button>
        </div>
    </div>
</header>

<style>
.sp-masthead {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    z-index: 1000;
    transition: transform 0.4s cubic-bezier(0.4, 0, 0.2, 1);
}

.sp-masthead.header-hidden {
    transform: translateY(-100%);
}

.sp-masthead-brand {
    display: flex;
    justify-content: center;
    align-items: center;
    padding: 28px 20px 18px;
    background: transparent;
}

.sp-logo-link {
    text-decoration: none;
}

.sp-logo-img {
    height: 48px;
    width: auto;
}

.sp-logo-text {
    font-family: var(--font-heading);
    font-size: 2.8rem;
    font-weight: 800;
    color: var(--color-text);
    letter-spacing: -0.02em;
    text-transform: uppercase;
}

.sp-masthead-bar {
    border-top: 1px solid var(--color-border);
    border-bottom: 1px solid var(--color-border);
    background: rgba(13, 26, 31, 0.6);
    backdrop-filter: blur(16px);
    -webkit-backdrop-filter: blur(16px);
}

.sp-masthead-inner {
    max-width: var(--container-width);
    margin: 0 auto;
    padding: 0 24px;
    display: flex;
    align-items: center;
    justify-content: space-between;
    height: 52px;
}

.sp-nav-strip {
    flex: 1;
    display: flex;
    justify-content: center;
}

.sp-nav-list {
    display: flex;
    gap: 36px;
    list-style: none;
    margin: 0;
    padding: 0;
}

.sp-nav-item {
    font-family: var(--font-heading);
    font-size: 0.85rem;
    font-weight: 600;
    color: var(--color-text-muted);
    text-decoration: none;
    text-transform: uppercase;
    letter-spacing: 0.08em;
    padding: 16px 0;
    position: relative;
    transition: color var(--transition-speed) ease;
}

.sp-nav-item::after {
    content: '';
    position: absolute;
    bottom: 12px;
    left: 0;
    width: 0;
    height: 2px;
    background: var(--color-primary);
    transition: width var(--transition-speed) ease;
}

.sp-nav-item:hover,
.sp-nav-item.active {
    color: var(--color-text);
}

.sp-nav-item:hover::after,
.sp-nav-item.active::after {
    width: 100%;
}

.sp-masthead-actions {
    display: flex;
    align-items: center;
    gap: 20px;
}

.sp-header-phone {
    display: flex;
    align-items: center;
    gap: 8px;
    font-family: var(--font-heading);
    font-size: 0.85rem;
    font-weight: 600;
    color: var(--color-text-muted);
    text-decoration: none;
    transition: color var(--transition-speed) ease;
}

.sp-header-phone i {
    font-size: 0.75rem;
    color: var(--color-primary);
}

.sp-header-phone:hover {
    color: var(--color-primary);
}

.sp-header-cta {
    display: inline-flex;
    align-items: center;
    padding: 10px 22px;
    font-family: var(--font-heading);
    font-size: 0.8rem;
    font-weight: 700;
    color: var(--color-background);
    background: var(--color-primary);
    border-radius: var(--btn-radius);
    text-decoration: none;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    transition: all var(--transition-speed) ease;
}

.sp-header-cta:hover {
    background: var(--color-accent);
    transform: translateY(-2px);
}

.sp-burger {
    display: none;
    flex-direction: column;
    justify-content: center;
    gap: 5px;
    width: 32px;
    height: 32px;
    background: none;
    border: none;
    cursor: pointer;
    padding: 4px;
}

.sp-burger span {
    display: block;
    width: 100%;
    height: 2px;
    background: var(--color-text);
    border-radius: 2px;
    transition: all 0.3s ease;
}

/* Scrolled State */
.sp-masthead.header-scrolled .sp-masthead-brand {
    padding: 12px 20px 8px;
}

.sp-masthead.header-scrolled .sp-logo-text {
    font-size: 1.8rem;
}

.sp-masthead.header-scrolled .sp-logo-img {
    height: 36px;
}

.sp-masthead.header-scrolled .sp-masthead-bar {
    background: rgba(13, 26, 31, 0.95);
}

/* Mobile Styles */
@media (max-width: 1024px) {
    .sp-nav-list {
        gap: 24px;
    }
    
    .sp-header-phone {
        display: none;
    }
}

@media (max-width: 768px) {
    .sp-masthead-brand {
        padding: 20px 16px 14px;
    }
    
    .sp-logo-text {
        font-size: 2rem;
    }
    
    .sp-burger {
        display: flex;
    }
    
    .sp-nav-strip {
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background: var(--color-background);
        flex-direction: column;
        justify-content: center;
        align-items: center;
        opacity: 0;
        visibility: hidden;
        transition: all 0.4s ease;
    }
    
    body.nav-open .sp-nav-strip {
        opacity: 1;
        visibility: visible;
    }
    
    .sp-nav-list {
        flex-direction: column;
        align-items: center;
        gap: 8px;
    }
    
    .sp-nav-item {
        font-size: 1.5rem;
        padding: 12px 0;
        letter-spacing: 0.05em;
    }
    
    .sp-masthead-actions {
        position: relative;
        z-index: 10;
    }
    
    .sp-header-cta {
        display: none;
    }
    
    body.nav-open .sp-burger span:nth-child(1) {
        transform: rotate(45deg) translate(5px, 5px);
    }
    
    body.nav-open .sp-burger span:nth-child(2) {
        opacity: 0;
    }
    
    body.nav-open .sp-burger span:nth-child(3) {
        transform: rotate(-45deg) translate(5px, -5px);
    }
}
</style>
<div class="mobile-overlay" id="mobileOverlay"></div>
<?php endif; ?>

<?php if ($isTbPage): ?>
    <?= $content ?? '' ?>
<?php else: ?>
    <main id="main-content"><?= $content ?? '' ?></main>
<?php endif; ?>

<?php if ($showFooter): ?>
<?php
$footerDesc = theme_get('footer.description', 'Reach new heights at Summit Pulse. Indoor bouldering, auto-belay walls, expert coaching, and a community that pushes you to climb higher.');
$footerCopyright = theme_get('footer.copyright', '');
$footerAddress = theme_get('footer.address', '');
$footerPhone = theme_get('footer.phone', '');
$footerEmail = theme_get('footer.email', '');
$footerHours = theme_get('footer.hours', '');
$footerFacebook = theme_get('footer.facebook', '');
$footerInstagram = theme_get('footer.instagram', '');
$footerLinkedin = theme_get('footer.linkedin', '');
$footerYoutube = theme_get('footer.youtube', '');
?>
<footer class="sp-footer">
    <div class="sp-footer-wave">
        <svg viewBox="0 0 1440 120" preserveAspectRatio="none">
            <path d="M0,60 C360,120 720,0 1080,60 C1260,90 1380,30 1440,60 L1440,120 L0,120 Z" fill="var(--color-surface)"/>
        </svg>
    </div>
    
    <div class="sp-footer-main">
        <div class="sp-footer-container">
            <!-- Featured Row -->
            <div class="sp-footer-featured">
                <div class="sp-footer-brand-col">
                    <a href="/" class="sp-footer-logo" data-ts="brand.logo">
                        <?php if ($tsLogo): ?>
                            <img src="<?= esc($tsLogo) ?>" alt="<?= esc(theme_get('brand.site_name', $siteName)) ?>" height="42">
                        <?php else: ?>
                            <span class="sp-footer-logo-text" data-ts="brand.site_name"><?= esc(theme_get('brand.site_name', $siteName)) ?></span>
                        <?php endif; ?>
                    </a>
                    <p class="sp-footer-about" data-ts="footer.description"><?= esc($footerDesc) ?></p>
                    
                    <div class="sp-footer-social">
                        <?php if ($footerFacebook): ?>
                        <a href="<?= esc($footerFacebook) ?>" target="_blank" rel="noopener" aria-label="Facebook"><i class="fab fa-facebook-f"></i></a>
                        <?php endif; ?>
                        <?php if ($footerInstagram): ?>
                        <a href="<?= esc($footerInstagram) ?>" target="_blank" rel="noopener" aria-label="Instagram"><i class="fab fa-instagram"></i></a>
                        <?php endif; ?>
                        <?php if ($footerLinkedin): ?>
                        <a href="<?= esc($footerLinkedin) ?>" target="_blank" rel="noopener" aria-label="LinkedIn"><i class="fab fa-linkedin-in"></i></a>
                        <?php endif; ?>
                        <?php if ($footerYoutube): ?>
                        <a href="<?= esc($footerYoutube) ?>" target="_blank" rel="noopener" aria-label="YouTube"><i class="fab fa-youtube"></i></a>
                        <?php endif; ?>
                    </div>
                </div>
                
                <div class="sp-footer-links-col">
                    <h4 class="sp-footer-heading">Quick Links</h4>
                    <?= render_menu('footer', ['class' => 'sp-footer-menu', 'link_class' => 'sp-footer-link', 'wrap' => false]) ?>
                </div>
                
                <div class="sp-footer-contact-col">
                    <h4 class="sp-footer-heading">Contact Us</h4>
                    <div class="sp-footer-contact-list">
                        <?php if ($footerAddress): ?>
                        <div class="sp-footer-contact-item">
                            <i class="fas fa-map-marker-alt"></i>
                            <span data-ts="footer.address"><?= esc($footerAddress) ?></span>
                        </div>
                        <?php endif; ?>
                        <?php if ($footerPhone): ?>
                        <div class="sp-footer-contact-item">
                            <i class="fas fa-phone-alt"></i>
                            <a href="tel:<?= esc(preg_replace('/[^0-9+]/', '', $footerPhone)) ?>" data-ts="footer.phone"><?= esc($footerPhone) ?></a>
                        </div>
                        <?php endif; ?>
                        <?php if ($footerEmail): ?>
                        <div class="sp-footer-contact-item">
                            <i class="fas fa-envelope"></i>
                            <a href="mailto:<?= esc($footerEmail) ?>" data-ts="footer.email"><?= esc($footerEmail) ?></a>
                        </div>
                        <?php endif; ?>
                        <?php if ($footerHours): ?>
                        <div class="sp-footer-contact-item">
                            <i class="fas fa-clock"></i>
                            <span data-ts="footer.hours"><?= esc($footerHours) ?></span>
                        </div>
                        <?php endif; ?>
                    </div>
                </div>
                
                <div class="sp-footer-newsletter-col">
                    <h4 class="sp-footer-heading">Stay Connected</h4>
                    <p class="sp-footer-newsletter-text">Get climbing tips, event updates, and exclusive member offers.</p>
                    <form class="sp-footer-newsletter-form">
                        <input type="email" placeholder="Your email address" class="sp-footer-input" required>
                        <button type="submit" class="sp-footer-submit">
                            <i class="fas fa-paper-plane"></i>
                        </button>
                    </form>
                </div>
            </div>
            
            <!-- Tags Row -->
            <div class="sp-footer-tags">
                <span class="sp-tag">Bouldering</span>
                <span class="sp-tag">Auto-Belay</span>
                <span class="sp-tag">Youth Programs</span>
                <span class="sp-tag">Training Boards</span>
                <span class="sp-tag">Protein Café</span>
                <span class="sp-tag">Coaching</span>
                <span class="sp-tag">Memberships</span>
                <span class="sp-tag">Day Passes</span>
            </div>
        </div>
    </div>
    
    <div class="sp-footer-bottom">
        <div class="sp-footer-container">
            <p class="sp-footer-copyright" data-ts="footer.copyright">
                <?= $footerCopyright ? esc($footerCopyright) : '&copy; ' . date('Y') . ' ' . esc(theme_get('brand.site_name', $siteName)) . '. All rights reserved.' ?>
            </p>
            <div class="sp-footer-legal">
                <a href="/privacy">Privacy Policy</a>
                <a href="/terms">Terms of Service</a>
            </div>
        </div>
    </div>
</footer>

<style>
.sp-footer {
    position: relative;
    background: var(--color-background);
}

.sp-footer-wave {
    position: relative;
    margin-bottom: -2px;
}

.sp-footer-wave svg {
    display: block;
    width: 100%;
    height: 80px;
}

.sp-footer-main {
    background: var(--color-surface);
    padding: 80px 0 50px;
}

.sp-footer-container {
    max-width: var(--container-width);
    margin: 0 auto;
    padding: 0 24px;
}

.sp-footer-featured {
    display: grid;
    grid-template-columns: 1.5fr 1fr 1fr 1.2fr;
    gap: 50px;
}

.sp-footer-logo {
    display: inline-block;
    text-decoration: none;
    margin-bottom: 20px;
}

.sp-footer-logo img {
    height: 42px;
    width: auto;
}

.sp-footer-logo-text {
    font-family: var(--font-heading);
    font-size: 1.8rem;
    font-weight: 800;
    color: var(--color-text);
    text-transform: uppercase;
    letter-spacing: -0.01em;
}

.sp-footer-about {
    font-size: 0.95rem;
    line-height: 1.7;
    color: var(--color-text-muted);
    margin-bottom: 24px;
    max-width: 320px;
}

.sp-footer-social {
    display: flex;
    gap: 12px;
}

.sp-footer-social a {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 40px;
    height: 40px;
    background: var(--color-border);
    border-radius: 50%;
    color: var(--color-text-muted);
    text-decoration: none;
    transition: all var(--transition-speed) ease;
}

.sp-footer-social a:hover {
    background: var(--color-primary);
    color: var(--color-background);
    transform: translateY(-3px);
}

.sp-footer-heading {
    font-family: var(--font-heading);
    font-size: 0.9rem;
    font-weight: 700;
    color: var(--color-text);
    text-transform: uppercase;
    letter-spacing: 0.1em;
    margin-bottom: 24px;
    position: relative;
    padding-bottom: 12px;
}

.sp-footer-heading::after {
    content: '';
    position: absolute;
    bottom: 0;
    left: 0;
    width: 30px;
    height: 2px;
    background: linear-gradient(90deg, var(--color-primary), var(--color-secondary));
}

.sp-footer-menu {
    list-style: none;
    padding: 0;
    margin: 0;
    display: flex;
    flex-direction: column;
    gap: 12px;
}

.sp-footer-link {
    font-size: 0.95rem;
    color: var(--color-text-muted);
    text-decoration: none;
    transition: color var(--transition-speed) ease;
}

.sp-footer-link:hover {
    color: var(--color-primary);
}

.sp-footer-contact-list {
    display: flex;
    flex-direction: column;
    gap: 16px;
}

.sp-footer-contact-item {
    display: flex;
    align-items: flex-start;
    gap: 12px;
    font-size: 0.95rem;
    color: var(--color-text-muted);
}

.sp-footer-contact-item i {
    color: var(--color-primary);
    font-size: 0.9rem;
    margin-top: 3px;
    width: 16px;
}

.sp-footer-contact-item a {
    color: var(--color-text-muted);
    text-decoration: none;
    transition: color var(--transition-speed) ease;
}

.sp-footer-contact-item a:hover {
    color: var(--color-primary);
}

.sp-footer-newsletter-text {
    font-size: 0.95rem;
    color: var(--color-text-muted);
    margin-bottom: 20px;
    line-height: 1.6;
}

.sp-footer-newsletter-form {
    display: flex;
    gap: 0;
}

.sp-footer-input {
    flex: 1;
    padding: 14px 18px;
    font-size: 0.9rem;
    color: var(--color-text);
    background: var(--color-background);
    border: 1px solid var(--color-border);
    border-right: none;
    border-radius: var(--btn-radius) 0 0 var(--btn-radius);
    outline: none;
    transition: border-color var(--transition-speed) ease;
}

.sp-footer-input::placeholder {
    color: var(--color-text-muted);
}

.sp-footer-input:focus {
    border-color: var(--color-primary);
}

.sp-footer-submit {
    padding: 14px 20px;
    background: var(--color-primary);
    color: var(--color-background);
    border: none;
    border-radius: 0 var(--btn-radius) var(--btn-radius) 0;
    cursor: pointer;
    transition: background var(--transition-speed) ease;
}

.sp-footer-submit:hover {
    background: var(--color-accent);
}

.sp-footer-tags {
    display: flex;
    flex-wrap: wrap;
    gap: 10px;
    margin-top: 50px;
    padding-top: 40px;
    border-top: 1px solid var(--color-border);
    justify-content: center;
}

.sp-tag {
    display: inline-block;
    padding: 8px 16px;
    font-family: var(--font-heading);
    font-size: 0.75rem;
    font-weight: 600;
    color: var(--color-text-muted);
    background: var(--color-background);
    border: 1px solid var(--color-border);
    border-radius: 20px;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    transition: all var(--transition-speed) ease;
}

.sp-tag:hover {
    border-color: var(--color-primary);
    color: var(--color-primary);
}

.sp-footer-bottom {
    background: var(--color-background);
    padding: 24px 0;
    border-top: 1px solid var(--color-border);
}

.sp-footer-bottom .sp-footer-container {
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.sp-footer-copyright {
    font-size: 0.85rem;
    color: var(--color-text-muted);
}

.sp-footer-legal {
    display: flex;
    gap: 24px;
}

.sp-footer-legal a {
    font-size: 0.85rem;
    color: var(--color-text-muted);
    text-decoration: none;
    transition: color var(--transition-speed) ease;
}

.sp-footer-legal a:hover {
    color: var(--color-primary);
}

@media (max-width: 1024px) {
    .sp-footer-featured {
        grid-template-columns: 1fr 1fr;
        gap: 40px;
    }
}

@media (max-width: 768px) {
    .sp-footer-main {
        padding: 60px 0 40px;
    }
    
    .sp-footer-featured {
        grid-template-columns: 1fr;
        gap: 40px;
        text-align: center;
    }
    
    .sp-footer-about {
        max-width: 100%;
    }
    
    .sp-footer-social {
        justify-content: center;
    }
    
    .sp-footer-heading::after {
        left: 50%;
        transform: translateX(-50%);
    }
    
    .sp-footer-menu {
        align-items: center;
    }
    
    .sp-footer-contact-list {
        align-items: center;
    }
    
    .sp-footer-contact-item {
        justify-content: center;
    }
    
    .sp-footer-tags {
        margin-top: 40px;
        padding-top: 30px;
    }
    
    .sp-footer-bottom .sp-footer-container {
        flex-direction: column;
        gap: 16px;
        text-align: center;
    }
}
</style>
<?php endif; ?>

<script src="<?= $themePath ?>/assets/js/main.js"></script>
<?php if (function_exists('cms_ab_testing_widget')): echo cms_ab_testing_widget(); endif; ?>
<?php if (function_exists('ai_theme_chat_widget')): echo ai_theme_chat_widget(); endif; ?>
</body>
</html>