<?php
/**
 * AI-Generated Theme Layout
 * Generated by AI Theme Builder
 */

if (!defined('CMS_ROOT')) define('CMS_ROOT', dirname(__DIR__, 2));
if (!defined('CMS_APP')) define('CMS_APP', CMS_ROOT . '/app');

require_once CMS_APP . '/helpers/functions.php';

if (file_exists(CMS_ROOT . '/includes/helpers/menu.php')) {
    require_once CMS_ROOT . '/includes/helpers/menu.php';
}

$jtbBootPath = CMS_ROOT . '/plugins/jessie-theme-builder/includes/jtb-frontend-boot.php';
if (file_exists($jtbBootPath)) require_once $jtbBootPath;

$themeConfig = get_theme_config();
$themeOptions = $themeConfig['options'] ?? [];
$showHeader = $themeOptions['show_header'] ?? true;
$showFooter = $themeOptions['show_footer'] ?? true;

$siteName = theme_get('brand.site_name', get_site_name());
$siteLogo = theme_get('brand.logo', get_site_logo());
$tsLogo = theme_get('brand.logo') ?: $siteLogo;

$pageData = $page ?? [];
if (!empty($title) && empty($pageData['title'])) $pageData['title'] = $title;
$isTbPage = !empty($page['is_tb_page']);

$themeCssVariables = generate_theme_css_variables($themeConfig);
$themePath = '/themes/' . basename(__DIR__);
?><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?= render_seo_meta($pageData) ?>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;500;600;700&amp;family=Crimson+Pro:wght@300;400;500;600&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/assets/css/fontawesome.min.css">
    <link rel="stylesheet" href="/assets/css/tb-frontend.css">
    <link rel="stylesheet" href="<?= $themePath ?>/assets/css/style.css">
    <style>
<?= $themeCssVariables ?>
<?= generate_studio_css_overrides() ?>
    </style>
<?= function_exists("theme_render_favicon") ? theme_render_favicon() : "" ?>
<?= function_exists("theme_render_og_image") ? theme_render_og_image() : "" ?>
</head>
<body class="<?= esc(get_body_class() ?? '') ?><?= $isTbPage ? ' tb-page' : '' ?>">
<?= function_exists("theme_render_announcement_bar") ? theme_render_announcement_bar() : "" ?>

<?php if ($showHeader): ?>
<?php
$headerPhone = theme_get('header.phone', '+44 07856 67 87');
$headerCtaText = theme_get('header.cta_text', 'Reserve Tea Ceremony');
$headerCtaLink = theme_get('header.cta_link', '#contact');
?>
<a href="#main-content" class="skip-nav">Skip to content</a>
<header id="siteHeader" class="ch-header">
    <div class="ch-header-pill">
        <div class="ch-pill-inner">
            <a href="/" class="ch-brand" data-ts="brand.logo">
                <?php if ($tsLogo): ?>
                    <img src="<?= esc($tsLogo) ?>" alt="<?= esc(theme_get('brand.site_name', $siteName)) ?>" class="ch-logo-img">
                <?php else: ?>
                    <span class="ch-logo-text" data-ts="brand.site_name"><?= esc(theme_get('brand.site_name', $siteName)) ?></span>
                <?php endif; ?>
            </a>
            
            <nav id="headerNav" class="ch-nav">
                <?= render_menu('header', ['class' => 'ch-nav-links', 'link_class' => 'ch-nav-link', 'wrap' => false]) ?>
            </nav>

            <div class="ch-actions">
                <?php if ($headerPhone): ?>
                <a href="tel:<?= esc(str_replace(' ', '', $headerPhone)) ?>" class="ch-phone">
                    <i class="fas fa-phone"></i>
                    <span data-ts="header.phone"><?= esc($headerPhone) ?></span>
                </a>
                <?php endif; ?>
                <a href="<?= esc($headerCtaLink) ?>" 
                   class="ch-cta-btn"
                   data-ts="header.cta_text" 
                   data-ts-href="header.cta_link">
                    <?= esc($headerCtaText) ?>
                </a>
            </div>

            <button class="dark-mode-toggle" data-dark-toggle aria-label="Toggle dark mode" style="background:none;border:none;cursor:pointer;font-size:1.25rem;padding:4px 8px">🌙</button>
    <button id="mobileToggle" class="ch-mobile-toggle" aria-label="Menu">
                <span></span>
                <span></span>
                <span></span>
            </button>
        </div>
    </div>
</header>
<div class="mobile-overlay" id="mobileOverlay"></div>
<?php endif; ?>

<?php if ($isTbPage): ?>
    <?= $content ?? '' ?>
<?php else: ?>
    <main id="main-content"><?= $content ?? '' ?></main>
<?php endif; ?>

<?php if ($showFooter): ?>
<?php
$footerDesc = theme_get('footer.description', 'Experience the ancient art of Japanese tea ceremony in our serene bamboo garden. Every moment crafted with mindfulness and grace.');
$footerAddress = theme_get('footer.address', '70 Broomstick Hall Road, EN9 1LR');
$footerPhone = theme_get('footer.phone', '+44 07856 67 87');
$footerEmail = theme_get('footer.email', 'info@jessieai.com');
$footerHours = theme_get('footer.hours', 'Tue-Sun: 10:00-18:00');
$footerCopyright = theme_get('footer.copyright', '');
?>
<footer class="ch-footer">
    <div class="ch-footer-waves">
        <svg viewBox="0 0 1200 120" preserveAspectRatio="none">
            <path d="M0,0 C150,60 350,0 600,30 C850,60 1050,0 1200,30 L1200,120 L0,120 Z" fill="var(--surface)"></path>
        </svg>
    </div>
    
    <div class="ch-footer-main">
        <div class="container">
            <div class="ch-footer-grid">
                <div class="ch-footer-brand-col">
                    <a href="/" class="ch-footer-brand" data-ts="brand.logo">
                        <?php if ($tsLogo): ?>
                            <img src="<?= esc($tsLogo) ?>" alt="<?= esc(theme_get('brand.site_name', $siteName)) ?>" class="ch-footer-logo">
                        <?php else: ?>
                            <span class="ch-footer-logo-text" data-ts="brand.site_name"><?= esc(theme_get('brand.site_name', $siteName)) ?></span>
                        <?php endif; ?>
                    </a>
                    <p class="ch-footer-tagline" data-ts="footer.description">
                        <?= esc($footerDesc) ?>
                    </p>
                    <div class="ch-footer-social">
                        <?php if (theme_get('footer.facebook')): ?>
                        <a href="<?= esc(theme_get('footer.facebook')) ?>" target="_blank" rel="noopener" aria-label="Facebook">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                        <?php endif; ?>
                        <?php if (theme_get('footer.instagram')): ?>
                        <a href="<?= esc(theme_get('footer.instagram')) ?>" target="_blank" rel="noopener" aria-label="Instagram">
                            <i class="fab fa-instagram"></i>
                        </a>
                        <?php endif; ?>
                        <?php if (theme_get('footer.linkedin')): ?>
                        <a href="<?= esc(theme_get('footer.linkedin')) ?>" target="_blank" rel="noopener" aria-label="LinkedIn">
                            <i class="fab fa-linkedin-in"></i>
                        </a>
                        <?php endif; ?>
                        <?php if (theme_get('footer.youtube')): ?>
                        <a href="<?= esc(theme_get('footer.youtube')) ?>" target="_blank" rel="noopener" aria-label="YouTube">
                            <i class="fab fa-youtube"></i>
                        </a>
                        <?php endif; ?>
                    </div>
                </div>

                <div class="ch-footer-nav-col">
                    <h4 class="ch-footer-heading">Explore</h4>
                    <?= render_menu('footer', ['class' => 'ch-footer-links', 'link_class' => 'ch-footer-link', 'wrap' => false]) ?>
                </div>

                <div class="ch-footer-contact-col">
                    <h4 class="ch-footer-heading">Visit Us</h4>
                    <div class="ch-footer-contact">
                        <?php if ($footerAddress): ?>
                        <div class="ch-contact-item" data-ts="footer.address">
                            <i class="fas fa-map-marker-alt"></i>
                            <span><?= esc($footerAddress) ?></span>
                        </div>
                        <?php endif; ?>
                        <?php if ($footerPhone): ?>
                        <div class="ch-contact-item">
                            <i class="fas fa-phone"></i>
                            <a href="tel:<?= esc(str_replace(' ', '', $footerPhone)) ?>" data-ts="footer.phone">
                                <?= esc($footerPhone) ?>
                            </a>
                        </div>
                        <?php endif; ?>
                        <?php if ($footerEmail): ?>
                        <div class="ch-contact-item">
                            <i class="fas fa-envelope"></i>
                            <a href="mailto:<?= esc($footerEmail) ?>" data-ts="footer.email">
                                <?= esc($footerEmail) ?>
                            </a>
                        </div>
                        <?php endif; ?>
                        <?php if ($footerHours): ?>
                        <div class="ch-contact-item" data-ts="footer.hours">
                            <i class="fas fa-clock"></i>
                            <span><?= esc($footerHours) ?></span>
                        </div>
                        <?php endif; ?>
                    </div>
                </div>

                <div class="ch-footer-newsletter-col">
                    <h4 class="ch-footer-heading">Tea Notes</h4>
                    <p class="ch-newsletter-desc">Receive seasonal tea ceremony updates and mindful moments.</p>
                    <form class="ch-newsletter-form">
                        <input type="email" placeholder="Your email" class="ch-newsletter-input" required>
                        <button type="submit" class="ch-newsletter-btn">
                            <i class="fas fa-paper-plane"></i>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="ch-footer-bottom">
        <div class="container">
            <p class="ch-copyright" data-ts="footer.copyright">
                <?= $footerCopyright ? esc($footerCopyright) : '&copy; ' . date('Y') . ' ' . esc(theme_get('brand.site_name', $siteName)) . '. All rights reserved.' ?>
            </p>
        </div>
    </div>
</footer>
<?php endif; ?>

<script src="<?= $themePath ?>/assets/js/main.js"></script>
<?php if (function_exists('cms_ab_testing_widget')): echo cms_ab_testing_widget(); endif; ?>
<?php if (function_exists('ai_theme_chat_widget')): echo ai_theme_chat_widget(); endif; ?>
</body>
</html>