<?php
/**
 * AI-Generated Theme Layout
 * Generated by AI Theme Builder
 */

if (!defined('CMS_ROOT')) define('CMS_ROOT', dirname(__DIR__, 2));
if (!defined('CMS_APP')) define('CMS_APP', CMS_ROOT . '/app');

require_once CMS_APP . '/helpers/functions.php';

if (file_exists(CMS_ROOT . '/includes/helpers/menu.php')) {
    require_once CMS_ROOT . '/includes/helpers/menu.php';
}

$jtbBootPath = CMS_ROOT . '/plugins/jessie-theme-builder/includes/jtb-frontend-boot.php';
if (file_exists($jtbBootPath)) require_once $jtbBootPath;

$themeConfig = get_theme_config();
$themeOptions = $themeConfig['options'] ?? [];
$showHeader = $themeOptions['show_header'] ?? true;
$showFooter = $themeOptions['show_footer'] ?? true;

$siteName = theme_get('brand.site_name', get_site_name());
$siteLogo = theme_get('brand.logo', get_site_logo());
$tsLogo = theme_get('brand.logo') ?: $siteLogo;

$pageData = $page ?? [];
if (!empty($title) && empty($pageData['title'])) $pageData['title'] = $title;
$isTbPage = !empty($page['is_tb_page']);

$themeCssVariables = generate_theme_css_variables($themeConfig);
$themePath = '/themes/' . basename(__DIR__);
?><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?= render_seo_meta($pageData) ?>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400;9..144,700&amp;family=Be+Vietnam+Pro:wght@400;500;600&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/assets/css/fontawesome.min.css">
    <link rel="stylesheet" href="/assets/css/tb-frontend.css">
    <link rel="stylesheet" href="<?= $themePath ?>/assets/css/style.css">
    <style>
<?= $themeCssVariables ?>
<?= generate_studio_css_overrides() ?>
    </style>
<?= function_exists("theme_render_favicon") ? theme_render_favicon() : "" ?>
<?= function_exists("theme_render_og_image") ? theme_render_og_image() : "" ?>
</head>
<body class="<?= esc(get_body_class() ?? '') ?><?= $isTbPage ? ' tb-page' : '' ?>">
<?= function_exists("theme_render_announcement_bar") ? theme_render_announcement_bar() : "" ?>

<?php if ($showHeader): ?>
<a href="#main-content" class="skip-nav">Skip to content</a>
<header class="site-header" id="siteHeader">
    <div class="header-container">
        <a href="/" class="header-logo" data-ts="brand.logo">
            <?php if ($tsLogo): ?>
                <img src="<?= esc($tsLogo) ?>" alt="<?= esc(theme_get('brand.site_name', $siteName)) ?>">
            <?php else: ?>
                <span class="logo-text" data-ts="brand.site_name"><?= esc(theme_get('brand.site_name', $siteName)) ?></span>
            <?php endif; ?>
        </a>
        <nav class="header-nav" id="headerNav">
            <?= render_menu('header', ['class' => 'nav-links', 'link_class' => 'nav-link', 'wrap' => false]) ?>
        </nav>
        <div class="header-actions">
            <a href="<?= esc(theme_get('header.cta_link', '#contact')) ?>" class="header-cta" data-ts="header.cta_text" data-ts-href="header.cta_link"><?= esc(theme_get('header.cta_text', 'Order Ahead')) ?></a>
            <button class="mobile-toggle" id="mobileToggle" aria-label="Toggle menu">
                <span></span>
                <span></span>
            </button>
        </div>
    </div>
</header>
<div class="mobile-overlay" id="mobileOverlay"></div>
<?php endif; ?>

<?php if ($isTbPage): ?>
    <?= $content ?? '' ?>
<?php else: ?>
    <main id="main-content"><?= $content ?? '' ?></main>
<?php endif; ?>

<?php if ($showFooter): ?>
<footer class="site-footer">
    <div class="footer-main">
        <div class="container">
            <div class="footer-brand-block">
                <a href="/" class="footer-logo" data-ts="brand.logo">
                    <?php if ($tsLogo): ?>
                        <img src="<?= esc($tsLogo) ?>" alt="<?= esc(theme_get('brand.site_name', $siteName)) ?>" height="36">
                    <?php else: ?>
                        <span class="logo-text" data-ts="brand.site_name"><?= esc(theme_get('brand.site_name', $siteName)) ?></span>
                    <?php endif; ?>
                </a>
                <p class="footer-tagline" data-ts="footer.description"><?= esc(theme_get('footer.description', 'Scandinavian simplicity meets exceptional coffee. Single-origin beans, crafted with care.')) ?></p>
                <div class="footer-social">
                    <?php if (theme_get('footer.instagram')): ?>
                    <a href="<?= esc(theme_get('footer.instagram')) ?>" aria-label="Instagram" target="_blank" rel="noopener"><i class="fab fa-instagram"></i></a>
                    <?php endif; ?>
                    <?php if (theme_get('footer.facebook')): ?>
                    <a href="<?= esc(theme_get('footer.facebook')) ?>" aria-label="Facebook" target="_blank" rel="noopener"><i class="fab fa-facebook-f"></i></a>
                    <?php endif; ?>
                    <?php if (theme_get('footer.linkedin')): ?>
                    <a href="<?= esc(theme_get('footer.linkedin')) ?>" aria-label="LinkedIn" target="_blank" rel="noopener"><i class="fab fa-linkedin-in"></i></a>
                    <?php endif; ?>
                    <?php if (theme_get('footer.youtube')): ?>
                    <a href="<?= esc(theme_get('footer.youtube')) ?>" aria-label="YouTube" target="_blank" rel="noopener"><i class="fab fa-youtube"></i></a>
                    <?php endif; ?>
                </div>
            </div>
            <div class="footer-links-block">
                <h4>Explore</h4>
                <?= render_menu('footer', ['class' => 'footer-links', 'link_class' => 'footer-link', 'wrap' => false]) ?>
            </div>
            <div class="footer-contact-block">
                <h4>Visit Us</h4>
                <?php if (theme_get('footer.address')): ?>
                <p data-ts="footer.address"><i class="fas fa-map-marker-alt"></i> <?= esc(theme_get('footer.address')) ?></p>
                <?php endif; ?>
                <?php if (theme_get('footer.phone')): ?>
                <p data-ts="footer.phone"><i class="fas fa-phone"></i> <?= esc(theme_get('footer.phone')) ?></p>
                <?php endif; ?>
                <?php if (theme_get('footer.email')): ?>
                <p data-ts="footer.email"><i class="fas fa-envelope"></i> <?= esc(theme_get('footer.email')) ?></p>
                <?php endif; ?>
                <?php if (theme_get('footer.hours')): ?>
                <p data-ts="footer.hours"><i class="fas fa-clock"></i> <?= esc(theme_get('footer.hours')) ?></p>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="container">
            <p data-ts="footer.copyright"><?= theme_get('footer.copyright') ? esc(theme_get('footer.copyright')) : '&copy; ' . date('Y') . ' ' . esc(theme_get('brand.site_name', $siteName)) . '. All rights reserved.' ?></p>
        </div>
    </div>
</footer>
<?php endif; ?>

<script src="<?= $themePath ?>/assets/js/main.js"></script>
<?php if (function_exists('cms_ab_testing_widget')): echo cms_ab_testing_widget(); endif; ?>
<?php if (function_exists('ai_theme_chat_widget')): echo ai_theme_chat_widget(); endif; ?>
</body>
</html>