<?php
/**
 * AI-Generated Theme Layout
 * Generated by AI Theme Builder
 */

if (!defined('CMS_ROOT')) define('CMS_ROOT', dirname(__DIR__, 2));
if (!defined('CMS_APP')) define('CMS_APP', CMS_ROOT . '/app');

require_once CMS_APP . '/helpers/functions.php';

if (file_exists(CMS_ROOT . '/includes/helpers/menu.php')) {
    require_once CMS_ROOT . '/includes/helpers/menu.php';
}

$jtbBootPath = CMS_ROOT . '/plugins/jessie-theme-builder/includes/jtb-frontend-boot.php';
if (file_exists($jtbBootPath)) require_once $jtbBootPath;

$themeConfig = get_theme_config();
$themeOptions = $themeConfig['options'] ?? [];
$showHeader = $themeOptions['show_header'] ?? true;
$showFooter = $themeOptions['show_footer'] ?? true;

$siteName = theme_get('brand.site_name', get_site_name());
$siteLogo = theme_get('brand.logo', get_site_logo());
$tsLogo = theme_get('brand.logo') ?: $siteLogo;

$pageData = $page ?? [];
if (!empty($title) && empty($pageData['title'])) $pageData['title'] = $title;
$isTbPage = !empty($page['is_tb_page']);

$themeCssVariables = generate_theme_css_variables($themeConfig);
$themePath = '/themes/' . basename(__DIR__);
?><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?= render_seo_meta($pageData) ?>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@700&amp;family=Crimson+Pro:wght@400&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/assets/css/fontawesome.min.css">
    <link rel="stylesheet" href="/assets/css/tb-frontend.css">
    <link rel="stylesheet" href="<?= $themePath ?>/assets/css/style.css">
    <style>
<?= $themeCssVariables ?>
<?= generate_studio_css_overrides() ?>
    </style>
<?= function_exists("theme_render_favicon") ? theme_render_favicon() : "" ?>
<?= function_exists("theme_render_og_image") ? theme_render_og_image() : "" ?>
</head>
<body class="<?= esc(get_body_class() ?? '') ?><?= $isTbPage ? ' tb-page' : '' ?>">
<?= function_exists("theme_render_announcement_bar") ? theme_render_announcement_bar() : "" ?>

<?php if ($showHeader): ?>
<a href="#main-content" class="skip-nav">Skip to content</a>
<header id="siteHeader" class="gp-header">
    <div class="gp-header__inner">
        <!-- Left-heavy branded nameplate (40% width) -->
        <div class="gp-header__brand">
            <a href="/" class="gp-header__logo">
                <?php if ($tsLogo): ?>
                    <img src="<?= esc($tsLogo) ?>" alt="<?= esc(theme_get('brand.site_name', $siteName)) ?>" height="<?= theme_get('header.logoSize', 36) ?>">
                <?php else: ?>
                    <span class="gp-header__logo-text" data-ts="brand.site_name"><?= esc(theme_get('brand.site_name', $siteName)) ?></span>
                <?php endif; ?>
            </a>
            <p class="gp-header__tagline" data-ts="brand.tagline"><?= esc(theme_get('brand.tagline', 'Precision Medicine Through Genomic Insight')) ?></p>
        </div>

        <!-- Right compact nav + contact + CTA -->
        <div class="gp-header__right">
            <!-- Contact info (phone) -->
            <?php if (theme_get('header.phone')): ?>
                <a href="tel:<?= esc(preg_replace('/[^0-9+]/', '', theme_get('header.phone'))) ?>" class="gp-header__phone" data-ts="header.phone">
                    <i class="fas fa-phone-alt"></i>
                    <span><?= esc(theme_get('header.phone')) ?></span>
                </a>
            <?php endif; ?>

            <!-- Navigation -->
            <nav id="headerNav" class="gp-header__nav">
                <?= render_menu('header', ['class' => 'gp-header__nav-links', 'link_class' => 'gp-header__nav-link', 'wrap' => false]) ?>
            </nav>

            <!-- CTA Button -->
            <a href="<?= esc(theme_get('header.cta_link', '#contact')) ?>" class="gp-header__cta" data-ts="header.cta_text" data-ts-href="header.cta_link">
                <?= esc(theme_get('header.cta_text', 'Schedule Consultation')) ?>
                <i class="fas fa-arrow-right"></i>
            </a>

            <!-- Mobile hamburger -->
            <button class="dark-mode-toggle" data-dark-toggle aria-label="Toggle dark mode" style="background:none;border:none;cursor:pointer;font-size:1.25rem;padding:4px 8px">🌙</button>
    <button id="mobileToggle" class="gp-header__hamburger" aria-label="Menu">
                <span></span>
                <span></span>
                <span></span>
            </button>
        </div>
    </div>
</header>
<div class="mobile-overlay" id="mobileOverlay"></div>
<?php endif; ?>

<?php if ($isTbPage): ?>
    <?= $content ?? '' ?>
<?php else: ?>
    <main id="main-content"><?= $content ?? '' ?></main>
<?php endif; ?>

<?php if ($showFooter): ?>
<footer class="gp-footer">
    <div class="gp-footer__top">
        <div class="container">
            <div class="gp-footer__layout">
                <!-- Big Brand Left (60%) -->
                <div class="gp-footer__brand">
                    <a href="/" class="gp-footer__logo">
                        <?php if ($tsLogo): ?>
                            <img src="<?= esc($tsLogo) ?>" alt="<?= esc(theme_get('brand.site_name', $siteName)) ?>" height="48">
                        <?php else: ?>
                            <span class="gp-footer__logo-text" data-ts="brand.site_name"><?= esc(theme_get('brand.site_name', $siteName)) ?></span>
                        <?php endif; ?>
                    </a>
                    <p class="gp-footer__description" data-ts="footer.description">
                        <?= esc(theme_get('footer.description', 'Pioneering personalized medicine through advanced genomic analysis. Transforming healthcare one genome at a time with precision, integrity, and innovation.')) ?>
                    </p>

                    <!-- Newsletter Signup -->
                    <div class="gp-footer__newsletter">
                        <h4 class="gp-footer__newsletter-title">Stay Updated</h4>
                        <p class="gp-footer__newsletter-desc">Receive the latest in genomic research and personalized health insights.</p>
                        <form class="gp-footer__newsletter-form">
                            <input type="email" placeholder="Your email address" class="gp-footer__newsletter-input">
                            <button type="submit" class="gp-footer__newsletter-btn">
                                <i class="fas fa-paper-plane"></i>
                            </button>
                        </form>
                    </div>
                </div>

                <!-- Compact Links + Contact Right -->
                <div class="gp-footer__right">
                    <!-- Quick Links -->
                    <div class="gp-footer__links">
                        <h4 class="gp-footer__links-title">Quick Links</h4>
                        <?= render_menu('footer', ['class' => 'gp-footer__links-list', 'link_class' => 'gp-footer__link', 'wrap' => false]) ?>
                    </div>

                    <!-- Contact Info -->
                    <div class="gp-footer__contact">
                        <h4 class="gp-footer__contact-title">Contact Us</h4>
                        <?php if (theme_get('footer.address')): ?>
                            <div class="gp-footer__contact-item">
                                <i class="fas fa-map-marker-alt"></i>
                                <span data-ts="footer.address"><?= esc(theme_get('footer.address')) ?></span>
                            </div>
                        <?php endif; ?>
                        <?php if (theme_get('footer.phone')): ?>
                            <div class="gp-footer__contact-item">
                                <i class="fas fa-phone-alt"></i>
                                <a href="tel:<?= esc(preg_replace('/[^0-9+]/', '', theme_get('footer.phone'))) ?>" data-ts="footer.phone"><?= esc(theme_get('footer.phone')) ?></a>
                            </div>
                        <?php endif; ?>
                        <?php if (theme_get('footer.email')): ?>
                            <div class="gp-footer__contact-item">
                                <i class="fas fa-envelope"></i>
                                <a href="mailto:<?= esc(theme_get('footer.email')) ?>" data-ts="footer.email"><?= esc(theme_get('footer.email')) ?></a>
                            </div>
                        <?php endif; ?>
                    </div>

                    <!-- Social Media -->
                    <div class="gp-footer__social">
                        <h4 class="gp-footer__social-title">Follow Us</h4>
                        <div class="gp-footer__social-icons">
                            <?php if (theme_get('footer.facebook')): ?>
                                <a href="<?= esc(theme_get('footer.facebook')) ?>" target="_blank" class="gp-footer__social-icon">
                                    <i class="fab fa-facebook-f"></i>
                                </a>
                            <?php endif; ?>
                            <?php if (theme_get('footer.instagram')): ?>
                                <a href="<?= esc(theme_get('footer.instagram')) ?>" target="_blank" class="gp-footer__social-icon">
                                    <i class="fab fa-instagram"></i>
                                </a>
                            <?php endif; ?>
                            <?php if (theme_get('footer.linkedin')): ?>
                                <a href="<?= esc(theme_get('footer.linkedin')) ?>" target="_blank" class="gp-footer__social-icon">
                                    <i class="fab fa-linkedin-in"></i>
                                </a>
                            <?php endif; ?>
                            <?php if (theme_get('footer.twitter')): ?>
                                <a href="<?= esc(theme_get('footer.twitter')) ?>" target="_blank" class="gp-footer__social-icon">
                                    <i class="fab fa-twitter"></i>
                                </a>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="gp-footer__bottom">
        <div class="container">
            <p class="gp-footer__copyright" data-ts="footer.copyright">
                <?= theme_get('footer.copyright') ? esc(theme_get('footer.copyright')) : '&copy; ' . date('Y') . ' ' . esc(theme_get('brand.site_name', $siteName)) . '. All rights reserved.' ?>
            </p>
        </div>
    </div>
</footer>
<?php endif; ?>

<script src="<?= $themePath ?>/assets/js/main.js"></script>
<?php if (function_exists('cms_ab_testing_widget')): echo cms_ab_testing_widget(); endif; ?>
<?php if (function_exists('ai_theme_chat_widget')): echo ai_theme_chat_widget(); endif; ?>
</body>
</html>