<?php
/**
 * AI-Generated Theme Layout
 * Generated by AI Theme Builder
 */

if (!defined('CMS_ROOT')) define('CMS_ROOT', dirname(__DIR__, 2));
if (!defined('CMS_APP')) define('CMS_APP', CMS_ROOT . '/app');

require_once CMS_APP . '/helpers/functions.php';

if (file_exists(CMS_ROOT . '/includes/helpers/menu.php')) {
    require_once CMS_ROOT . '/includes/helpers/menu.php';
}

$jtbBootPath = CMS_ROOT . '/plugins/jessie-theme-builder/includes/jtb-frontend-boot.php';
if (file_exists($jtbBootPath)) require_once $jtbBootPath;

$themeConfig = get_theme_config();
$themeOptions = $themeConfig['options'] ?? [];
$showHeader = $themeOptions['show_header'] ?? true;
$showFooter = $themeOptions['show_footer'] ?? true;

$siteName = theme_get('brand.site_name', get_site_name());
$siteLogo = theme_get('brand.logo', get_site_logo());
$tsLogo = theme_get('brand.logo') ?: $siteLogo;

$pageData = $page ?? [];
if (!empty($title) && empty($pageData['title'])) $pageData['title'] = $title;
$isTbPage = !empty($page['is_tb_page']);

$themeCssVariables = generate_theme_css_variables($themeConfig);
$themePath = '/themes/' . basename(__DIR__);
?><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?= render_seo_meta($pageData) ?>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&amp;family=IBM+Plex+Sans:wght@400;600;700&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/assets/css/fontawesome.min.css">
    <link rel="stylesheet" href="/assets/css/tb-frontend.css">
    <link rel="stylesheet" href="<?= $themePath ?>/assets/css/style.css">
    <style>
<?= $themeCssVariables ?>
<?= generate_studio_css_overrides() ?>
    </style>
<?= function_exists("theme_render_favicon") ? theme_render_favicon() : "" ?>
<?= function_exists("theme_render_og_image") ? theme_render_og_image() : "" ?>
</head>
<body class="<?= esc(get_body_class() ?? '') ?><?= $isTbPage ? ' tb-page' : '' ?>">
<?= function_exists("theme_render_announcement_bar") ? theme_render_announcement_bar() : "" ?>

<?php if ($showHeader): ?>
<a href="#main-content" class="skip-nav">Skip to content</a>
<header id="siteHeader" class="sf-header">
    <div class="sf-header__top-bar">
        <div class="sf-container">
            <div class="sf-header__top-content">
                <div class="sf-header__contact-info">
                    <?php if (theme_get('header.phone')): ?>
                        <a href="tel:<?= esc(theme_get('header.phone')) ?>" class="sf-header__contact-link">
                            <i class="fas fa-phone-alt"></i>
                            <span data-ts="header.phone"><?= esc(theme_get('header.phone', '+1 (555) 123-4567')) ?></span>
                        </a>
                    <?php endif; ?>
                    <?php if (theme_get('header.email')): ?>
                        <a href="mailto:<?= esc(theme_get('header.email')) ?>" class="sf-header__contact-link">
                            <i class="fas fa-envelope"></i>
                            <span data-ts="header.email"><?= esc(theme_get('header.email', 'hello@scarletflow.com')) ?></span>
                        </a>
                    <?php endif; ?>
                </div>
                <div class="sf-header__social">
                    <?php if (theme_get('footer.facebook')): ?>
                        <a href="<?= esc(theme_get('footer.facebook')) ?>" target="_blank" aria-label="Facebook">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                    <?php endif; ?>
                    <?php if (theme_get('footer.instagram')): ?>
                        <a href="<?= esc(theme_get('footer.instagram')) ?>" target="_blank" aria-label="Instagram">
                            <i class="fab fa-instagram"></i>
                        </a>
                    <?php endif; ?>
                    <?php if (theme_get('footer.linkedin')): ?>
                        <a href="<?= esc(theme_get('footer.linkedin')) ?>" target="_blank" aria-label="LinkedIn">
                            <i class="fab fa-linkedin-in"></i>
                        </a>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
    <div class="sf-header__main">
        <div class="sf-container">
            <div class="sf-header__main-inner">
                <nav id="headerNav" class="sf-header__nav sf-header__nav--primary">
                    <?= render_menu('header', ['class' => 'sf-nav__list', 'link_class' => 'sf-nav__link', 'wrap' => false]) ?>
                </nav>
                <div class="sf-header__brand">
                    <a href="/" class="sf-header__logo">
                        <?php if ($tsLogo): ?>
                            <img src="<?= esc($tsLogo) ?>" alt="<?= esc(theme_get('brand.site_name', $siteName)) ?>" height="<?= $themeConfig['header']['logoSize'] ?? 36 ?>">
                        <?php else: ?>
                            <span class="sf-header__logo-text" data-ts="brand.site_name"><?= esc(theme_get('brand.site_name', $siteName)) ?></span>
                        <?php endif; ?>
                    </a>
                </div>
                <div class="sf-header__actions">
                    <a href="<?= esc(theme_get('header.cta_link', '#contact')) ?>" class="sf-btn sf-btn--header" data-ts="header.cta_text" data-ts-href="header.cta_link">
                        <?= esc(theme_get('header.cta_text', 'Get a Strategy')) ?>
                    </a>
                    <button class="dark-mode-toggle" data-dark-toggle aria-label="Toggle dark mode" style="background:none;border:none;cursor:pointer;font-size:1.25rem;padding:4px 8px">🌙</button>
    <button id="mobileToggle" class="sf-header__toggle" aria-label="Menu">
                        <span></span>
                        <span></span>
                        <span></span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="mobile-overlay" id="mobileOverlay"></div>
<?php endif; ?>

<?php if ($isTbPage): ?>
    <?= $content ?? '' ?>
<?php else: ?>
    <main id="main-content"><?= $content ?? '' ?></main>
<?php endif; ?>

<?php if ($showFooter): ?>
<footer class="sf-footer">
    <div class="sf-footer__wave">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 120" preserveAspectRatio="none">
            <path d="M321.39,56.44c58-10.79,114.16-30.13,172-41.86,82.39-16.72,168.19-17.73,250.45-.39C823.78,31,906.67,72,985.66,92.83c70.05,18.48,146.53,26.09,214.34,3V0H0V27.35A600.21,600.21,0,0,0,321.39,56.44Z"></path>
        </svg>
    </div>
    <div class="sf-footer__main">
        <div class="sf-container">
            <div class="sf-footer__grid">
                <div class="sf-footer__brand-block">
                    <a href="/" class="sf-footer__logo">
                        <?php if ($tsLogo): ?>
                            <img src="<?= esc($tsLogo) ?>" alt="<?= esc(theme_get('brand.site_name', $siteName)) ?>" height="40">
                        <?php else: ?>
                            <span class="sf-footer__logo-text" data-ts="brand.site_name"><?= esc(theme_get('brand.site_name', $siteName)) ?></span>
                        <?php endif; ?>
                    </a>
                    <p class="sf-footer__tagline" data-ts="footer.description">
                        <?= esc(theme_get('footer.description', 'Full-service digital marketing agency driving growth for DTC brands through data-driven strategies.')) ?>
                    </p>
                    <div class="sf-footer__social">
                        <?php if (theme_get('footer.facebook')): ?>
                            <a href="<?= esc(theme_get('footer.facebook')) ?>" target="_blank" aria-label="Facebook" class="sf-footer__social-link">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                        <?php endif; ?>
                        <?php if (theme_get('footer.instagram')): ?>
                            <a href="<?= esc(theme_get('footer.instagram')) ?>" target="_blank" aria-label="Instagram" class="sf-footer__social-link">
                                <i class="fab fa-instagram"></i>
                            </a>
                        <?php endif; ?>
                        <?php if (theme_get('footer.linkedin')): ?>
                            <a href="<?= esc(theme_get('footer.linkedin')) ?>" target="_blank" aria-label="LinkedIn" class="sf-footer__social-link">
                                <i class="fab fa-linkedin-in"></i>
                            </a>
                        <?php endif; ?>
                        <?php if (theme_get('footer.twitter')): ?>
                            <a href="<?= esc(theme_get('footer.twitter')) ?>" target="_blank" aria-label="Twitter" class="sf-footer__social-link">
                                <i class="fab fa-twitter"></i>
                            </a>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="sf-footer__services">
                    <h4 class="sf-footer__title" data-ts="footer.services_title">Our Services</h4>
                    <ul class="sf-footer__list">
                        <li><a href="/services#seo" class="sf-footer__link">SEO & Content</a></li>
                        <li><a href="/services#ppc" class="sf-footer__link">PPC Advertising</a></li>
                        <li><a href="/services#social" class="sf-footer__link">Social Media</a></li>
                        <li><a href="/services#conversion" class="sf-footer__link">Conversion Optimization</a></li>
                        <li><a href="/services#analytics" class="sf-footer__link">Analytics & Reporting</a></li>
                    </ul>
                </div>
                <div class="sf-footer__contact">
                    <h4 class="sf-footer__title" data-ts="footer.contact_title">Get In Touch</h4>
                    <address class="sf-footer__contact-info">
                        <?php if (theme_get('footer.address')): ?>
                            <div class="sf-footer__contact-item">
                                <i class="fas fa-map-marker-alt"></i>
                                <span data-ts="footer.address"><?= esc(theme_get('footer.address', '123 Marketing Ave, Suite 500<br>New York, NY 10001')) ?></span>
                            </div>
                        <?php endif; ?>
                        <?php if (theme_get('footer.phone')): ?>
                            <div class="sf-footer__contact-item">
                                <i class="fas fa-phone-alt"></i>
                                <a href="tel:<?= esc(theme_get('footer.phone')) ?>" data-ts="footer.phone"><?= esc(theme_get('footer.phone', '+1 (555) 123-4567')) ?></a>
                            </div>
                        <?php endif; ?>
                        <?php if (theme_get('footer.email')): ?>
                            <div class="sf-footer__contact-item">
                                <i class="fas fa-envelope"></i>
                                <a href="mailto:<?= esc(theme_get('footer.email')) ?>" data-ts="footer.email"><?= esc(theme_get('footer.email', 'hello@scarletflow.com')) ?></a>
                            </div>
                        <?php endif; ?>
                        <?php if (theme_get('footer.hours')): ?>
                            <div class="sf-footer__contact-item">
                                <i class="fas fa-clock"></i>
                                <span data-ts="footer.hours"><?= esc(theme_get('footer.hours', 'Mon-Fri: 9am-6pm EST')) ?></span>
                            </div>
                        <?php endif; ?>
                    </address>
                </div>
                <div class="sf-footer__newsletter">
                    <h4 class="sf-footer__title">Marketing Insights</h4>
                    <p class="sf-footer__newsletter-desc">Get weekly tips on SEO, PPC, and conversion optimization.</p>
                    <form class="sf-footer__form">
                        <input type="email" placeholder="Your email address" class="sf-footer__input" required>
                        <button type="submit" class="sf-btn sf-btn--small">Subscribe</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="sf-footer__bottom">
        <div class="sf-container">
            <div class="sf-footer__bottom-inner">
                <nav class="sf-footer__nav">
                    <?= render_menu('footer', ['class' => 'sf-footer__nav-list', 'link_class' => 'sf-footer__nav-link', 'wrap' => false]) ?>
                </nav>
                <p class="sf-footer__copyright" data-ts="footer.copyright">
                    <?= theme_get('footer.copyright') ? esc(theme_get('footer.copyright')) : '&copy; ' . date('Y') . ' ' . esc(theme_get('brand.site_name', $siteName)) . '. All rights reserved.' ?>
                </p>
            </div>
        </div>
    </div>
</footer>
<?php endif; ?>

<script src="<?= $themePath ?>/assets/js/main.js"></script>
<?php if (function_exists('cms_ab_testing_widget')): echo cms_ab_testing_widget(); endif; ?>
<?php if (function_exists('ai_theme_chat_widget')): echo ai_theme_chat_widget(); endif; ?>
</body>
</html>