<?php
/**
 * About Page
 * Generated by AI Designer for Jessie AI CMS
 * 
 * @package Theme
 */

// Page configuration
$page_title = 'About | Jessie AI CMS';
$page_name = 'about';

// Include header
if (isset($theme_path) && file_exists($theme_path . '/header.php')) {
    include $theme_path . '/header.php';
}
?>

<main>
    <section class="section section-hero" style="background: linear-gradient(to right, var(--color-primary), rgba(29, 78, 216, 0.8)), url('https://images.pexels.com/photos/1083822/pexels-photo-1083822.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop') no-repeat center center; background-size: cover;">
        <div class="container">
            <h1 style="font-family: 'Inter', sans-serif; font-size: 3rem; color: #FFFFFF;">Empower Your Content with Jessie AI CMS</h1>
            <p style="font-family: 'Inter', sans-serif; font-size: 1.5rem; color: #FFFFFF;">Boost your productivity with AI workflows designed for digital marketers and content creators.</p>
            <a href="#cta" class="btn btn-primary">Get Started</a>
        </div>
    </section>
    
    <section class="section section-story">
        <div class="container">
            <h2 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Our Story</h2>
            <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Founded in 2023, Jessie AI CMS was created to revolutionize the way content is produced and managed. Our journey began with a vision to streamline workflows through AI-driven technology, enabling marketers and content creators to focus on what truly matters.</p>
            <div class="grid grid-2">
                <div class="card">
                    <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">2023</h3>
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Launch of Jessie AI CMS, introducing smart workflows.</p>
                </div>
                <div class="card">
                    <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">2024</h3>
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Integration with N8N for seamless automation.</p>
                </div>
            </div>
        </div>
    </section>
    
    <section class="section section-mission">
        <div class="container">
            <h2 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Our Mission</h2>
            <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">To empower content creators with cutting-edge AI tools that enhance productivity and elevate SEO strategies.</p>
            <img src="https://images.pexels.com/photos/30617066/pexels-photo-30617066.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop" alt="Mission Imagery">
        </div>
    </section>
    
    <section class="section section-values">
        <div class="container">
            <h2 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Core Values</h2>
            <div class="grid grid-4">
                <div class="card">
                    <i class="fas fa-lightbulb" style="color: var(--color-secondary);"></i>
                    <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Innovation</h3>
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">We embrace new ideas and technologies to stay ahead.</p>
                </div>
                <div class="card">
                    <i class="fas fa-users" style="color: var(--color-secondary);"></i>
                    <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Community</h3>
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">We support our users by building a strong community.</p>
                </div>
                <div class="card">
                    <i class="fas fa-check-circle" style="color: var(--color-secondary);"></i>
                    <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Quality</h3>
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">We deliver high-quality tools that enhance your content strategy.</p>
                </div>
                <div class="card">
                    <i class="fas fa-cogs" style="color: var(--color-secondary);"></i>
                    <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Efficiency</h3>
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Our solutions streamline your workflows for maximum productivity.</p>
                </div>
            </div>
        </div>
    </section>
    
    <section class="section section-team-preview">
        <div class="container">
            <h2 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Meet Our Team</h2>
            <div class="grid grid-3">
                <div class="card">
                    <img src="https://images.pexels.com/photos/35437523/pexels-photo-35437523.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop" alt="Team Member 1">
                    <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Jessie Taylor</h3>
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">CEO & Founder</p>
                </div>
                <div class="card">
                    <img src="https://images.pexels.com/photos/6775122/pexels-photo-6775122.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop" alt="Team Member 2">
                    <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Mark Johnson</h3>
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">CTO</p>
                </div>
                <div class="card">
                    <img src="https://images.pexels.com/photos/6775122/pexels-photo-6775122.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop" alt="Team Member 3">
                    <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Sarah Lee</h3>
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Marketing Director</p>
                </div>
            </div>
        </div>
    </section>
    
    <section class="section section-timeline">
        <div class="container">
            <h2 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Our Journey</h2>
            <div class="grid grid-2">
                <div class="card">
                    <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">2023</h3>
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Launch of Jessie AI CMS</p>
                </div>
                <div class="card">
                    <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">2024</h3>
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Integration with N8N for automation</p>
                </div>
            </div>
        </div>
    </section>
    
    <section class="section section-cta">
        <div class="container">
            <h2 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Ready to Transform Your Content Strategy?</h2>
            <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Join us at Jessie AI CMS and elevate your SEO game with our advanced tools.</p>
            <a href="#signup" class="btn btn-secondary">Sign Up Now</a>
        </div>
    </section>
</main>

<?php
// Include footer
if (isset($theme_path) && file_exists($theme_path . '/footer.php')) {
    include $theme_path . '/footer.php';
}