<?php
/**
 * Blog Page
 * Generated by AI Designer for Jessie AI CMS
 * 
 * @package Theme
 */

// Page configuration
$page_title = 'Blog | Jessie AI CMS';
$page_name = 'blog';

// Include header
if (isset($theme_path) && file_exists($theme_path . '/header.php')) {
    include $theme_path . '/header.php';
}
?>

<main>
    <section class="section section-hero">
        <div class="container" style="background: linear-gradient(to bottom right, var(--color-primary), #FFFFFF); padding: 60px 20px; border-radius: 12px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
            <h1 style="font-family: 'Inter', sans-serif; color: var(--color-text); font-size: 48px; margin-bottom: 20px;">Boost Your Productivity with AI Workflows</h1>
            <p style="font-family: 'Inter', sans-serif; color: var(--color-text); font-size: 20px; margin-bottom: 30px;">Transform your content strategy with our theme builder and elevate your SEO game with cutting-edge AI technology.</p>
            <a href="#newsletter" class="btn btn-primary" style="border-radius: 8px;">Get Started</a>
        </div>
    </section>
    
    <section class="section section-featured-post">
        <div class="container">
            <article class="card" style="border-radius: 12px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); padding: 20px; margin-bottom: 40px;">
                <img src="https://images.pexels.com/photos/632527/pexels-photo-632527.jpeg?auto=compress&cs=tinysrgb&w=1200&h=630&fit=crop" alt="Featured Blog Post" style="border-radius: 12px; max-width: 100%; height: auto;">
                <h2 style="font-family: 'Inter', sans-serif; color: var(--color-text); font-size: 32px; margin-top: 15px;">Unleash the Power of AI in Your Marketing Strategy</h2>
                <p style="font-family: 'Inter', sans-serif; color: var(--color-text); font-size: 18px;">Discover how Jessie AI CMS can streamline your content creation process and enhance your SEO performance.</p>
                <a href="#featured-post" class="btn btn-secondary" style="border-radius: 8px;">Read More</a>
            </article>
        </div>
    </section>
    
    <section class="section section-posts-grid">
        <div class="container">
            <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text); font-size: 28px; margin-bottom: 20px;">Latest Posts</h3>
            <div class="grid grid-3">
                <article class="card" style="border-radius: 12px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
                    <img src="https://images.pexels.com/photos/11861406/pexels-photo-11861406.jpeg?auto=compress&cs=tinysrgb&w=1200&h=630&fit=crop" alt="Blog Post 1" style="border-radius: 12px; max-width: 100%; height: auto;">
                    <h4 style="font-family: 'Inter', sans-serif; color: var(--color-text); font-size: 24px; margin: 10px 0;">Integrating N8N for Workflow Automation</h4>
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text); font-size: 16px;">Learn how to automate your processes using N8N with Jessie AI CMS.</p>
                </article>
                <article class="card" style="border-radius: 12px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
                    <img src="https://images.pexels.com/photos/12166438/pexels-photo-12166438.jpeg?auto=compress&cs=tinysrgb&w=1200&h=630&fit=crop" alt="Blog Post 2" style="border-radius: 12px; max-width: 100%; height: auto;">
                    <h4 style="font-family: 'Inter', sans-serif; color: var(--color-text); font-size: 24px; margin: 10px 0;">SEO Strategies for AI Content</h4>
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text); font-size: 16px;">Elevate your SEO game with these advanced techniques tailored for AI-generated content.</p>
                </article>
                <article class="card" style="border-radius: 12px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
                    <img src="https://images.pexels.com/photos/12295317/pexels-photo-12295317.jpeg?auto=compress&cs=tinysrgb&w=1200&h=630&fit=crop" alt="Blog Post 3" style="border-radius: 12px; max-width: 100%; height: auto;">
                    <h4 style="font-family: 'Inter', sans-serif; color: var(--color-text); font-size: 24px; margin: 10px 0;">Creating Engaging Content with AI</h4>
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text); font-size: 16px;">Discover tips for crafting captivating content using Jessie AI CMS.</p>
                </article>
            </div>
        </div>
    </section>
    
    <section class="section section-categories">
        <div class="container">
            <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text); font-size: 28px; margin-bottom: 20px;">Explore Categories</h3>
            <div class="grid grid-4">
                <div class="card" style="border-radius: 12px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); padding: 20px;">
                    <h4 style="font-family: 'Inter', sans-serif; color: var(--color-text); font-size: 22px;">AI Workflows</h4>
                </div>
                <div class="card" style="border-radius: 12px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); padding: 20px;">
                    <h4 style="font-family: 'Inter', sans-serif; color: var(--color-text); font-size: 22px;">Content Strategy</h4>
                </div>
                <div class="card" style="border-radius: 12px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); padding: 20px;">
                    <h4 style="font-family: 'Inter', sans-serif; color: var(--color-text); font-size: 22px;">SEO Tips</h4>
                </div>
                <div class="card" style="border-radius: 12px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); padding: 20px;">
                    <h4 style="font-family: 'Inter', sans-serif; color: var(--color-text); font-size: 22px;">N8N Automation</h4>
                </div>
            </div>
        </div>
    </section>
    
    <section class="section section-newsletter" id="newsletter">
        <div class="container" style="padding: 40px; border-radius: 12px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
            <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text); font-size: 28px; margin-bottom: 20px;">Subscribe to Our Newsletter</h3>
            <p style="font-family: 'Inter', sans-serif; color: var(--color-text); font-size: 18px; margin-bottom: 20px;">Stay updated with the latest tips and trends in AI content creation and marketing.</p>
            <form action="#" method="post">
                <input type="email" placeholder="Enter your email" required style="padding: 10px; border-radius: 8px; border: 1px solid var(--color-text); width: 100%; max-width: 400px; margin-right: 10px;">
                <button type="submit" class="btn btn-primary" style="border-radius: 8px;">Subscribe</button>
            </form>
        </div>
    </section>
</main>

<?php
// Include footer
if (isset($theme_path) && file_exists($theme_path . '/footer.php')) {
    include $theme_path . '/footer.php';
}