<?php
/**
 * Contact Page
 * Generated by AI Designer for Jessie AI CMS
 * 
 * @package Theme
 */

// Page configuration
$page_title = 'Contact | Jessie AI CMS';
$page_name = 'contact';

// Include header
if (isset($theme_path) && file_exists($theme_path . '/header.php')) {
    include $theme_path . '/header.php';
}
?>

<main>
    <section class="section section-hero" style="background: linear-gradient(to bottom right, #1D4ED8, #FFFFFF); padding: 50px 0;">
        <div class="container text-center">
            <h1 style="font-family: 'Inter', sans-serif; color: #FFFFFF; font-size: 3rem;">Get in Touch with Jessie AI CMS</h1>
            <p style="font-family: 'Inter', sans-serif; color: #FFFFFF; font-size: 1.25rem;">Boost your productivity and elevate your content strategy today!</p>
            <a href="#contact-form" class="btn btn-primary" style="border-radius: 12px;">Contact Us</a>
        </div>
    </section>

    <section class="section section-contact-info">
        <div class="container grid grid-2" style="margin-top: 40px;">
            <div class="card" style="padding: 20px; border-radius: 12px; box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);">
                <h3 style="font-family: 'Inter', sans-serif; color: #111827;">Contact Information</h3>
                <p style="font-family: 'Inter', sans-serif; color: #111827;"><i class="fas fa-map-marker-alt"></i> 123 AI Lane, Tech City, CA 90210</p>
                <p style="font-family: 'Inter', sans-serif; color: #111827;"><i class="fas fa-phone"></i> (123) 456-7890</p>
                <p style="font-family: 'Inter', sans-serif; color: #111827;"><i class="fas fa-envelope"></i> support@jessieai.com</p>
            </div>
            <div class="card" style="padding: 20px; border-radius: 12px; box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);">
                <h3 style="font-family: 'Inter', sans-serif; color: #111827;">Business Hours</h3>
                <table style="width: 100%; border-collapse: collapse;">
                    <tr>
                        <th style="font-family: 'Inter', sans-serif; color: #111827;">Day</th>
                        <th style="font-family: 'Inter', sans-serif; color: #111827;">Hours</th>
                    </tr>
                    <tr>
                        <td style="font-family: 'Inter', sans-serif; color: #111827;">Monday - Friday</td>
                        <td style="font-family: 'Inter', sans-serif; color: #111827;">9 AM - 5 PM</td>
                    </tr>
                    <tr>
                        <td style="font-family: 'Inter', sans-serif; color: #111827;">Saturday</td>
                        <td style="font-family: 'Inter', sans-serif; color: #111827;">10 AM - 4 PM</td>
                    </tr>
                    <tr>
                        <td style="font-family: 'Inter', sans-serif; color: #111827;">Sunday</td>
                        <td style="font-family: 'Inter', sans-serif; color: #111827;">Closed</td>
                    </tr>
                </table>
            </div>
        </div>
    </section>

    <section class="section section-contact-form" id="contact-form">
        <div class="container" style="margin-top: 40px;">
            <h2 style="font-family: 'Inter', sans-serif; color: #111827;">Send Us a Message</h2>
            <form style="display: grid; gap: 20px; margin-top: 20px;">
                <input type="text" name="name" placeholder="Your Name" required style="padding: 12px; border-radius: 8px; border: 1px solid #E5E7EB;">
                <input type="email" name="email" placeholder="Your Email" required style="padding: 12px; border-radius: 8px; border: 1px solid #E5E7EB;">
                <input type="tel" name="phone" placeholder="Your Phone" required style="padding: 12px; border-radius: 8px; border: 1px solid #E5E7EB;">
                <textarea name="message" placeholder="Your Message" required style="padding: 12px; border-radius: 8px; border: 1px solid #E5E7EB;"></textarea>
                <button type="submit" class="btn btn-secondary" style="border-radius: 12px;">Submit</button>
            </form>
        </div>
    </section>

    <section class="section section-map" style="margin-top: 40px;">
        <div class="container">
            <h2 style="font-family: 'Inter', sans-serif; color: #111827;">Our Location</h2>
            <div style="height: 300px; border-radius: 12px; overflow: hidden; margin-top: 20px;">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3151.8354345094963!2d144.9537353153187!3d-37.81720997975197!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6ad642af0f017d05%3A0x5045675218ceed30!2sMelbourne%20CBD%2C%20Melbourne%20VIC%2C%20Australia!5e0!3m2!1sen!2sus!4v1616586198623!5m2!1sen!2sus" style="width: 100%; height: 100%; border: 0;" allowfullscreen="" loading="lazy"></iframe>
            </div>
        </div>
    </section>
</main>

<?php
// Include footer
if (isset($theme_path) && file_exists($theme_path . '/footer.php')) {
    include $theme_path . '/footer.php';
}