<?php
/**
 * Faq Page
 * Generated by AI Designer for Jessie AI CMS
 * 
 * @package Theme
 */

// Page configuration
$page_title = 'Faq | Jessie AI CMS';
$page_name = 'faq';

// Include header
if (isset($theme_path) && file_exists($theme_path . '/header.php')) {
    include $theme_path . '/header.php';
}
?>

<main>
    <section class="section section-hero" style="background: linear-gradient(to right, var(--color-primary), #E0F2FE);">
        <div class="container">
            <h1 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Frequently Asked Questions</h1>
            <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Everything you need to know about Jessie AI CMS to boost your productivity and transform your content strategy.</p>
            <a href="#contact" class="btn btn-primary">Get Started</a>
        </div>
    </section>

    <section class="section section-faq-list">
        <div class="container">
            <h2 style="font-family: 'Inter', sans-serif; color: var(--color-text);">FAQs</h2>
            <div class="grid grid-2">
                <div class="card">
                    <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">What is Jessie AI CMS?</h3>
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Jessie AI CMS is a powerful content management system that leverages AI-driven workflows to streamline content creation for digital marketers and content creators.</p>
                </div>
                <div class="card">
                    <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">How does it integrate with N8N?</h3>
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Our CMS allows seamless integration with N8N, enabling automation of your workflows and reducing manual effort in content management.</p>
                </div>
                <div class="card">
                    <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">What SEO tools are available?</h3>
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">We provide advanced SEO tools specifically designed for AI content, helping you elevate your SEO game effectively.</p>
                </div>
                <div class="card">
                    <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Can I customize my themes?</h3>
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Absolutely! Our theme builder allows you to customize your themes to fit your brand's unique identity.</p>
                </div>
            </div>
        </div>
    </section>

    <section class="section section-contact-cta" id="contact">
        <div class="container" style="text-align: center;">
            <h2 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Need More Help?</h2>
            <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Contact us for personalized assistance and support.</p>
            <p>
                <i class="fas fa-phone-alt"></i> Phone: (123) 456-7890 <br>
                <i class="far fa-envelope"></i> Email: support@jessieai.com
            </p>
            <a href="mailto:support@jessieai.com" class="btn btn-secondary">Contact Us</a>
        </div>
    </section>
</main>

<?php
// Include footer
if (isset($theme_path) && file_exists($theme_path . '/footer.php')) {
    include $theme_path . '/footer.php';
}