<?php
/**
 * Homepage Page
 * Generated by AI Designer for Jessie AI CMS
 * 
 * @package Theme
 */

// Page configuration
$page_title = 'Jessie AI CMS';
$page_name = 'homepage';

// Include header
if (isset($theme_path) && file_exists($theme_path . '/header.php')) {
    include $theme_path . '/header.php';
}
?>

<main>
    <section class="section section-hero" style="background: linear-gradient(to right, #1D4ED8, #FFFFFF);">
        <div class="container">
            <h1 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Unlock Your Content's Potential with Jessie AI CMS</h1>
            <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Boost your productivity with AI workflows tailored for digital marketers.</p>
            <a href="#services" class="btn btn-primary">Get Started</a>
        </div>
    </section>
    
    <section class="section section-about-preview">
        <div class="container grid-2">
            <img src="https://images.pexels.com/photos/7805685/pexels-photo-7805685.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop" alt="About Jessie AI CMS" style="border-radius: 12px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
            <div>
                <h2 style="font-family: 'Inter', sans-serif; color: var(--color-text);">About Jessie AI CMS</h2>
                <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Our CMS leverages AI technology to enhance your content strategy and streamline your workflows.</p>
                <a href="/about" class="btn btn-secondary">Learn More</a>
            </div>
        </div>
    </section>
    
    <section class="section section-features">
        <div class="container grid-3">
            <div class="card">
                <i class="fas fa-robot"></i>
                <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">AI-Driven Workflows</h3>
                <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Automate your content creation process and focus on what matters most.</p>
            </div>
            <div class="card">
                <i class="fas fa-cogs"></i>
                <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">N8N Integration</h3>
                <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Seamlessly integrate with N8N for powerful automation.</p>
            </div>
            <div class="card">
                <i class="fas fa-search"></i>
                <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Advanced SEO Tools</h3>
                <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Elevate your SEO game with cutting-edge AI technology designed for optimal content performance.</p>
            </div>
        </div>
    </section>
    
    <section class="section section-services-preview">
        <div class="container grid-4">
            <div class="card">
                <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Custom Theme Builder</h3>
                <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Create stunning themes without any coding knowledge.</p>
            </div>
            <div class="card">
                <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Content Strategy Consultation</h3>
                <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Expert advice to guide your content strategy.</p>
            </div>
            <div class="card">
                <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">SEO Optimization Service</h3>
                <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Comprehensive SEO audits and recommendations.</p>
            </div>
            <div class="card">
                <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">AI Content Generation</h3>
                <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Generate high-quality content powered by AI.</p>
            </div>
        </div>
        <a href="/services" class="btn btn-primary">View All Services</a>
    </section>
    
    <section class="section section-testimonials">
        <div class="container grid-2">
            <div>
                <img src="https://images.pexels.com/photos/7230225/pexels-photo-7230225.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop" alt="Customer Testimonial 1" style="border-radius: 50%; width: 80px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);">
                <blockquote style="font-family: 'Inter', sans-serif; color: var(--color-text);">"Jessie AI CMS has transformed our workflow and boosted our productivity!"</blockquote>
                <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">- Alex Johnson, Digital Marketer</p>
            </div>
            <div>
                <img src="https://images.pexels.com/photos/3801426/pexels-photo-3801426.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop" alt="Customer Testimonial 2" style="border-radius: 50%; width: 80px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);">
                <blockquote style="font-family: 'Inter', sans-serif; color: var(--color-text);">"The SEO tools are incredible! Our rankings have never been better."</blockquote>
                <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">- Maria Lopez, Content Creator</p>
            </div>
        </div>
    </section>
    
    <section class="section section-cta">
        <div class="container">
            <h2 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Ready to Transform Your Content Strategy?</h2>
            <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Join thousands of satisfied users and take your content to the next level with Jessie AI CMS.</p>
            <a href="#services" class="btn btn-primary">Start Your Journey</a>
        </div>
    </section>
    
    <section class="section section-stats">
        <div class="container grid-4">
            <div>
                <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">5 Years</h3>
                <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">In Business</p>
            </div>
            <div>
                <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">200+</h3>
                <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Clients Served</p>
            </div>
            <div>
                <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">300+</h3>
                <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Projects Completed</p>
            </div>
        </div>
    </section>
</main>

<?php
// Include footer
if (isset($theme_path) && file_exists($theme_path . '/footer.php')) {
    include $theme_path . '/footer.php';
}