<?php
/**
 * Portfolio Page
 * Generated by AI Designer for Jessie AI CMS
 * 
 * @package Theme
 */

// Page configuration
$page_title = 'Portfolio | Jessie AI CMS';
$page_name = 'portfolio';

// Include header
if (isset($theme_path) && file_exists($theme_path . '/header.php')) {
    include $theme_path . '/header.php';
}
?>

<main>
    <section class="section section-hero" style="background: linear-gradient(to bottom right, var(--color-primary), rgba(29, 78, 216, 0.8));">
        <div class="container">
            <h1 style="font-family: 'Inter', sans-serif; color: #FFFFFF;">Transform Your Content Strategy</h1>
            <p style="font-family: 'Inter', sans-serif; color: #FFFFFF;">Boost your productivity with AI workflows and elevate your SEO game.</p>
            <a href="#portfolio" class="btn btn-primary">Explore Our Solutions</a>
        </div>
    </section>
    
    <section class="section section-portfolio">
        <div class="container">
            <h2 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Our Work</h2>
            <div class="filter">
                <button class="btn btn-secondary">All</button>
                <button class="btn btn-secondary">AI Workflows</button>
                <button class="btn btn-secondary">N8N Integration</button>
                <button class="btn btn-secondary">SEO Tools</button>
            </div>
            <div class="grid grid-3">
                <div class="card">
                    <img src="https://images.pexels.com/photos/6804091/pexels-photo-6804091.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop" alt="AI Workflows">
                    <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">AI Workflows</h3>
                </div>
                <div class="card">
                    <img src="https://images.pexels.com/photos/3865558/pexels-photo-3865558.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop" alt="N8N Integration">
                    <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">N8N Integration</h3>
                </div>
                <div class="card">
                    <img src="https://images.pexels.com/photos/267415/pexels-photo-267415.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop" alt="SEO Tools">
                    <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Advanced SEO Tools</h3>
                </div>
            </div>
        </div>
    </section>
    
    <section class="section section-process">
        <div class="container">
            <h2 style="font-family: 'Inter', sans-serif; color: var(--color-text);">How It Works</h2>
            <div class="grid grid-4">
                <div class="card">
                    <i class="fas fa-brain"></i>
                    <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">1. AI-Powered Ideas</h3>
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Generate content ideas using AI technology.</p>
                </div>
                <div class="card">
                    <i class="fas fa-cogs"></i>
                    <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">2. Seamless Integration</h3>
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Integrate with N8N for automation.</p>
                </div>
                <div class="card">
                    <i class="fas fa-chart-line"></i>
                    <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">3. Optimize Content</h3>
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Use advanced SEO tools to optimize your content.</p>
                </div>
                <div class="card">
                    <i class="fas fa-paper-plane"></i>
                    <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">4. Launch & Analyze</h3>
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Launch your campaigns and analyze the results.</p>
                </div>
            </div>
        </div>
    </section>
    
    <section class="section section-cta" style="background-color: var(--color-primary);">
        <div class="container">
            <h2 style="font-family: 'Inter', sans-serif; color: #FFFFFF;">Ready to Elevate Your Content?</h2>
            <p style="font-family: 'Inter', sans-serif; color: #FFFFFF;">Join us at Jessie AI CMS and transform your digital marketing strategy today.</p>
            <a href="#contact" class="btn btn-secondary">Get Started</a>
        </div>
    </section>
</main>

<?php
// Include footer
if (isset($theme_path) && file_exists($theme_path . '/footer.php')) {
    include $theme_path . '/footer.php';
}