<?php
/**
 * Pricing Page
 * Generated by AI Designer for Jessie AI CMS
 * 
 * @package Theme
 */

// Page configuration
$page_title = 'Pricing | Jessie AI CMS';
$page_name = 'pricing';

// Include header
if (isset($theme_path) && file_exists($theme_path . '/header.php')) {
    include $theme_path . '/header.php';
}
?>

<main>
    <section class="section section-hero" style="background: linear-gradient(to right, var(--color-primary), #F3F4F6);">
        <div class="container">
            <h1 class="text-4xl font-bold text-white">Unlock Your Content's Potential with Jessie AI CMS</h1>
            <p class="text-lg text-white mt-2">Boost your productivity with AI workflows and transform your content strategy.</p>
            <a href="#pricing" class="btn btn-primary mt-4">Get Started</a>
        </div>
    </section>

    <section class="section section-pricing">
        <div class="container">
            <h2 class="text-3xl font-bold text-center">Our Pricing Plans</h2>
            <div class="grid grid-3 gap-6 mt-6">
                <div class="card p-6 shadow-lg rounded-lg">
                    <h3 class="text-2xl font-semibold">Basic</h3>
                    <p class="text-xl font-bold mt-2">$19/month</p>
                    <ul class="mt-4">
                        <li><i class="fas fa-check-circle"></i> AI-driven workflows</li>
                        <li><i class="fas fa-check-circle"></i> Basic SEO tools</li>
                        <li><i class="fas fa-check-circle"></i> Theme builder access</li>
                    </ul>
                    <a href="#" class="btn btn-secondary mt-4">Choose Plan</a>
                </div>
                <div class="card p-6 shadow-lg rounded-lg">
                    <h3 class="text-2xl font-semibold">Pro</h3>
                    <p class="text-xl font-bold mt-2">$49/month</p>
                    <ul class="mt-4">
                        <li><i class="fas fa-check-circle"></i> Everything in Basic</li>
                        <li><i class="fas fa-check-circle"></i> Advanced SEO tools</li>
                        <li><i class="fas fa-check-circle"></i> N8N integration</li>
                    </ul>
                    <a href="#" class="btn btn-secondary mt-4">Choose Plan</a>
                </div>
                <div class="card p-6 shadow-lg rounded-lg">
                    <h3 class="text-2xl font-semibold">Enterprise</h3>
                    <p class="text-xl font-bold mt-2">Contact Us</p>
                    <ul class="mt-4">
                        <li><i class="fas fa-check-circle"></i> All Pro features</li>
                        <li><i class="fas fa-check-circle"></i> Custom solutions</li>
                        <li><i class="fas fa-check-circle"></i> Dedicated support</li>
                    </ul>
                    <a href="#" class="btn btn-secondary mt-4">Contact Us</a>
                </div>
            </div>
        </div>
    </section>

    <section class="section section-features-comparison">
        <div class="container">
            <h2 class="text-3xl font-bold text-center">Feature Comparison</h2>
            <table class="mt-6 w-full text-left border-collapse">
                <thead>
                    <tr>
                        <th class="border-b-2 border-gray-300 p-4">Feature</th>
                        <th class="border-b-2 border-gray-300 p-4">Basic</th>
                        <th class="border-b-2 border-gray-300 p-4">Pro</th>
                        <th class="border-b-2 border-gray-300 p-4">Enterprise</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="border-b border-gray-200 p-4">AI Workflows</td>
                        <td class="border-b border-gray-200 p-4">✔️</td>
                        <td class="border-b border-gray-200 p-4">✔️</td>
                        <td class="border-b border-gray-200 p-4">✔️</td>
                    </tr>
                    <tr>
                        <td class="border-b border-gray-200 p-4">N8N Integration</td>
                        <td class="border-b border-gray-200 p-4">❌</td>
                        <td class="border-b border-gray-200 p-4">✔️</td>
                        <td class="border-b border-gray-200 p-4">✔️</td>
                    </tr>
                    <tr>
                        <td class="border-b border-gray-200 p-4">Advanced SEO Tools</td>
                        <td class="border-b border-gray-200 p-4">❌</td>
                        <td class="border-b border-gray-200 p-4">✔️</td>
                        <td class="border-b border-gray-200 p-4">✔️</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </section>

    <section class="section section-faq">
        <div class="container">
            <h2 class="text-3xl font-bold text-center">Frequently Asked Questions</h2>
            <div class="mt-6">
                <details class="mb-4">
                    <summary class="font-semibold text-lg">What is Jessie AI CMS?</summary>
                    <p>Jessie AI CMS is a content management system designed to enhance your digital marketing efforts with AI-driven workflows and advanced SEO tools.</p>
                </details>
                <details class="mb-4">
                    <summary class="font-semibold text-lg">How does the AI work?</summary>
                    <p>Our AI analyzes your content and provides suggestions to optimize your strategy for better engagement and search rankings.</p>
                </details>
                <details class="mb-4">
                    <summary class="font-semibold text-lg">Can I integrate with existing tools?</summary>
                    <p>Yes! Jessie AI CMS integrates seamlessly with N8N and other popular automation tools to streamline your workflow.</p>
                </details>
                <details class="mb-4">
                    <summary class="font-semibold text-lg">What support do you offer?</summary>
                    <p>We provide dedicated support for all our plans, ensuring you have the help you need whenever you need it.</p>
                </details>
            </div>
        </div>
    </section>

    <section class="section section-cta">
        <div class="container text-center">
            <h2 class="text-3xl font-bold">Ready to Elevate Your Content Strategy?</h2>
            <p class="mt-2">Join thousands of satisfied users and take your digital marketing to the next level with Jessie AI CMS.</p>
            <a href="#pricing" class="btn btn-primary mt-4">Sign Up Now</a>
        </div>
    </section>
</main>

<?php
// Include footer
if (isset($theme_path) && file_exists($theme_path . '/footer.php')) {
    include $theme_path . '/footer.php';
}