<?php
/**
 * Services Page
 * Generated by AI Designer for Jessie AI CMS
 * 
 * @package Theme
 */

// Page configuration
$page_title = 'Services | Jessie AI CMS';
$page_name = 'services';

// Include header
if (isset($theme_path) && file_exists($theme_path . '/header.php')) {
    include $theme_path . '/header.php';
}
?>

<main>
    <section class="section section-hero">
        <div class="container">
            <div class="hero-content">
                <h1 style="font-family: 'Inter', sans-serif;">Boost Your Productivity with Jessie AI CMS</h1>
                <p style="font-family: 'Inter', sans-serif;">Transform your content strategy and elevate your SEO game with our advanced AI-driven workflows.</p>
                <a href="#services" class="btn btn-primary">Get Started</a>
            </div>
        </div>
    </section>

    <section class="section section-services">
        <div class="container">
            <h2 style="font-family: 'Inter', sans-serif;">Our Services</h2>
            <div class="grid grid-3">
                <div class="card">
                    <img src="https://images.pexels.com/photos/6804091/pexels-photo-6804091.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop" alt="AI Workflows">
                    <h3 style="font-family: 'Inter', sans-serif;">AI-Driven Workflows</h3>
                    <p style="font-family: 'Inter', sans-serif;">Streamline your content creation with intelligent workflows that adapt to your needs.</p>
                </div>
                <div class="card">
                    <img src="https://images.pexels.com/photos/4312856/pexels-photo-4312856.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop" alt="Theme Builder">
                    <h3 style="font-family: 'Inter', sans-serif;">Theme Builder</h3>
                    <p style="font-family: 'Inter', sans-serif;">Easily create and customize themes that reflect your brand's identity.</p>
                </div>
                <div class="card">
                    <img src="https://images.pexels.com/photos/267415/pexels-photo-267415.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop" alt="SEO Tools">
                    <h3 style="font-family: 'Inter', sans-serif;">Advanced SEO Tools</h3>
                    <p style="font-family: 'Inter', sans-serif;">Utilize cutting-edge AI technology to enhance your SEO strategy and drive traffic.</p>
                </div>
            </div>
        </div>
    </section>

    <section class="section section-process">
        <div class="container">
            <h2 style="font-family: 'Inter', sans-serif;">How It Works</h2>
            <div class="grid grid-3">
                <div class="process-step">
                    <i class="fas fa-cog"></i>
                    <h3 style="font-family: 'Inter', sans-serif;">Set Up Your Account</h3>
                    <p style="font-family: 'Inter', sans-serif;">Get started by creating your account in just a few easy steps.</p>
                </div>
                <div class="process-step">
                    <i class="fas fa-rocket"></i>
                    <h3 style="font-family: 'Inter', sans-serif;">Integrate with N8N</h3>
                    <p style="font-family: 'Inter', sans-serif;">Connect your workflows with N8N for seamless automation.</p>
                </div>
                <div class="process-step">
                    <i class="fas fa-edit"></i>
                    <h3 style="font-family: 'Inter', sans-serif;">Create and Publish</h3>
                    <p style="font-family: 'Inter', sans-serif;">Easily create, edit, and publish content that resonates with your audience.</p>
                </div>
            </div>
        </div>
    </section>

    <section class="section section-pricing">
        <div class="container">
            <h2 style="font-family: 'Inter', sans-serif;">Pricing Plans</h2>
            <div class="grid grid-2">
                <div class="card">
                    <h3 style="font-family: 'Inter', sans-serif;">Basic Plan</h3>
                    <p style="font-family: 'Inter', sans-serif;">Perfect for individuals and small teams.</p>
                    <p style="font-family: 'Inter', sans-serif;'>$19/month</p>
                    <a href="#pricing" class="btn btn-secondary">Choose Plan</a>
                </div>
                <div class="card">
                    <h3 style="font-family: 'Inter', sans-serif;">Pro Plan</h3>
                    <p style="font-family: 'Inter', sans-serif;">Advanced features for growing businesses.</p>
                    <p style="font-family: 'Inter', sans-serif;'>$49/month</p>
                    <a href="#pricing" class="btn btn-secondary">Choose Plan</a>
                </div>
            </div>
        </div>
    </section>

    <section class="section section-faq">
        <div class="container">
            <h2 style="font-family: 'Inter', sans-serif;">Frequently Asked Questions</h2>
            <ul>
                <li style="font-family: 'Inter', sans-serif;">
                    <strong>What is Jessie AI CMS?</strong> A comprehensive content management system powered by AI to enhance your content creation process.
                </li>
                <li style="font-family: 'Inter', sans-serif;">
                    <strong>How does the theme builder work?</strong> Our intuitive theme builder allows you to customize your website effortlessly.
                </li>
                <li style="font-family: 'Inter', sans-serif;">
                    <strong>Can I integrate with other tools?</strong> Yes, Jessie AI CMS integrates seamlessly with N8N and other automation tools.
                </li>
            </ul>
            <a href="#faq" class="btn btn-primary">View All FAQs</a>
        </div>
    </section>

    <section class="section section-cta">
        <div class="container">
            <h2 style="font-family: 'Inter', sans-serif;">Ready to Transform Your Content Strategy?</h2>
            <p style="font-family: 'Inter', sans-serif;">Join Jessie AI CMS today and elevate your digital marketing efforts.</p>
            <a href="#get-started" class="btn btn-primary">Get Started Now</a>
        </div>
    </section>
</main>

<?php
// Include footer
if (isset($theme_path) && file_exists($theme_path . '/footer.php')) {
    include $theme_path . '/footer.php';
}