<?php
/**
 * Team Page
 * Generated by AI Designer for Jessie AI CMS
 * 
 * @package Theme
 */

// Page configuration
$page_title = 'Team | Jessie AI CMS';
$page_name = 'team';

// Include header
if (isset($theme_path) && file_exists($theme_path . '/header.php')) {
    include $theme_path . '/header.php';
}
?>

<main>
    <section class="section section-hero" style="background: linear-gradient(to bottom right, #1D4ED8, #059669);">
        <div class="container">
            <h1 style="font-family: 'Inter', sans-serif; color: white;">Meet Our Team</h1>
            <p style="font-family: 'Inter', sans-serif; color: white;">Innovators in AI-driven content solutions</p>
            <a href="#team-grid" class="btn btn-primary">Join Us</a>
        </div>
    </section>

    <section class="section section-team-grid">
        <div class="container">
            <h2 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Our Team</h2>
            <div class="grid grid-4">
                <div class="card">
                    <img src="https://images.pexels.com/photos/5818271/pexels-photo-5818271.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop" alt="Jessie Smith">
                    <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Jessie Smith</h3>
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">CEO & Founder</p>
                    <div>
                        <a href="#"><i class="fab fa-linkedin"></i></a>
                        <a href="#"><i class="fab fa-twitter"></i></a>
                    </div>
                </div>
                <div class="card">
                    <img src="https://images.pexels.com/photos/8383884/pexels-photo-8383884.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop" alt="Alex Johnson">
                    <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Alex Johnson</h3>
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">CTO</p>
                    <div>
                        <a href="#"><i class="fab fa-linkedin"></i></a>
                        <a href="#"><i class="fab fa-twitter"></i></a>
                    </div>
                </div>
                <div class="card">
                    <img src="https://images.pexels.com/photos/29078099/pexels-photo-29078099.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop" alt="Maria Garcia">
                    <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Maria Garcia</h3>
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Head of Marketing</p>
                    <div>
                        <a href="#"><i class="fab fa-linkedin"></i></a>
                        <a href="#"><i class="fab fa-twitter"></i></a>
                    </div>
                </div>
                <div class="card">
                    <img src="https://images.pexels.com/photos/10819067/pexels-photo-10819067.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop" alt="David Lee">
                    <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">David Lee</h3>
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Lead Developer</p>
                    <div>
                        <a href="#"><i class="fab fa-linkedin"></i></a>
                        <a href="#"><i class="fab fa-twitter"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="section section-culture">
        <div class="container">
            <h2 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Our Culture</h2>
            <div class="grid grid-2">
                <div class="card">
                    <img src="https://images.pexels.com/photos/7971170/pexels-photo-7971170.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop" alt="Team Collaboration">
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">We foster collaboration and creativity, empowering our team to innovate.</p>
                </div>
                <div class="card">
                    <img src="https://images.pexels.com/photos/5439481/pexels-photo-5439481.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop" alt="Team Meeting">
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Regular team meetings ensure everyone stays aligned and inspired.</p>
                </div>
            </div>
        </div>
    </section>

    <section class="section section-values">
        <div class="container">
            <h2 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Core Values</h2>
            <div class="grid grid-3">
                <div class="card">
                    <i class="fas fa-lightbulb"></i>
                    <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Innovation</h3>
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">We continuously seek new ideas and technologies to enhance our offerings.</p>
                </div>
                <div class="card">
                    <i class="fas fa-users"></i>
                    <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Teamwork</h3>
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Collaboration is at the heart of our success, bringing diverse perspectives together.</p>
                </div>
                <div class="card">
                    <i class="fas fa-cogs"></i>
                    <h3 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Excellence</h3>
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">We strive for excellence in everything we do, ensuring high-quality results.</p>
                </div>
            </div>
        </div>
    </section>

    <section class="section section-cta">
        <div class="container">
            <h2 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Ready to Transform Your Content Strategy?</h2>
            <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Join us at Jessie AI CMS and boost your productivity with our AI-driven workflows.</p>
            <a href="#contact" class="btn btn-secondary">Get Started</a>
        </div>
    </section>
</main>

<?php
// Include footer
if (isset($theme_path) && file_exists($theme_path . '/footer.php')) {
    include $theme_path . '/footer.php';
}