<?php
/**
 * Testimonials Page
 * Generated by AI Designer for Jessie AI CMS
 * 
 * @package Theme
 */

// Page configuration
$page_title = 'Testimonials | Jessie AI CMS';
$page_name = 'testimonials';

// Include header
if (isset($theme_path) && file_exists($theme_path . '/header.php')) {
    include $theme_path . '/header.php';
}
?>

<main>
    <section class="section section-hero" style="background: linear-gradient(135deg, var(--color-primary) 50%, #FFFFFF 50%);">
        <div class="container text-center">
            <h1 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Transform Your Content Strategy with Jessie AI CMS</h1>
            <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Boost your productivity and elevate your SEO game with our cutting-edge AI technology.</p>
            <a href="#testimonials" class="btn btn-primary">See Testimonials</a>
        </div>
    </section>

    <section class="section section-testimonials">
        <div class="container">
            <h2 style="font-family: 'Inter', sans-serif; color: var(--color-text);">What Our Clients Say</h2>
            <div class="grid grid-3">
                <div class="card">
                    <img src="https://images.pexels.com/photos/15300255/pexels-photo-15300255.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop" alt="Client 1">
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">"Jessie AI CMS has completely transformed our content workflow. We save hours each week!"</p>
                    <p><strong>- Alex Johnson, Digital Marketer</strong></p>
                </div>
                <div class="card">
                    <img src="https://images.pexels.com/photos/5878516/pexels-photo-5878516.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop" alt="Client 2">
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">"The integration with N8N has streamlined our processes. Highly recommend!"</p>
                    <p><strong>- Maria Gomez, Content Creator</strong></p>
                </div>
                <div class="card">
                    <img src="https://images.pexels.com/photos/11279323/pexels-photo-11279323.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop" alt="Client 3">
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">"The AI tools for SEO are top-notch. We’ve seen a significant increase in traffic!"</p>
                    <p><strong>- Liam Smith, SEO Specialist</strong></p>
                </div>
                <div class="card">
                    <img src="https://images.pexels.com/photos/7876085/pexels-photo-7876085.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop" alt="Client 4">
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">"Creating content has never been easier. Jessie AI CMS is a game-changer!"</p>
                    <p><strong>- Sarah Lee, Brand Strategist</strong></p>
                </div>
                <div class="card">
                    <img src="https://images.pexels.com/photos/8292825/pexels-photo-8292825.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop" alt="Client 5">
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">"The theme builder is intuitive and helps us maintain our brand identity effortlessly."</p>
                    <p><strong>- David Brown, Marketing Manager</strong></p>
                </div>
                <div class="card">
                    <img src="https://images.pexels.com/photos/8292825/pexels-photo-8292825.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop" alt="Client 6">
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">"Professional, approachable, and effective. Jessie AI CMS ticks all the boxes!"</p>
                    <p><strong>- Emily White, Content Director</strong></p>
                </div>
            </div>
        </div>
    </section>

    <section class="section section-stats">
        <div class="container text-center">
            <h2 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Our Impact</h2>
            <div class="grid grid-4">
                <div class="stat">
                    <h3 style="font-family: 'Inter', sans-serif; color: var(--color-primary);">5+</h3>
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Years of Experience</p>
                </div>
                <div class="stat">
                    <h3 style="font-family: 'Inter', sans-serif; color: var(--color-primary);">300+</h3>
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Happy Clients</p>
                </div>
                <div class="stat">
                    <h3 style="font-family: 'Inter', sans-serif; color: var(--color-primary);">1000+</h3>
                    <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Projects Completed</p>
                </div>
            </div>
        </div>
    </section>

    <section class="section section-clients">
        <div class="container">
            <h2 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Trusted by Leading Brands</h2>
            <div class="grid grid-4">
                <img src="https://images.pexels.com/photos/4252961/pexels-photo-4252961.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop" alt="Client Logo 1">
                <img src="https://images.pexels.com/photos/19807747/pexels-photo-19807747.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop" alt="Client Logo 2">
                <img src="https://images.pexels.com/photos/35440180/pexels-photo-35440180.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop" alt="Client Logo 3">
                <img src="https://images.pexels.com/photos/10884108/pexels-photo-10884108.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop" alt="Client Logo 4">
            </div>
        </div>
    </section>

    <section class="section section-cta">
        <div class="container text-center">
            <h2 style="font-family: 'Inter', sans-serif; color: var(--color-text);">Ready to Elevate Your Content Strategy?</h2>
            <p style="font-family: 'Inter', sans-serif; color: var(--color-text);">Join the revolution of AI-driven content creation today!</p>
            <a href="#signup" class="btn btn-secondary">Get Started Now</a>
        </div>
    </section>
</main>

<?php
// Include footer
if (isset($theme_path) && file_exists($theme_path . '/footer.php')) {
    include $theme_path . '/footer.php';
}