<?php /** 404 Page */ ?>
<div class="jd-page" style="text-align: center; min-height: 60vh; display: flex; flex-direction: column; align-items: center; justify-content: center;">
    <h1 style="font-size: 6rem; background: var(--jd-gradient); -webkit-background-clip: text; -webkit-text-fill-color: transparent; margin-bottom: 16px;">404</h1>
    <p class="jd-page-sub">This page doesn't exist. Maybe it was generated by AI and escaped? 🐕</p>
    <a href="/" class="jd-btn jd-btn-primary"><i class="fas fa-home"></i> Back Home</a>
</div>
