<?php
/** Themes Showcase — Marquee of AI-generated themes */
$themeNames = [];
$themesDir = dirname(__DIR__, 2);
if (is_dir($themesDir)) {
    foreach (scandir($themesDir) as $d) {
        if ($d[0] === '.' || $d === 'core' || $d === 'presets' || $d === 'jtb' || $d === 'blank' || $d === 'default' || $d === 'jessie' || $d === 'jessie-demo') continue;
        $jsonPath = $themesDir . '/' . $d . '/theme.json';
        if (file_exists($jsonPath)) {
            $j = json_decode(file_get_contents($jsonPath), true);
            $themeNames[] = $j['name'] ?? ucwords(str_replace('-', ' ', $d));
        }
    }
}
if (empty($themeNames)) {
    $themeNames = ['FlowForge SaaS', 'Nordic Brew Coffee', 'Sentinel Shield', 'Chiaroscuro Photography', 'Amber Grove Restaurant', 'Velocity Bank', 'Lexington Legal', 'Summit Pulse Fitness'];
}
// Double for seamless marquee
$all = array_merge($themeNames, $themeNames);
$colors = ['#8b5cf6','#06b6d4','#f59e0b','#ec4899','#10b981','#ef4444','#a78bfa','#22d3ee'];
?>
<section class="jd-section" id="themes-showcase">
    <div class="jd-section-header jd-fade-up">
        <span class="jd-section-badge"><i class="fas fa-palette"></i> AI Themes</span>
        <h2 class="jd-section-title"><?= count($themeNames) ?> AI-Generated Themes</h2>
        <p class="jd-section-desc">Every theme is unique — generated by AI with matching pages, content, images, and CSS. From restaurants to fintech, photography to SaaS.</p>
    </div>
    <div class="jd-themes-marquee jd-fade-up">
        <div class="jd-themes-track">
            <?php foreach ($all as $i => $name):
                $c = $colors[$i % count($colors)];
            ?>
            <div class="jd-theme-preview">
                <div class="jd-theme-preview-bar">
                    <div class="jd-theme-preview-dot"></div>
                    <div class="jd-theme-preview-dot"></div>
                    <div class="jd-theme-preview-dot"></div>
                </div>
                <div class="jd-theme-preview-body">
                    <div class="jd-theme-preview-line short" style="background: <?= $c ?>40;"></div>
                    <div class="jd-theme-preview-line medium"></div>
                    <div class="jd-theme-preview-line"></div>
                    <div class="jd-theme-preview-line short"></div>
                    <div class="jd-theme-preview-line accent" style="background: <?= $c ?>30;"></div>
                    <div class="jd-theme-preview-line medium"></div>
                </div>
                <div class="jd-theme-preview-name"><?= htmlspecialchars($name) ?></div>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
</section>
