<?php
/**
 * AI-Generated Theme Layout
 * Generated by AI Theme Builder
 */

if (!defined('CMS_ROOT')) define('CMS_ROOT', dirname(__DIR__, 2));
if (!defined('CMS_APP')) define('CMS_APP', CMS_ROOT . '/app');

require_once CMS_APP . '/helpers/functions.php';

if (file_exists(CMS_ROOT . '/includes/helpers/menu.php')) {
    require_once CMS_ROOT . '/includes/helpers/menu.php';
}

$jtbBootPath = CMS_ROOT . '/plugins/jessie-theme-builder/includes/jtb-frontend-boot.php';
if (file_exists($jtbBootPath)) require_once $jtbBootPath;

$themeConfig = get_theme_config();
$themeOptions = $themeConfig['options'] ?? [];
$showHeader = $themeOptions['show_header'] ?? true;
$showFooter = $themeOptions['show_footer'] ?? true;

$siteName = theme_get('brand.site_name', get_site_name());
$siteLogo = theme_get('brand.logo', get_site_logo());
$tsLogo = theme_get('brand.logo') ?: $siteLogo;

$pageData = $page ?? [];
if (!empty($title) && empty($pageData['title'])) $pageData['title'] = $title;
$isTbPage = !empty($page['is_tb_page']);

$themeCssVariables = generate_theme_css_variables($themeConfig);
$themePath = '/themes/' . basename(__DIR__);
?><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?= render_seo_meta($pageData) ?>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@400;500;600;700&amp;family=Urbanist:wght@400;500;600;700&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/assets/css/fontawesome.min.css">
    <link rel="stylesheet" href="/assets/css/tb-frontend.css">
    <link rel="stylesheet" href="<?= $themePath ?>/assets/css/style.css">
    <style>
<?= $themeCssVariables ?>
<?= generate_studio_css_overrides() ?>
    </style>
<?= function_exists("theme_render_favicon") ? theme_render_favicon() : "" ?>
<?= function_exists("theme_render_og_image") ? theme_render_og_image() : "" ?>
</head>
<body class="<?= esc(get_body_class() ?? '') ?><?= $isTbPage ? ' tb-page' : '' ?>">
<?= function_exists("theme_render_announcement_bar") ? theme_render_announcement_bar() : "" ?>

<?php if ($showHeader): ?>
<a href="#main-content" class="skip-nav">Skip to content</a>
<header class="site-header" id="siteHeader">
    <div class="header-container">
        <a href="/" class="header-logo" data-ts="brand.logo">
            <?php if ($tsLogo): ?>
                <img src="<?= esc($tsLogo) ?>" alt="<?= esc(theme_get('brand.site_name', $siteName)) ?>">
            <?php else: ?>
                <span class="logo-text" data-ts="brand.site_name"><?= esc(theme_get('brand.site_name', $siteName)) ?></span>
            <?php endif; ?>
        </a>
        <div class="header-center">
            <nav class="header-nav" id="headerNav">
                <?= render_menu('header', ['class' => 'nav-links', 'link_class' => 'nav-link', 'wrap' => false]) ?>
            </nav>
        </div>
        <div class="header-actions">
            <a href="<?= esc(theme_get('header.cta_link', '#contact')) ?>" 
               class="header-cta"
               data-ts="header.cta_text"
               data-ts-href="header.cta_link">
                <span class="cta-icon"><i class="fas fa-robot"></i></span>
                <span class="cta-label"><?= esc(theme_get('header.cta_text', 'Schedule Demo')) ?></span>
            </a>
            <button class="mobile-toggle" id="mobileToggle" aria-label="Menu">
                <span></span><span></span><span></span>
            </button>
        </div>
    </div>
    <div class="header-glow"></div>
</header>
<div class="mobile-overlay" id="mobileOverlay"></div>
<?php endif; ?>

<?php if ($isTbPage): ?>
    <?= $content ?? '' ?>
<?php else: ?>
    <main id="main-content"><?= $content ?? '' ?></main>
<?php endif; ?>

<?php if ($showFooter): ?>
<footer class="site-footer">
    <div class="footer-wave">
        <svg viewBox="0 0 1440 120" preserveAspectRatio="none">
            <path d="M0,60 C360,120 720,0 1080,60 C1260,90 1380,75 1440,60 L1440,120 L0,120 Z" fill="currentColor"/>
        </svg>
    </div>
    <div class="footer-main">
        <div class="container">
            <div class="footer-grid">
                <div class="footer-brand-col">
                    <a href="/" class="footer-logo" data-ts="brand.logo">
                        <?php if ($tsLogo): ?>
                            <img src="<?= esc($tsLogo) ?>" alt="<?= esc(theme_get('brand.site_name', $siteName)) ?>" height="44">
                        <?php else: ?>
                            <span class="logo-text" data-ts="brand.site_name"><?= esc(theme_get('brand.site_name', $siteName)) ?></span>
                        <?php endif; ?>
                    </a>
                    <p class="footer-tagline" data-ts="footer.description">
                        <?= esc(theme_get('footer.description', 'Revolutionizing last-mile delivery with autonomous robots and AI-powered route optimization for seamless urban logistics.')) ?>
                    </p>
                    <div class="footer-social">
                        <?php if (theme_get('footer.facebook')): ?>
                        <a href="<?= esc(theme_get('footer.facebook')) ?>" class="social-link" aria-label="Facebook"><i class="fab fa-facebook-f"></i></a>
                        <?php endif; ?>
                        <?php if (theme_get('footer.instagram')): ?>
                        <a href="<?= esc(theme_get('footer.instagram')) ?>" class="social-link" aria-label="Instagram"><i class="fab fa-instagram"></i></a>
                        <?php endif; ?>
                        <?php if (theme_get('footer.linkedin')): ?>
                        <a href="<?= esc(theme_get('footer.linkedin')) ?>" class="social-link" aria-label="LinkedIn"><i class="fab fa-linkedin-in"></i></a>
                        <?php endif; ?>
                        <?php if (theme_get('footer.youtube')): ?>
                        <a href="<?= esc(theme_get('footer.youtube')) ?>" class="social-link" aria-label="YouTube"><i class="fab fa-youtube"></i></a>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="footer-nav-col">
                    <h4 class="footer-heading" data-ts="footer.nav_title"><?= esc(theme_get('footer.nav_title', 'Navigation')) ?></h4>
                    <?= render_menu('footer', ['class' => 'footer-links', 'link_class' => 'footer-link', 'wrap' => false]) ?>
                </div>
                <div class="footer-services-col">
                    <h4 class="footer-heading" data-ts="footer.services_title"><?= esc(theme_get('footer.services_title', 'Solutions')) ?></h4>
                    <ul class="footer-list">
                        <li><a href="#"><i class="fas fa-chevron-right"></i> Same-Day Delivery</a></li>
                        <li><a href="#"><i class="fas fa-chevron-right"></i> Route Optimization</a></li>
                        <li><a href="#"><i class="fas fa-chevron-right"></i> Fleet Management</a></li>
                        <li><a href="#"><i class="fas fa-chevron-right"></i> API Integration</a></li>
                    </ul>
                </div>
                <div class="footer-contact-col">
                    <h4 class="footer-heading" data-ts="footer.contact_title"><?= esc(theme_get('footer.contact_title', 'Get In Touch')) ?></h4>
                    <ul class="footer-contact-list">
                        <?php if (theme_get('footer.address')): ?>
                        <li>
                            <i class="fas fa-map-marker-alt"></i>
                            <span data-ts="footer.address"><?= esc(theme_get('footer.address')) ?></span>
                        </li>
                        <?php endif; ?>
                        <?php if (theme_get('footer.phone')): ?>
                        <li>
                            <i class="fas fa-phone"></i>
                            <a href="tel:<?= esc(theme_get('footer.phone')) ?>" data-ts="footer.phone"><?= esc(theme_get('footer.phone')) ?></a>
                        </li>
                        <?php endif; ?>
                        <?php if (theme_get('footer.email')): ?>
                        <li>
                            <i class="fas fa-envelope"></i>
                            <a href="mailto:<?= esc(theme_get('footer.email')) ?>" data-ts="footer.email"><?= esc(theme_get('footer.email')) ?></a>
                        </li>
                        <?php endif; ?>
                        <?php if (theme_get('footer.hours')): ?>
                        <li>
                            <i class="fas fa-clock"></i>
                            <span data-ts="footer.hours"><?= esc(theme_get('footer.hours')) ?></span>
                        </li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="container">
            <div class="footer-bottom-inner">
                <p class="copyright" data-ts="footer.copyright">
                    <?= theme_get('footer.copyright') ? esc(theme_get('footer.copyright')) : '&copy; ' . date('Y') . ' ' . esc(theme_get('brand.site_name', $siteName)) . '. All rights reserved.' ?>
                </p>
                <div class="footer-badges">
                    <span class="badge"><i class="fas fa-shield-alt"></i> SOC 2 Certified</span>
                    <span class="badge"><i class="fas fa-leaf"></i> Carbon Neutral</span>
                </div>
            </div>
        </div>
    </div>
</footer>
<?php endif; ?>

<script src="<?= $themePath ?>/assets/js/main.js"></script>
<?php if (function_exists('cms_ab_testing_widget')): echo cms_ab_testing_widget(); endif; ?>
<?php if (function_exists('ai_theme_chat_widget')): echo ai_theme_chat_widget(); endif; ?>
</body>
</html>